      SUBROUTINE BQUAD(F,N,X,EPS,ANS,ERREST)
C
C TO INTEGRATE F(X) FROM X(1) TO X(N) WITH ABSOLUTE ACCURACY EPS,
C SET DEFAULT VALUES OF PARAMETERS AND CALL R2QUAD.  ALL THE DISTINCT
C POINTS AMONG X(2), ..., X(N-1) ARE USED AS INITIAL BREAKPOINTS.
C THIS PROGRAM IS USEFUL FOR INTEGRATING FUNCTIONS WHICH HAVE
C DISCONTINUITIES IN DERIVATIVES AT THE BREAKPOINTS, BUT NOT
C DISCONTINUITIES IN VALUE.
C
      REAL F,X(N),EPS,ANS,ERREST,HSAMPL
      LOGICAL MONOR
      EXTERNAL F
C
      HSAMPL = 0.125
      NFCALL = 2000
      LYSTAK = 250
      KMAXEX = 8
      KDIVID = 4
      JPRINT = 0
C
C/6S
C     IF (N .LT. 2) CALL SETERR
C    *   (29H BQUAD - N MUST BE AT LEAST 2, 29, 1, 2)
C     IF (.NOT.MONOR(X,N,1)) CALL SETERR
C    *   (37H BQUAD - THE X ARRAY MUST BE MONOTONE, 37, 2, 2)
C/7S
      IF (N .LT. 2) CALL SETERR
     *   (' BQUAD - N MUST BE AT LEAST 2', 29, 1, 2)
      IF (.NOT.MONOR(X,N,1)) CALL SETERR
     *   (' BQUAD - THE X ARRAY MUST BE MONOTONE', 37, 2, 2)
C/
C
      CALL R2QUAD(F,N,X,EPS,HSAMPL,NFCALL,LYSTAK,KMAXEX,KDIVID,
     *      JPRINT,ANS,ERREST,KWARN)
C
C
C/6S
C     IF (ERREST  .GT.  EPS) CALL SETERR
C    *   (54H BQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS,
C    *    54, 3, 1)
C/7S
      IF (ERREST  .GT.  EPS) CALL SETERR
     *   (' BQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS',
     *    54, 3, 1)
C/
C
C/6S
C     IF (KWARN .LT. 0 ) CALL SETERR
C    *   (59H BQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN
C    *    ,59, 4, 2)
C/7S
      IF (KWARN .LT. 0 ) CALL SETERR
     *   (' BQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN'
     *    ,59, 4, 2)
C/
C
       RETURN
      END
