      DOUBLE PRECISION FUNCTION D1QFUN(F,X)
C
C FUNCTION TO BE INTEGRATED USING D1QDAP AND D1QINT.
C NEXP .GT. 1 IF CHANGE OF VARIABLE HAS BEEN MADE.
C
      DOUBLE PRECISION F,X,XBOT,DELX,V
      EXTERNAL F
      COMMON /D1QCM3/ XBOT,DELX,R(3),RL(3),NEXP,KEXT,KLAST
C
      IF (NEXP.GT.1) GO TO 10
         D1QFUN = F(X)
         RETURN
C
   10 V = ((X-XBOT)/DELX)**(NEXP-1)
      D1QFUN = FLOAT(NEXP)*V*F(XBOT+V*(X-XBOT))
      RETURN
      END
