      SUBROUTINE D1QUAD(F,A,B,EPS,HS,NFCALL,LYSTAK,KMAXEX,KDIVID,
     X          JPRINT,NUMINT,ANS,ERREST,KWARN)
C
C INTEGRATE F(X) FROM A TO B WITH ABSOLUTE ACCURACY EPS.
C MUST TAKE STEP SIZE AT LEAST AS SMALL AS HS*DABS(B-A).
C USE NO MORE THAN NFCALL SAMPLING POINTS, OR CALLS TO F.
C FOR TEMPORARY STORAGE OF FUNCTION VALUES, ALLOCATE LYSTAK WORDS.
C DO AT MOST KMAXEX EXTRAPOLATIONS.
C DO NOT DIVIDE INTERVAL UNTIL AFTER KDIVID EXTRAPOLATIONS.
C JPRINT = 0 FOR NO PRINTING, 1 FOR SOME, 2 FOR LOTS.
C TO START, DIVIDE (A,B) INTO NUMINT EQUAL INTERVALS.
C RETURN VALUE AND ITS ESTIMATED ERROR IN ANS AND ERREST.
C RETURN KWARN AS WARNING FLAG.
C
C FUNCTION ISTKQU RETURNS AMOUNT OF SPACE LEFT IN STACK.
C FUNCTION ISTKGT ALLOCATES SPACE IN STACK AND GIVES POINTER TO IT.
C SUBROUTINE LEAVE DE-ALLOCATES SPACE IN STACK.
C THE DEFAULT STACK LENGTH IS 500 DOUBLE PRECISION WORDS.
C IF A LARGER STACK IS NECESSARY, THE PROGRAM CALLING D1QUAD OR DQUAD
C SHOULD INITIALIZE THE STACK  USING SUBROUTINE ISTKIN.
C
      DOUBLE PRECISION F,A,B,EPS,HS,ANS,ERREST,D1MACH
      EXTERNAL F
      COMMON /D1QCM1/ DLARGE,DSMALL,DROUND,HSAMPL,HSMALL,ESMALL,
     X   NPRINT,NUM,MAXY,MAXINT,MAXF,KMIN,KMAX,KDIV,NMAX
      DOUBLE PRECISION DLARGE,DSMALL,DROUND,HSAMPL,HSMALL,ESMALL
      DOUBLE PRECISION DLOG
C
      COMMON/CSTAK/DS
      DOUBLE PRECISION DS(500)
      INTEGER IS(1000)
      EQUIVALENCE (DS(1),IS(1))
C
C        MACHINE- AND PRECISION-DEPENDENT NUMBERS
C
      HSMALL = 50.D0*D1MACH(4)
      DROUND = 50.D0*D1MACH(4)
      DSMALL = 10.D0*D1MACH(1)
      DLARGE = 0.1D0*D1MACH(2)
C
C         PARAMETERS
C
      NPRINT = JPRINT
      NUM = MAX0(1,NUMINT)
      KMIN = 2
      KMAX = MAX0(4,MIN0(12,KMAXEX))
      KMAX = 2*(KMAX/2)
      KDIV = MIN0(MAX0(KDIVID,4),KMAX)
      KDIV = 2*(KDIV/2)
      HSAMPL = DMIN1(HS,1.D0)
      ESMALL = EPS*1.D-3
      NMAX = 1.-DLOG(DROUND)/DLOG(6.D0)
      NMAX = MIN0(25,NMAX)
C
C        ALLOCATE SCRATCH SPACE
C
      MAXY = MAX0(NUM+7,LYSTAK)
      MAXF = MAX0(4*NUM+1,NFCALL)
      MAXINT=1.-DLOG(HSMALL)/DLOG(2.D0)
      MAXINT = MAX0(MAXINT,NUM+2)
      CALL ENTER(0)
      NSHORT = ISTKQU(2)-2*MAXINT
      IF (NSHORT .LT. 0) GO TO 120
      IIDIV = ISTKGT(2*MAXINT,2)
      II = IIDIV+MAXINT
      NSHORT = ISTKQU(4)-(MAXINT+1+MAXY)
      IF (NSHORT .LT. 0) GO TO 120
      IX = ISTKGT(MAXINT+1+MAXY,4)
      IY = IX+MAXINT+1
C
      DS(IX)=A
      DO 110 J=1,NUM
         JJ=IX+J
  110    DS(JJ)=A+FLOAT(J)*(B-A)/FLOAT(NUM)
      DS(JJ)=B
C
      CALL D1QDAP(F,A,B,EPS,DS(IY),DS(IX),IS(II),IS(IIDIV),
     X    ANS,ERREST,KWARN)
C
      CALL LEAVE
      RETURN
C
  120 KWARN = NSHORT
      ANS = 0.
      ERREST = DLARGE
      CALL LEAVE
      RETURN
      END
