      SUBROUTINE DGQEX2(N, X, W)
      INTEGER N
      DOUBLE PRECISION X(N), W(N)
      COMMON /CSTAK/ D
      DOUBLE PRECISION D(500)
      INTEGER IA, IB, IC, IN, ISTKGT, NERR, NERROR
      DOUBLE PRECISION R(500)
      EQUIVALENCE (D(1), R(1))
C J. L. BLUE, 15 DEC 77
C CALCULATE GAUSS QUADRATURE RULES ON (-INFINITY, INFINITY),
C    WITH WEIGHT FUNCTION EXP(-X**2)
C USE DGAUSQ = SACK-DONOVAN PROGRAM,
C   WITH HERMITE POLYNOMIALS.
C/6S
C     IF (N .LT. 1) CALL SETERR(18H DGQEX2 - N .LT. 1, 18, 1, 2)
C/7S
      IF (N .LT. 1) CALL SETERR(' DGQEX2 - N .LT. 1', 18, 1, 2)
C/
      CALL ENTER(1)
      IA = ISTKGT(8*N, 4)
      IB = IA+2*N
      IC = IB+2*N
      IN = IC+2*N
      CALL DG8EX2(N, X, W, R(IA), R(IB), R(IC), R(IN))
      IF (NERROR(NERR) .EQ. 0) GOTO 10
         CALL ERROFF
C/6S
C        CALL SETERR(30HDGQEX2 - CANNOT OBTAIN X AND W, 30, 2, 1)
C/7S
         CALL SETERR('DGQEX2 - CANNOT OBTAIN X AND W', 30, 2, 1)
C/
   10 CALL LEAVE
      CALL DASYM(N,X)
      CALL DSYM(N,W)
      RETURN
      END
