      SUBROUTINE DGQEXA(N, ALPHA, X, W)
      INTEGER N
      DOUBLE PRECISION ALPHA, X(N), W(N)
      COMMON /CSTAK/ D
      DOUBLE PRECISION D(500)
      INTEGER IA, IB, IC, IN, ISTKGT, NERR, NERROR
      DOUBLE PRECISION R(500)
      EQUIVALENCE (D(1), R(1))
C J. L. BLUE, 15 DEC 77
C CALCULATE GAUSS QUADRATURE RULES ON (0, INFINITY),
C    WITH WEIGHT FUNCTION X**ALPHA * EXP(-X)
C USE DGAUSQ = SACK-DONOVAN PROGRAM, GENERALIZED LAGUERRE POLYNOMIALS.
C/6S
C     IF (N .LT. 1) CALL SETERR(18H DGQEXA - N .LT. 1, 18, 1, 2)
C     IF (ALPHA .LE. (-1.D0)) CALL SETERR(23H DGQEXA - ALPHA .LE. -1,
C    1   23, 2, 2)
C/7S
      IF (N .LT. 1) CALL SETERR(' DGQEXA - N .LT. 1', 18, 1, 2)
      IF (ALPHA .LE. (-1.D0)) CALL SETERR(' DGQEXA - ALPHA .LE. -1',
     1   23, 2, 2)
C/
      CALL ENTER(1)
      IA = ISTKGT(8*N, 4)
      IB = IA+2*N
      IC = IB+2*N
      IN = IC+2*N
      CALL DG8EXA(N, ALPHA, X, W, R(IA), R(IB), R(IC), R(IN))
      IF (NERROR(NERR) .EQ. 0) GOTO 10
         CALL ERROFF
C/6S
C        CALL SETERR(30HDGQEXA - CANNOT OBTAIN X AND W, 30, 3, 1)
C/7S
         CALL SETERR('DGQEXA - CANNOT OBTAIN X AND W', 30, 3, 1)
C/
   10 CALL LEAVE
      RETURN
      END
