      SUBROUTINE DGQXAB(N, ALPHA, BETA, X, W)
      INTEGER N
      DOUBLE PRECISION ALPHA, BETA, X(N), W(N)
      COMMON /CSTAK/ D
      DOUBLE PRECISION D(500)
      INTEGER IA, IB, IC, IN, ISTKGT, NERR, NERROR
      DOUBLE PRECISION R(500)
      EQUIVALENCE (D(1), R(1))
C J. L. BLUE, 15 DEC 77
C CALCULATE GAUSS QUADRATURE RULES ON (-1, 1),
C    WITH WEIGHT FUNCTION (1-X)**ALPHA * (1+X)**BETA
C USE DGAUSQ = SACK-DONOVAN PROGRAM, WITH JACOBI POLYNOMIALS.
C/6S
C     IF (N .LT. 1) CALL SETERR(18H DGQXAB - N .LT. 1, 18, 1, 2)
C     IF (DMIN1(ALPHA, BETA) .LE. (-1.D0)) CALL SETERR(
C    1   31H DGQXAB - ALPHA OR BETA .LE. -1, 31, 2, 2)
C/7S
      IF (N .LT. 1) CALL SETERR(' DGQXAB - N .LT. 1', 18, 1, 2)
      IF (DMIN1(ALPHA, BETA) .LE. (-1.D0)) CALL SETERR(
     1   ' DGQXAB - ALPHA OR BETA .LE. -1', 31, 2, 2)
C/
      CALL ENTER(1)
      IA = ISTKGT(8*N, 4)
      IB = IA+2*N
      IC = IB+2*N
      IN = IC+2*N
      CALL DG8XAB(N, ALPHA, BETA, X, W, R(IA), R(IB), R(IC), R(IN))
      IF (NERROR(NERR) .EQ. 0) GOTO 10
         CALL ERROFF
C/6S
C        CALL SETERR(30HDGQXAB - CANNOT OBTAIN X AND W, 30, 3, 1)
C/7S
         CALL SETERR('DGQXAB - CANNOT OBTAIN X AND W', 30, 3, 1)
C/
   10 CALL LEAVE
      IF (ALPHA .NE. BETA) RETURN
         CALL DASYM(N,X)
         CALL DSYM(N,W)
         RETURN
      END
