      SUBROUTINE DQUAD(F,A,B,EPS,ANS,ERREST)
C
C TO INTEGRATE F(X) FROM A TO B WITH ABSOLUTE ACCURACY EPS,
C SET DEFAULT VALUES OF PARAMETERS AND CALL D1QUAD
C
      DOUBLE PRECISION F,A,B,EPS,ANS,ERREST,HSAMPL
      EXTERNAL F
C
      HSAMPL = 0.125
      NFCALL = 2000
      LYSTAK = 250
      KMAXEX = 8
      KDIVID = 4
      JPRINT = 0
      NUMINT = 3
C
      CALL D1QUAD(F,A,B,EPS,HSAMPL,NFCALL,LYSTAK,KMAXEX,KDIVID,
     X      JPRINT,NUMINT,ANS,ERREST,KWARN)
C
C/6S
C     IF (KWARN .LT. 0 ) CALL SETERR
C    *   (58HDQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN
C    *    ,58,2,2)
C/7S
      IF (KWARN .LT. 0 ) CALL SETERR
     *   ('DQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN'
     *    ,58,2,2)
C/
C
C/6S
C     IF (ERREST  .GT.  EPS) CALL SETERR
C    *   (53HDQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS,
C    *    53,1,1)
C/7S
      IF (ERREST  .GT.  EPS) CALL SETERR
     *   ('DQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS',
     *    53,1,1)
C/
C
C
       RETURN
      END
