      SUBROUTINE DRQUAD(F,A,B,EPSABS,EPSREL,ANS,ERREST)
C
C TO INTEGRATE F(X) FROM A TO B WITH ACCURACY EPS,
C WHERE EPS = EPSABS + EPSREL * ABS(ANS),
C SET DEFAULT VALUES OF PARAMETERS AND CALL D1QUAD.
C IF EPSREL .GT. 0, NEED TO ESTIMATE ANS FIRST.
C
      DOUBLE PRECISION F,A,B,EPSABS,EPSREL,EPS,ANS,ERREST,HSAMPL
      DOUBLE PRECISION EPSA,EPSR,D1MACH
      EXTERNAL F
C
      HSAMPL = 0.125
      NFCALL = 2000
      LYSTAK = 250
      KMAXEX = 8
      KDIVID = 4
      JPRINT = 0
      NUMINT = 3
C
      EPSA = DMAX1(EPSABS,0.D0)
      EPSR = DMAX1(EPSREL,0.D0)
      EPS = EPSABS
      JMAX = 1
      IF (EPSR .GT. 0.D0) EPS = 0.05D0*D1MACH(2)
      IF (EPSR .GT. 0.D0) JMAX = 3
C
      DO 100 J=1,JMAX
         CALL D1QUAD(F,A,B,EPS,HSAMPL,NFCALL,LYSTAK,KMAXEX,KDIVID,
     X         JPRINT,NUMINT,ANS,ERREST,KWARN)
C
C/6S
C     IF (KWARN .LT. 0 ) CALL SETERR
C    *   (59HDRQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN
C    *    ,59,2,2)
C/7S
      IF (KWARN .LT. 0 ) CALL SETERR
     *   ('DRQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN'
     *    ,59,2,2)
C/
C
         IF (KWARN .GT. 0) GO TO 200
         EPS = EPSA + EPSR * DABS(ANS)
         IF (ERREST .LE. EPS) RETURN
         EPS = EPSA + EPSR * DMAX1(0.5D0*DABS(ANS), DABS(ANS)-ERREST)
C
  100 CONTINUE
C
C/6S
C 200 CALL SETERR
C    *   (54HDRQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS,
C    *    54,1,1)
C/7S
  200 CALL SETERR
     *   ('DRQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS',
     *    54,1,1)
C/
C
      RETURN
      END
