      SUBROUTINE GQM11(N,X,W)
C
C  TO COMPUTE THE ABCISSAE (X) AND WEIGHTS (W) FOR AN N POINT
C  GAUSS-LEGENDRE QUADRATURE RULE ON (-1,+1).
C
C  SCRATCH SPACE ALLOCATED - 17*N REAL WORDS.
C
C  ERROR STATES -
C
C    1 - N.LT.1.
C
      REAL X(N),W(N)
C
      COMMON /CSTAK/DS
      DOUBLE PRECISION DS(500)
      REAL WS(1)
      EQUIVALENCE (DS(1),WS(1))
C
C/6S
C     IF (N.LT.1)
C    1   CALL SETERR(15H GQM11 - N.LT.1,15,1,2)
C/7S
      IF (N.LT.1)
     1   CALL SETERR(' GQM11 - N.LT.1',15,1,2)
C/
C
      N2=2*N
C
C ... ALLOCATE SCRATCH SPACE FOR A,B,C AND NU.
C
      IA=ISTKGT(8*N,3)-1
      IB=IA+N2
      IC=IB+N2
      INU=IC+N2
C
C ... COMPUTE A,B,C AND NU FOR CALL TO GAUSQ.
C
      DO 10 I=1,N2
         IDXA=IA+I
         IDXB=IB+I
         IDXC=IC+I
         IDXNU=INU+I
         WS(IDXA)=(FLOAT(I))/(FLOAT(2*I-1))
         WS(IDXB)=0.0E0
         WS(IDXC)=(FLOAT(I-1))/(FLOAT(2*I-1))
 10      WS(IDXNU)=0.0E0
      WS(INU+1)=2.0E0
C
C ... GET X AND W.
C
      CALL GAUSQ(N,WS(IA+1),WS(IB+1),WS(IC+1),WS(INU+1),X,W)
C
      CALL ISTKRL(1)
C
      RETURN
C
      END
