      SUBROUTINE QUAD(F,A,B,EPS,ANS,ERREST)
C
C TO INTEGRATE F(X) FROM A TO B WITH ABSOLUTE ACCURACY EPS,
C SET DEFAULT VALUES OF PARAMETERS AND CALL R1QUAD
C
      REAL F,A,B,EPS,ANS,ERREST,HSAMPL
      EXTERNAL F
C
      HSAMPL = 0.125
      NFCALL = 2000
      LYSTAK = 250
      KMAXEX = 6
      KDIVID = 4
      JPRINT = 0
      NUMINT = 3
C
      CALL R1QUAD(F,A,B,EPS,HSAMPL,NFCALL,LYSTAK,KMAXEX,KDIVID,
     X      JPRINT,NUMINT,ANS,ERREST,KWARN)
C
C/6S
C     IF (KWARN .LT. 0 ) CALL SETERR
C    *   (57HQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN
C    *    ,57,2,2)
C/7S
      IF (KWARN .LT. 0 ) CALL SETERR
     *   ('QUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN'
     *    ,57,2,2)
C/
C
C/6S
C     IF (ERREST  .GT.  EPS) CALL SETERR
C    *   (52HQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS,
C    *    52,1,1)
C/7S
      IF (ERREST  .GT.  EPS) CALL SETERR
     *   ('QUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS',
     *    52,1,1)
C/
C
C
      RETURN
      END
