      SUBROUTINE R1QCHG(IDIV,X,Y,JPATT,NMAX,DROUND,HMIN,NPRINT)
C
C USING RATIOS OF T-TABLE DIFFERENCES STORED IN RL, TRY TO RECOGNIZE
C X**A BEHAVIOR.  FORMULAS ARE EMPIRICAL, NOT EXACT, FOR THE SEQUENCE
C H, H/2, H/3, H/4, H/6, H/8, . . .
C CHANGE OF VARIABLE PARAMETER NEXP IS CHOSEN SUCH THAT THE
C TRANSFORMED INTEGRAL SHOULD BE ABLE TO CONVERGE IN THE THIRD
C COLUMN OF THE T-TABLE.
C
      COMMON /R1QCM3/ XBOT,DELX,R(3),RL(3),NEXP,KEXT,KLAST
      REAL X(5),Y(9),DROUND,XBOT,HMIN,DELX
      DIMENSION IDIV(5)
C
      JOUT = I1MACH(2)
C
      IF (AMIN1(RL(2),RL(3)) .LT. 0.1) RETURN
                      A2 = 2.74*ALOG(RL(2)/1.34)
                      A3 = -1.
      IF (KLAST.EQ.4) A3 = 2.38*ALOG(RL(3)/1.57)
      IF (KLAST.GT.4) A3 = 2.89*ALOG(RL(3)/1.25)
      IF (ABS(A2-A3).GT.0.1 .OR. AMIN1(A2,A3).LT.(-0.99)) RETURN
      NEXP=12./(2.+A2+A3)+0.5
      NEXP = MAX0(1,MIN0(NEXP,NMAX))
      IF (NEXP .LE. 1) RETURN
         IF(NPRINT.GT.0) WRITE(JOUT,1) A2,A3,NEXP
    1    FORMAT(7H ALPHAS,2F6.3,26H CHANGE VARIABLES WITH N =,I4)
         XBOT = X(1)
         DELX = X(2)-XBOT
         Y(1) = 0.D0
         N = 1+3*2**IDIV(1)
         Y(2) = FLOAT(NEXP)*Y(N)
         IDIV(1) = 0
         HMIN = AMAX1(HMIN,ABS(DELX)*DROUND**(1./FLOAT(NEXP)))
         JPATT = 0
         RETURN
      END
