      REAL FUNCTION R1QFUN(F,X)
C
C FUNCTION TO BE INTEGRATED USING R1QDAP AND R1QINT.
C NEXP .GT. 1 IF CHANGE OF VARIABLE HAS BEEN MADE.
C
      REAL F,X,XBOT,DELX,V
      EXTERNAL F
      COMMON /R1QCM3/ XBOT,DELX,R(3),RL(3),NEXP,KEXT,KLAST
C
      IF (NEXP.GT.1) GO TO 10
         R1QFUN = F(X)
         RETURN
C
   10 V = ((X-XBOT)/DELX)**(NEXP-1)
      R1QFUN = FLOAT(NEXP)*V*F(XBOT+V*(X-XBOT))
      RETURN
      END
