      SUBROUTINE R1QUAD(F,A,B,EPS,HS,NFCALL,LYSTAK,KMAXEX,KDIVID,
     X          JPRINT,NUMINT,ANS,ERREST,KWARN)
C
C INTEGRATE F(X) FROM A TO B WITH ABSOLUTE ACCURACY EPS.
C MUST TAKE STEP SIZE AT LEAST AS SMALL AS HS*ABS(B-A).
C USE NO MORE THAN NFCALL SAMPLING POINTS, OR CALLS TO F.
C FOR TEMPORARY STORAGE OF FUNCTION VALUES, ALLOCATE LYSTAK WORDS.
C DO AT MOST KMAXEX EXTRAPOLATIONS.
C DO NOT DIVIDE INTERVAL UNTIL AFTER KDIVID EXTRAPOLATIONS.
C JPRINT = 0 FOR NO PRINTING, 1 FOR SOME, 2 FOR LOTS.
C TO START, DIVIDE (A,B) INTO NUMINT EQUAL INTERVALS.
C RETURN VALUE AND ITS ESTIMATED ERROR IN ANS AND ERREST.
C RETURN KWARN AS WARNING FLAG.
C
C FUNCTION ISTKQU RETURNS AMOUNT OF SPACE LEFT IN STACK.
C FUNCTION ISTKGT ALLOCATES SPACE IN STACK AND GIVES POINTER TO IT.
C SUBROUTINE LEAVE DE-ALLOCATES SPACE IN STACK.
C THE DEFAULT STACK LENGTH IS 500 DOUBLE PRECISION WORDS.
C IF A LARGER STACK IS NECESSARY, THE PROGRAM CALLING R1QUAD OR QUAD
C SHOULD INITIALIZE THE STACK  USING SUBROUTINE ISTKIN.
C
      REAL F,A,B,EPS,HS,ANS,ERREST
      EXTERNAL F
      COMMON /R1QCM1/ DLARGE,DSMALL,DROUND,HSAMPL,HSMALL,ESMALL,
     X   NPRINT,NUM,MAXY,MAXINT,MAXF,KMIN,KMAX,KDIV,NMAX
      REAL DLARGE,DSMALL,DROUND,HSAMPL,HSMALL,ESMALL
C
      COMMON/CSTAK/DS
      DOUBLE PRECISION DS(500)
      REAL RS(1000)
      INTEGER IS(1000)
      EQUIVALENCE (DS(1),IS(1)),(DS(1),RS(1))
C
C        MACHINE- AND PRECISION-DEPENDENT NUMBERS
C
      HSMALL = 50.*R1MACH(4)
      DROUND = 50.*R1MACH(4)
      DSMALL = 10.*R1MACH(1)
      DLARGE = 0.1*R1MACH(2)
C
C         PARAMETERS
C
      NPRINT = JPRINT
      NUM = MAX0(1,NUMINT)
      KMIN = 2
      KMAX = MAX0(4,MIN0(12,KMAXEX))
      KMAX = 2*(KMAX/2)
      KDIV = MIN0(MAX0(KDIVID,4),KMAX)
      KDIV = 2*(KDIV/2)
      HSAMPL = AMIN1(HS,1.E0)
      ESMALL = EPS*1.E-3
      NMAX = 1.-ALOG(DROUND)/ALOG(6.E0)
      NMAX = MIN0(25,NMAX)
C
C        ALLOCATE SCRATCH SPACE
C
      MAXY = MAX0(NUM+7,LYSTAK)
      MAXF = MAX0(4*NUM+1,NFCALL)
      MAXINT=1.-ALOG(HSMALL)/ALOG(2.E0)
      MAXINT = MAX0(MAXINT,NUM+2)
      CALL ENTER(0)
      NSHORT = ISTKQU(2)-2*MAXINT
      IF (NSHORT .LT. 0) GO TO 120
      IIDIV = ISTKGT(2*MAXINT,2)
      II = IIDIV+MAXINT
      NSHORT = ISTKQU(3)-(MAXINT+1+MAXY)
      IF (NSHORT .LT. 0) GO TO 120
      IX = ISTKGT(MAXINT+1+MAXY,3)
      IY = IX+MAXINT+1
C
      RS(IX)=A
      DO 110 J=1,NUM
         JJ=IX+J
  110    RS(JJ)=A+FLOAT(J)*(B-A)/FLOAT(NUM)
      RS(JJ)=B
C
      CALL R1QDAP(F,A,B,EPS,RS(IY),RS(IX),IS(II),IS(IIDIV),
     X    ANS,ERREST,KWARN)
C
      CALL LEAVE
      RETURN
C
  120 KWARN = NSHORT
      ANS = 0.
      ERREST = DLARGE
      CALL LEAVE
      RETURN
      END
