      SUBROUTINE RQUAD(F,A,B,EPSABS,EPSREL,ANS,ERREST)
C
C TO INTEGRATE F(X) FROM A TO B WITH ACCURACY EPS,
C WHERE EPS = EPSABS + EPSREL * ABS(ANS),
C SET DEFAULT VALUES OF PARAMETERS AND CALL R1QUAD.
C IF EPSREL .GT. 0, NEED TO ESTIMATE ANS FIRST.
C
      REAL F,A,B,EPSABS,EPSREL,EPS,ANS,ERREST,HSAMPL
      EXTERNAL F
C
      HSAMPL = 0.125
      NFCALL = 2000
      LYSTAK = 250
      KMAXEX = 6
      KDIVID = 4
      JPRINT = 0
      NUMINT = 3
C
      EPSA = AMAX1(EPSABS,0.)
      EPSR = AMAX1(EPSREL,0.)
      EPS = EPSABS
      JMAX = 1
      IF (EPSR .GT. 0.) EPS = 0.05*R1MACH(2)
      IF (EPSR .GT. 0.) JMAX = 3
C
      DO 100 J=1,JMAX
         CALL R1QUAD(F,A,B,EPS,HSAMPL,NFCALL,LYSTAK,KMAXEX,KDIVID,
     X         JPRINT,NUMINT,ANS,ERREST,KWARN)
C
C/6S
C     IF (KWARN .LT. 0 ) CALL SETERR
C    *   (58HRQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN
C    *    ,58,2,2)
C/7S
      IF (KWARN .LT. 0 ) CALL SETERR
     *   ('RQUAD - THE DYNAMIC STORAGE STACK IS FULL, USE PORT ISTKIN'
     *    ,58,2,2)
C/
C
         IF (KWARN .GT. 0) GO TO 200
         EPS = EPSA + EPSR * ABS(ANS)
         IF (ERREST .LE. EPS) RETURN
         EPS = EPSA + EPSR * AMAX1(0.5E0*ABS(ANS), ABS(ANS)-ERREST)
C
  100 CONTINUE
C
C/6S
C 200 CALL SETERR
C    *   (53HRQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS,
C    *    53,1,1)
C/7S
  200 CALL SETERR
     *   ('RQUAD - THE ERROR ESTIMATE,ERREST, IS LARGER THAN EPS',
     *    53,1,1)
C/
C
      RETURN
      END
