        SUBROUTINE CSPMIN(N,IC,IWORK,I,AROW,JROW,NUM,INDEX,A)
C
C THIS SUBROUTINE INSERTS IN THE VECTOR A THE ELEMENTS OF
C AROW ACCORDING TO THE SCHEME RECORDED IN IWORK AND
C DETERMINED BY SPMSF
C
C INPUT PARAMETERS
C N       NUMBER OF ROWS IN ORIGINAL MATRIX
C IC      INTEGER VECTOR OF LENGTH N CONTAINING INVERSE OF
C         COLUMN PERMUTATIONS
C IWORK   INTEGER VECTOR OUTPUT FROM SPMSF
C I       WHICH ROW NOW INTSERTING
C AROW    COMPLEX VECTOR LENGTH NUM OF NONZERO ELEMENTS IN ROW I
C         OF ORIGINAL MATRIX
C JROW    INTEGER VECTOR OF LENGTH NUM OF COLUMN INDICES IN ROW I
C         OF ORIGINAL VECTOR
C NUM     NUMBER OF NONZERO ELEMENTS IN ROW I NOW INSERTING INTO A
C INDEX   IF INDEX IS 1 THE WHOLE ARRAY A IS ZEROED OUT BEFOREHAND
C         THIS ALLOWS ONE TO CALL THE SUBROUTINE SEVERAL TIMES
C         FOR 1 ROW AND TO ADD THE NEW INFORMATION
C OUTPUT PARAMETER
C A       VECTOR FOR INSERT INTO DSPMNF WITH THE INFORMATION
C         FROM AROW INSERTED
C ERROR STATES
C 1 N.LT.1
C 2 I NOT IN 1 THOUGH N
C 3 NUM.LT.1
C 4 INDEX IN JROW VECTOR FOR ROW I WAS NOT KNOWN TO SPMSF
C
        INTEGER N,I,NUM
        INTEGER IC(N),JROW(N),INDEX,IWORK(1)
        COMPLEX A(N),AROW(NUM)
        INTEGER NTOT,K,IR,JS,JE,KK,MM,M,MIN,IDISP
C/6S
C       IF (N.LT.1) CALL SETERR(13HCSPMIN-N.LT.1,13,1,2)
C       IF (NUM.LT.1) CALL SETERR(15HCSPMIN-NUM.LT.1,15,3,2)
C       IF(I.LT.1.OR.I.GT.N) CALL SETERR(21HCSPMIN-I OUT OF RANGE,
C    1      21,2,2)
C/7S
        IF (N.LT.1) CALL SETERR('CSPMIN-N.LT.1',13,1,2)
        IF (NUM.LT.1) CALL SETERR('CSPMIN-NUM.LT.1',15,3,2)
        IF(I.LT.1.OR.I.GT.N) CALL SETERR('CSPMIN-I OUT OF RANGE',
     1      21,2,2)
C/
         IF (INDEX.NE.1) GO TO 10
            NTOT=IWORK(N+1)-1
            DO 1 K=1,NTOT
                 A(K)=(0.0E0,0.0E0)
 1          CONTINUE
 10      IR=I
         IDISP=2*N+1
         JS=IWORK(IR)+IDISP
         JE= IWORK(IR+1)+IDISP-1
         KK=JS
         DO 50 K=1,NUM
            MM=JROW(K)
            M=IC(MM)
            IF (IWORK(KK)-M)30,40,20
 20         IF (KK.EQ.JS) GO TO 80
            KK=KK-1
            IF (IWORK(KK)-M)80,40,20
 30         IF (KK.EQ.JE) GO TO 80
            KK=KK+1
            IF (IWORK(KK)-M)30,40,80
 40         MIN=KK-IDISP
            A(MIN)=A(MIN)+AROW(K)
 50     CONTINUE
        RETURN
C/6S
C80     CALL SETERR(20HCSPMIN-UNKNOWN INDEX,20,4,2)
C/7S
 80     CALL SETERR('CSPMIN-UNKNOWN INDEX',20,4,2)
C/
        RETURN
        END
