      SUBROUTINE CSPMNF(N, IWORK, A,  EPS, GROWTH)
      INTEGER N, IWORK(1), JLU
      REAL   EPS, GROWTH
      COMPLEX A(1)
      COMPLEX DD(500)
      COMMON /CSTAK/ DD
      INTEGER ID, NERR, ISTKGT, NERROR, ISP(1)
      EQUIVALENCE (DD(1), ISP(1))
C NUMERICAL FACTORIZATION
C INPUT PARAMETERS
C N    ORDER OF MATRIX
C IWORK INTEGER VECTOR OF SYMBOLIC FACTORIZATION COMPUTED BY
C        SPMSF
C EPS     LARGEST NONACCEPTABLE PIVOT FOR SINGULARITY TEST
C A       VECTOR COMPUTED BY  SPMIN ACCORDING TO INSTRUCTIONS
C         GIVEN IN  SPMSF
C OUTPUT PARAMETERS
C A     NUMERICAL FACTORIZATION OF MATRIX
C GROWTH NUMERICAL ELEMENT GROWTH. IF THIS MUCH .GT. 1, THEN THE
C        COMPUTED DECOMPOSITION MAY BE THE DECOMPOSITION OF A MATRIX
C        THAT IS NOT VERY CLOSE TO THE ORIGINAL MATRIX.
C STORAGE ALLOCATED -N COMPLEX LOCATION WHICH
C       ARE RETURNED
C ERROR STATES
C 1   N.LT.1     FATAL
C 10+K SINGULAR MATRIX OF RANK K   RECOVERABLE
C/6S
C     IF (N .LT. 1) CALL SETERR(13HCSPMNF-N.LT.1, 13, 1, 2)
C/7S
      IF (N .LT. 1) CALL SETERR('CSPMNF-N.LT.1', 13, 1, 2)
C/
      CALL ENTER(1)
      ID = ISTKGT(N, 5)
       JLU=2*N+2
       CALL CS4MNF(N,IWORK,IWORK(N+2),IWORK(JLU),A,DD(ID),GROWTH,EPS)
C/6S
C     IF (NERROR(NERR) .NE. 0) CALL N5ERR(22HCSPMNF-SINGULAR MATRIX, 22,
C    1   NERR, 1)
C/7S
      IF (NERROR(NERR) .NE. 0) CALL N5ERR('CSPMNF-SINGULAR MATRIX', 22,
     1   NERR, 1)
C/
      CALL LEAVE
      RETURN
      END
