      SUBROUTINE SPFSL(N, MRP, MCP, IWORK, UL, B, IB, NB)
      INTEGER N, IB, NB
      INTEGER MRP(N), MCP(N), IWORK(1)
      REAL UL(1), B(IB, NB)
      REAL D(1000)
      COMMON /CSTAK/ D
      INTEGER JLU, ISTKGT, ITMP
C FORWARD SOLVE FOR SPARSE MATRICES
C INPUT PARAMETERS
C N     NUMBER OF EQUATIONS
C MRP   INTEGER VECTOR OF ROW PERMUTATIONS
C MCP   INTEGER VECTOR,LENGTHN OR COLUMN PERMUTATIONS
C IWORK INTEGER VECTOR COMPUTED BY  SPFLU
C UL    REAL ARRAY COMPUTED BY  SPFLU
C IU    INTEGER VECTOR OF LENGTH N POINTING TO U IN LU
C       DECOMPOSITION,COMPUTED BY SPFLU OR SPFCE
C B     MATRIX OF RIGHT HAND SIDES
C IB    ROW DIMENSION OF B MATRIX
C NB    NUMBER OF RIGHT HAND SIDES
C OUTPUT PARAMETERS
C B     THE SOLUTION MATRIX
C STORAGE SPACE ALLOCATED AND DEALLOCATED -N REAL LOCATIONS
C ERROR CONDITIONS
C 1 N.LT.1    FATAL
C 2 IB.LT.N   FATAL
C 3 NB.LT.1   FATAL
C/6S
C     IF (N .LT. 1) CALL SETERR(13H SPFSL-N.LT.1, 13, 1, 2)
C     IF (IB .LT. N) CALL SETERR(14H SPFSL-IB.LT.N, 14, 2, 2)
C     IF (NB .LT. 1) CALL SETERR(14H SPFSL-NB.LT.1, 14, 3, 2)
C/7S
      IF (N .LT. 1) CALL SETERR(' SPFSL-N.LT.1', 13, 1, 2)
      IF (IB .LT. N) CALL SETERR(' SPFSL-IB.LT.N', 14, 2, 2)
      IF (NB .LT. 1) CALL SETERR(' SPFSL-NB.LT.1', 14, 3, 2)
C/
      CALL ENTER(1)
      ITMP = ISTKGT(N, 3)
      JLU = 2*N+2
      CALL S4FSL(N, MRP, MCP, IWORK, IWORK(JLU), UL, IWORK(N+2), B, IB
     1   , NB, D(ITMP))
      CALL LEAVE
      RETURN
      END
