      SUBROUTINE SPMOR(N, IA, JA, C, IC)
C  THIS IS LINDA KAUFMANS SPARSE MATRIX PACKAGE
C  ROUTINES USED BY ALL THE SPARSE.S SPARSE.D AND SPARSE.C
C  PACKAGES
C
C  DECEMBER 9, 1982 (SLIGHT REVISION)
C
      INTEGER N
      INTEGER IA(1), JA(1), C(N), IC(N)
      EXTERNAL I4YX
      DOUBLE PRECISION DD(500)
      COMMON /CSTAK/ DD
      INTEGER IV, LV, FLAG, ISTKGT, ISTKQU, MAX
      INTEGER ISP(1000), NSP
      EQUIVALENCE (DD(1), ISP(1))
C MNEUMONIC -UNSYMMETRIC ORDER SCHEME
C THIS SUBROUTINE USES THE MINIMUM DEGREE ORDERING
C SCHEME TO REORDER A MATRIX
C INPUT PARAMETERS
C N      ORDER OF THE MATRIX
C IA     INTEGER VECTOR,LENGTH N+1,WHICH POINTS TO
C        TO BEGININNING OF ITH ROW IN JA ARRAY
C JA     THE COLUMN INDICES OF THE NONZERO ELEMENTS IN THE
C        SPARSE MATRIX
C OUTPUT PARAMETERS
C C      INTEGER VECTOR OF LENGTH N OF REORDERED COLUMNS(AND
C        ROWS)
C IC     INTEGER VECTOR OF LENGTH NOF INVERTED ORDER
C        I.E. C(IC(I))=I
C ERROR STATES
C 1      N.LT.1     FATAL
C 2      STORAGE EXCEEDED IMMEDIATELY   FATAL
C N+K    KTH ROW OF MATRIX IS NULL
C 2N+K   STORAGE EXCEED AT KTH ROW
C MINIMUM STORAGE TAKEN FROM STACK-2N+M,WHERE
C M IS THE NUMBER OF NONZEROS IN SPARSE MATRIX
      CALL ENTER(1)
C/6S
C     IF (N .LT. 1) CALL SETERR(13H SPMOR-N.LT.1, 13, 1, 2)
C/7S
      IF (N .LT. 1) CALL SETERR(' SPMOR-N.LT.1', 13, 1, 2)
C/
      NSP = ISTKQU(2)
      IV = ISTKGT(NSP, 2)
      MAX=(NSP-N)/2-1
      LV=IV+MAX
      IHEAD=LV+MAX
      FLAG=0
      CALL S4MDM(N,I4YX,MAX,ISP(IV),ISP(LV),ISP(IHEAD),C,IC,
     1 ISP(IV),FLAG,IA,JA,1)
      IF (FLAG .EQ. 0) GOTO 1
C/6S
C     IF (FLAG.GT.2*N+10)
C    2   CALL SETERR(27H SPMOR-INSUFFICIENT STORAGE,27,FLAG,1)
C     IF (FLAG.LE.N+10)
C    1   CALL SETERR(15H SPMOR-NULL ROW,15,FLAG,1)
C     IF (FLAG.GT.N+10.AND.FLAG.LE.10+2*N)
C    1   CALL SETERR(29H SPMOR-INCORRECT COLUMN INDEX,29,FLAG,1)
C/7S
      IF (FLAG.GT.2*N+10)
     2   CALL SETERR(' SPMOR-INSUFFICIENT STORAGE',27,FLAG,1)
      IF (FLAG.LE.N+10)
     1   CALL SETERR(' SPMOR-NULL ROW',15,FLAG,1)
      IF (FLAG.GT.N+10.AND.FLAG.LE.10+2*N)
     1   CALL SETERR(' SPMOR-INCORRECT COLUMN INDEX',29,FLAG,1)
C/
   1  CALL LEAVE
      RETURN
      END
