#Makefile to compile nonsmooth models from the Luksan and Vlcek
#Created by Luis Miguel Rios lmrios@gmail.com
#define the fortran compiler
#FC=gfortran
FC=g77

all: problem2_1 problem2_2 problem2_3 problem2_4 \
     problem2_5 problem2_6 problem2_7 problem2_8 \
     problem2_9 problem2_10 problem2_11 problem2_12 \
     problem2_13 problem2_14 problem2_15 problem2_16 \
     problem2_17 problem2_18 problem2_19 problem2_20 \
     problem2_21 problem2_22 problem2_23 problem2_24 \
     problem2_25 \
     problem3_1 problem3_2 problem3_3 problem3_4 \
     problem3_5 problem3_6 problem3_7 problem3_8 \
     problem3_9 problem3_10 problem3_11 problem3_12 \
     problem3_13 problem3_15 problem3_16 \
     problem3_17 problem3_18 problem3_19 problem3_20 \
     problem3_21 problem3_22 problem3_23 problem3_24 \
     problem3_25
     
NONSMOOTH_FILES = test06.o test19.o

problem2_1 = problem2_1.o
problem2_1: $(problem2_1) $(NONSMOOTH_FILES)
	$(FC) -o problem2_1 $(problem2_1) $(NONSMOOTH_FILES)

problem2_2 = problem2_2.o
problem2_2: $(problem2_2) $(NONSMOOTH_FILES)
	$(FC) -o problem2_2 $(problem2_2) $(NONSMOOTH_FILES)

problem2_3 = problem2_3.o
problem2_3: $(problem2_3) $(NONSMOOTH_FILES)
	$(FC) -o problem2_3 $(problem2_3) $(NONSMOOTH_FILES)

problem2_4 = problem2_4.o
problem2_4: $(problem2_4) $(NONSMOOTH_FILES)
	$(FC) -o problem2_4 $(problem2_4) $(NONSMOOTH_FILES)

problem2_5 = problem2_5.o
problem2_5: $(problem2_5) $(NONSMOOTH_FILES)
	$(FC) -o problem2_5 $(problem2_5) $(NONSMOOTH_FILES)

problem2_6 = problem2_6.o
problem2_6: $(problem2_6) $(NONSMOOTH_FILES)
	$(FC) -o problem2_6 $(problem2_6) $(NONSMOOTH_FILES)

problem2_7 = problem2_7.o
problem2_7: $(problem2_7) $(NONSMOOTH_FILES)
	$(FC) -o problem2_7 $(problem2_7) $(NONSMOOTH_FILES)

problem2_8 = problem2_8.o
problem2_8: $(problem2_8) $(NONSMOOTH_FILES)
	$(FC) -o problem2_8 $(problem2_8) $(NONSMOOTH_FILES)

problem2_9 = problem2_9.o
problem2_9: $(problem2_9) $(NONSMOOTH_FILES)
	$(FC) -o problem2_9 $(problem2_9) $(NONSMOOTH_FILES)

problem2_10 = problem2_10.o
problem2_10: $(problem2_10) $(NONSMOOTH_FILES)
	$(FC) -o problem2_10 $(problem2_10) $(NONSMOOTH_FILES)

problem2_11 = problem2_11.o
problem2_11: $(problem2_11) $(NONSMOOTH_FILES)
	$(FC) -o problem2_11 $(problem2_11) $(NONSMOOTH_FILES)

problem2_12 = problem2_12.o
problem2_12: $(problem2_12) $(NONSMOOTH_FILES)
	$(FC) -o problem2_12 $(problem2_12) $(NONSMOOTH_FILES)

problem2_13 = problem2_13.o
problem2_13: $(problem2_13) $(NONSMOOTH_FILES)
	$(FC) -o problem2_13 $(problem2_13) $(NONSMOOTH_FILES)

problem2_14 = problem2_14.o
problem2_14: $(problem2_14) $(NONSMOOTH_FILES)
	$(FC) -o problem2_14 $(problem2_14) $(NONSMOOTH_FILES)

problem2_15 = problem2_15.o
problem2_15: $(problem2_15) $(NONSMOOTH_FILES)
	$(FC) -o problem2_15 $(problem2_15) $(NONSMOOTH_FILES)

problem2_16 = problem2_16.o
problem2_16: $(problem2_16) $(NONSMOOTH_FILES)
	$(FC) -o problem2_16 $(problem2_16) $(NONSMOOTH_FILES)

problem2_17 = problem2_17.o
problem2_17: $(problem2_17) $(NONSMOOTH_FILES)
	$(FC) -o problem2_17 $(problem2_17) $(NONSMOOTH_FILES)

problem2_18 = problem2_18.o
problem2_18: $(problem2_18) $(NONSMOOTH_FILES)
	$(FC) -o problem2_18 $(problem2_18) $(NONSMOOTH_FILES)

problem2_19 = problem2_19.o
problem2_19: $(problem2_19) $(NONSMOOTH_FILES)
	$(FC) -o problem2_19 $(problem2_19) $(NONSMOOTH_FILES)

problem2_20 = problem2_20.o
problem2_20: $(problem2_20) $(NONSMOOTH_FILES)
	$(FC) -o problem2_20 $(problem2_20) $(NONSMOOTH_FILES)

problem2_21 = problem2_21.o
problem2_21: $(problem2_21) $(NONSMOOTH_FILES)
	$(FC) -o problem2_21 $(problem2_21) $(NONSMOOTH_FILES)

problem2_22 = problem2_22.o
problem2_22: $(problem2_22) $(NONSMOOTH_FILES)
	$(FC) -o problem2_22 $(problem2_22) $(NONSMOOTH_FILES)

problem2_23 = problem2_23.o
problem2_23: $(problem2_23) $(NONSMOOTH_FILES)
	$(FC) -o problem2_23 $(problem2_23) $(NONSMOOTH_FILES)

problem2_24 = problem2_24.o
problem2_24: $(problem2_24) $(NONSMOOTH_FILES)
	$(FC) -o problem2_24 $(problem2_24) $(NONSMOOTH_FILES)

problem2_25 = problem2_25.o
problem2_25: $(problem2_25) $(NONSMOOTH_FILES)
	$(FC) -o problem2_25 $(problem2_25) $(NONSMOOTH_FILES)

problem3_1 = problem3_1.o
problem3_1: $(problem3_1) $(NONSMOOTH_FILES)
	$(FC) -o problem3_1 $(problem3_1) $(NONSMOOTH_FILES)

problem3_2 = problem3_2.o
problem3_2: $(problem3_2) $(NONSMOOTH_FILES)
	$(FC) -o problem3_2 $(problem3_2) $(NONSMOOTH_FILES)

problem3_3 = problem3_3.o
problem3_3: $(problem3_3) $(NONSMOOTH_FILES)
	$(FC) -o problem3_3 $(problem3_3) $(NONSMOOTH_FILES)

problem3_4 = problem3_4.o
problem3_4: $(problem3_4) $(NONSMOOTH_FILES)
	$(FC) -o problem3_4 $(problem3_4) $(NONSMOOTH_FILES)

problem3_5 = problem3_5.o
problem3_5: $(problem3_5) $(NONSMOOTH_FILES)
	$(FC) -o problem3_5 $(problem3_5) $(NONSMOOTH_FILES)

problem3_6 = problem3_6.o
problem3_6: $(problem3_6) $(NONSMOOTH_FILES)
	$(FC) -o problem3_6 $(problem3_6) $(NONSMOOTH_FILES)

problem3_7 = problem3_7.o
problem3_7: $(problem3_7) $(NONSMOOTH_FILES)
	$(FC) -o problem3_7 $(problem3_7) $(NONSMOOTH_FILES)

problem3_8 = problem3_8.o
problem3_8: $(problem3_8) $(NONSMOOTH_FILES)
	$(FC) -o problem3_8 $(problem3_8) $(NONSMOOTH_FILES)

problem3_9 = problem3_9.o
problem3_9: $(problem3_9) $(NONSMOOTH_FILES)
	$(FC) -o problem3_9 $(problem3_9) $(NONSMOOTH_FILES)

problem3_10 = problem3_10.o
problem3_10: $(problem3_10) $(NONSMOOTH_FILES)
	$(FC) -o problem3_10 $(problem3_10) $(NONSMOOTH_FILES)

problem3_11 = problem3_11.o
problem3_11: $(problem3_11) $(NONSMOOTH_FILES)
	$(FC) -o problem3_11 $(problem3_11) $(NONSMOOTH_FILES)

problem3_12 = problem3_12.o
problem3_12: $(problem3_12) $(NONSMOOTH_FILES)
	$(FC) -o problem3_12 $(problem3_12) $(NONSMOOTH_FILES)

problem3_13 = problem3_13.o
problem3_13: $(problem3_13) $(NONSMOOTH_FILES)
	$(FC) -o problem3_13 $(problem3_13) $(NONSMOOTH_FILES)

problem3_14 = problem3_14.o
problem3_14: $(problem3_14) $(NONSMOOTH_FILES)
	$(FC) -o problem3_14 $(problem3_14) $(NONSMOOTH_FILES)

problem3_15 = problem3_15.o
problem3_15: $(problem3_15) $(NONSMOOTH_FILES)
	$(FC) -o problem3_15 $(problem3_15) $(NONSMOOTH_FILES)

problem3_16 = problem3_16.o
problem3_16: $(problem3_16) $(NONSMOOTH_FILES)
	$(FC) -o problem3_16 $(problem3_16) $(NONSMOOTH_FILES)

problem3_17 = problem3_17.o
problem3_17: $(problem3_17) $(NONSMOOTH_FILES)
	$(FC) -o problem3_17 $(problem3_17) $(NONSMOOTH_FILES)

problem3_18 = problem3_18.o
problem3_18: $(problem3_18) $(NONSMOOTH_FILES)
	$(FC) -o problem3_18 $(problem3_18) $(NONSMOOTH_FILES)

problem3_19 = problem3_19.o
problem3_19: $(problem3_19) $(NONSMOOTH_FILES)
	$(FC) -o problem3_19 $(problem3_19) $(NONSMOOTH_FILES)

problem3_20 = problem3_20.o
problem3_20: $(problem3_20) $(NONSMOOTH_FILES)
	$(FC) -o problem3_20 $(problem3_20) $(NONSMOOTH_FILES)

problem3_21 = problem3_21.o
problem3_21: $(problem3_21) $(NONSMOOTH_FILES)
	$(FC) -o problem3_21 $(problem3_21) $(NONSMOOTH_FILES)

problem3_22 = problem3_22.o
problem3_22: $(problem3_22) $(NONSMOOTH_FILES)
	$(FC) -o problem3_22 $(problem3_22) $(NONSMOOTH_FILES)

problem3_23 = problem3_23.o
problem3_23: $(problem3_23) $(NONSMOOTH_FILES)
	$(FC) -o problem3_23 $(problem3_23) $(NONSMOOTH_FILES)

problem3_24 = problem3_24.o
problem3_24: $(problem3_24) $(NONSMOOTH_FILES)
	$(FC) -o problem3_24 $(problem3_24) $(NONSMOOTH_FILES)

problem3_25 = problem3_25.o
problem3_25: $(problem3_25) $(NONSMOOTH_FILES)
	$(FC) -o problem3_25 $(problem3_25) $(NONSMOOTH_FILES)
			
.f.o:
	$(FC) -g -c $*.f

test06.o: test06.f
	${FC} -g  -c test06.f
test19.o: test19.f
	${FC} -g  -c test19.f

clean:
	rm -f *.o