      DOUBLE PRECISION FUNCTION D3POLY(NN,QR,QI,MS,MP,ARE,MRE)
C BOUNDS THE ERROR IN EVALUATING THE POLYNOMIAL BY THE HORNER
C RECURRENCE.
C QR,QI - THE PARTIAL SUMS
C MS    -MODULUS OF THE POINT
C MP    -MODULUS OF POLYNOMIAL VALUE
C ARE, MRE -ERROR BOUNDS ON COMPLEX ADDITION AND MULTIPLICATION
      DOUBLE PRECISION QR(1),QI(1),MS,MP,ARE,MRE,E,CD1MOD
      E = CD1MOD(QR(1),QI(1))*MRE/(ARE+MRE)
      DO 10 I = 1,NN
          E = E*MS+CD1MOD(QR(I),QI(I))
   10 CONTINUE
      D3POLY = E*(ARE+MRE)-MP*MRE
      RETURN
      END
