      DOUBLE PRECISION FUNCTION DZ1DEL(DX2, XP, P2, G2, PMIN,
     1   F2NORM, F2LAST, F2BEST)
      DOUBLE PRECISION DX2, XP, P2, G2, PMIN, F2NORM
      DOUBLE PRECISION F2LAST, F2BEST
      DOUBLE PRECISION XINCR, RATE
      DATA XINCR/1.5D0/
      DATA RATE/0.7D0/
C GET NEW GUESS AT REASONABLE STEP LENGTH
C INPUTS
C DX2 = PREVIOUS STEP LENGTH
C XP = FRACTION OF NEWTON STEP USED IN PREVIOUS STEP
C P2 = NEW NEWTON STEP LENGTH
C G2 = NEW STEEPEST-DESCENT STEP LENGTH
C PMIN = MINIMUM ALLOWABLE XP
C F2NORM = CURRENT 2-NORM OF FUNCTION
C F2LAST = PREVIOUS 2-NORM
C F2BEST = BEST-EVER 2-NORM
C OUTPUT
C NEW STEP LENGTH DZ1DEL
      IF (XP .LE. 0.0D0) GOTO 7
         IF (XP .LT. 1.0D0 .OR. F2NORM .GE. F2LAST) GOTO 1
            DZ1DEL = DX2*DMIN1(XINCR, (XINCR-1.0D0)*(F2NORM/F2LAST-
     1         1.0D0)/(RATE-1.0D0)+1.0D0)
C LAST STEP HAD SOME NEWTON
C SUCCESSFUL FULL NEWTON STEP
            GOTO  6
   1        IF (F2NORM .LT. F2LAST) GOTO 2
               DZ1DEL = DMAX1(0.25D0, F2BEST/F2NORM)*DX2
               IF (F2NORM .GT. F2LAST*(RATE*XP+1.0D0)) DZ1DEL = DMIN1(
     1            DZ1DEL, RATE*DX2)
               GOTO  5
   2           DZ1DEL = DX2*DMIN1(XINCR, (XINCR-1.0D0)*(F2NORM/F2LAST-
     1            1.0D0)/(RATE-1.0D0)+1.0D0)
               IF (F2NORM .LE. F2BEST) GOTO 3
                  DZ1DEL = DMIN1(DZ1DEL, DX2)
                  GOTO  4
   3              DZ1DEL = DMAX1(DZ1DEL, DX2)
   4           CONTINUE
   5     CONTINUE
   6     CONTINUE
         GOTO  8
   7     DZ1DEL = DX2*DMIN1(XINCR, (XINCR-1.0D0)*(F2NORM/F2LAST-1.0D0)/(
     1      RATE-1.0D0)+1.0D0)
C LAST WAS STEEPEST-DESCENT
         IF (F2NORM .LT. RATE*F2LAST .AND. PMIN*P2 .LT. DZ1DEL .AND.
     1      DZ1DEL .LT. 0.1D0*P2 .AND. G2 .GE. 0.25D0*DX2) DZ1DEL =
     2      DMIN1(G2, DZ1DEL)
   8  IF (DZ1DEL .LE. 0.0D0) DZ1DEL = G2
      RETURN
      END
