      DOUBLE PRECISION FUNCTION DZ1DOT(N, X, X2, Y, Y2)
      INTEGER N
      DOUBLE PRECISION X(N), X2, Y(N), Y2
      INTEGER J
C FIND DOT PRODUCT OF UNIT VECTORS IN X AND Y DIRECTIONS
      DZ1DOT = 0.0D0
      DO  1 J = 1, N
         DZ1DOT = DZ1DOT+(X(J)/X2)*(Y(J)/Y2)
   1     CONTINUE
      RETURN
      END
