      REAL FUNCTION Z1DEL(DX2, XP, P2, G2, PMIN, F2NORM, F2LAST,
     1   F2BEST)
      REAL DX2, XP, P2, G2, PMIN, F2NORM
      REAL F2LAST, F2BEST
      REAL XINCR, RATE, AMIN1, AMAX1
      DATA XINCR/1.5E0/
      DATA RATE/0.7E0/
C GET NEW GUESS AT REASONABLE STEP LENGTH
C INPUTS
C DX2 = PREVIOUS STEP LENGTH
C XP = FRACTION OF NEWTON STEP USED IN PREVIOUS STEP
C P2 = NEW NEWTON STEP LENGTH
C G2 = NEW STEEPEST-DESCENT STEP LENGTH
C PMIN = MINIMUM ALLOWABLE XP
C F2NORM = CURRENT 2-NORM OF FUNCTION
C F2LAST = PREVIOUS 2-NORM
C F2BEST = BEST-EVER 2-NORM
C OUTPUT
C NEW STEP LENGTH Z1DEL
      IF (XP .LE. 0.0E0) GOTO 7
         IF (XP .LT. 1.0E0 .OR. F2NORM .GE. F2LAST) GOTO 1
            Z1DEL = DX2*AMIN1(XINCR, (XINCR-1.0E0)*(F2NORM/F2LAST-1.0E0)
     1         /(RATE-1.0E0)+1.0E0)
C LAST STEP HAD SOME NEWTON
C SUCCESSFUL FULL NEWTON STEP
            GOTO  6
   1        IF (F2NORM .LT. F2LAST) GOTO 2
               Z1DEL = AMAX1(0.25E0, F2BEST/F2NORM)*DX2
               IF (F2NORM .GT. F2LAST*(RATE*XP+1.0E0)) Z1DEL = AMIN1(
     1            Z1DEL, RATE*DX2)
               GOTO  5
   2           Z1DEL = DX2*AMIN1(XINCR, (XINCR-1.0E0)*(F2NORM/F2LAST-
     1            1.0E0)/(RATE-1.0E0)+1.0E0)
               IF (F2NORM .LE. F2BEST) GOTO 3
                  Z1DEL = AMIN1(Z1DEL, DX2)
                  GOTO  4
   3              Z1DEL = AMAX1(Z1DEL, DX2)
   4           CONTINUE
   5     CONTINUE
   6     CONTINUE
         GOTO  8
   7     Z1DEL = DX2*AMIN1(XINCR, (XINCR-1.0E0)*(F2NORM/F2LAST-1.0E0)/(
     1      RATE-1.0E0)+1.0E0)
C LAST WAS STEEPEST-DESCENT
         IF (F2NORM .LT. RATE*F2LAST .AND. PMIN*P2 .LT. Z1DEL .AND.
     1      Z1DEL .LT. 0.1E0*P2 .AND. G2 .GE. 0.25E0*DX2) Z1DEL = AMIN1(
     2      G2, Z1DEL)
   8  IF (Z1DEL .LE. 0.0E0) Z1DEL = G2
      RETURN
      END
