      SUBROUTINE A90STH(T0, S0, X, T1, S1, NS, DT, TSTOP, OK, E,
     1   HANDLE, HANLE1)
      INTEGER NS
      EXTERNAL HANDLE, HANLE1
      REAL T0, S0(NS), X(1), T1, S1(NS), DT
      REAL TSTOP, E(NS)
      LOGICAL OK
      COMMON /A90STK/ NU, NV, K, NX
      INTEGER NU, NV, K, NX
C OUTPUT FILTER IN BPOSTS.
C SCRATCH SPACE ALLOCATED - S(A90STH) = S(HANDLE).
C X(NX).
      CALL HANDLE(T0, S0(NV+1), S0, T1, S1(NV+1), S1, NU, NV, K, X, NX
     1   , DT, TSTOP, E(NV+1), E, OK, HANLE1)
      RETURN
      END
