      LOGICAL FUNCTION A90STE(Y, NY, X, T, DT, ERRPAR, DELTA, E,
     1   ERROR, ERROR1)
      INTEGER NY
      EXTERNAL ERROR, ERROR1
      REAL Y(NY), X(1), T, DT, ERRPAR(2), DELTA
      REAL E(NY)
      LOGICAL ERROR
      COMMON /A90STK/ NU, NV, K, NX
      INTEGER NU, NV, K, NX
      LOGICAL ERPUTS
C THE ERROR FILTER FOR  ESSOM.
C SCRATCH SPACE ALLOCATED - S(A90STE) = S(ERROR).
C X(NX).
      ERPUTS = DELTA .EQ. 1.
      A90STE = ERROR(Y(NV+1), NU, K, X, NX, Y, NV, T, DT, ERRPAR,
     1   ERPUTS, E(NV+1), E, ERROR1)
      RETURN
      END
