      LOGICAL FUNCTION A9OSTN(U, NU, V, NV, T, DT, K, X, NX, AF,
     1   AF1, BC, BC1, D, D1234, ERROR, INMI, SCALE, ERRPAR)
      INTEGER NX
      EXTERNAL AF, AF1, BC, BC1, D, D1234
      EXTERNAL ERROR, INMI, SCALE
      INTEGER NU, NV, K
      REAL U(1), V(1), T, DT, X(NX), ERRPAR(2)
      COMMON /CSTAK/ DS
      DOUBLE PRECISION DS(500)
      COMMON /A9OSTM/ THETA, EGIVE, MINIT, MAXIT, KEEJAC
      INTEGER MINIT, MAXIT, KEEJAC
      REAL THETA, EGIVE
      COMMON /A9OSTK/ IUTETA, IVTETA, IUT, IVT
      INTEGER IUTETA, IVTETA, IUT, IVT
      INTEGER IDU, IEU, IEV, IDV, ISTKGT, IEU1
      INTEGER IEV1, IEU2, IEV2, IS(1000), IUOLD, IVOLD
      REAL RS(1000), WS(1000)
      LOGICAL A9OSTO, DONE, LS(1000)
      EQUIVALENCE (DS(1), WS(1), RS(1), IS(1), LS(1))
C NONLINEAR EQUATION SOLVER FOR POSTS.
C SCRATCH SPACE ALLOCATED -
C     S(A9OSTN) = IF ( THETA ~= 1 ) { NU*(NX-K)+NV } +
C                 3*(NU*(NX-K)+NV) +
C                 ( NU*(NX-K)+NV ) INTEGER +
C                 MAX ( S(A90STC), S(ERROR) )
C REAL WORDS.
C U(NX-K,NU),V(NV).
C THE PORT LIBRARY STACK AND ITS ALIASES.
      CALL ENTER(1)
      IVOLD = ISTKGT(NU*(NX-K)+NV, 3)
      IUOLD = IVOLD+NV
      IVTETA = ISTKGT(NU*(NX-K)+NV, 3)
      IUTETA = IVTETA+NV
      IVT = ISTKGT(NU*(NX-K)+NV, 3)
      IUT = IVT+NV
      IEV = ISTKGT(NU*(NX-K)+NV, 3)
      IEU = IEV+NV
      IDV = ISTKGT(NU*(NX-K)+NV, 3)
      IDU = IDV+NV
      IEV1 = ISTKGT(NU*(NX-K)+NV, 3)
      IEU1 = IEV1+NV
      IEV2 = ISTKGT(NU*(NX-K)+NV, 3)
      IEU2 = IEV2+NV
      DONE = A9OSTO(U, NU, V, NV, T, DT, K, X, NX, AF, AF1, BC, BC1, D
     1   , D1234, ERROR, INMI, SCALE, ERRPAR, WS(IUTETA), WS(IUT), WS(
     2   IVTETA), WS(IVT), WS(IUOLD), WS(IVOLD), RS(IEU), RS(IEV), RS(
     3   IEU1), RS(IEV1), RS(IEU2), RS(IEV2), WS(IDU), WS(IDV), NX-K,
     4   THETA, MINIT, MAXIT, KEEJAC, EGIVE)
      CALL LEAVE
      A9OSTN = DONE
      RETURN
      END
