      LOGICAL FUNCTION A9OSTE(U, NU, K, X, NX, V, NV, T, DT,
     1   ERRPAR, ERPUTS, EU, EV, ERROR)
      INTEGER NX
      EXTERNAL ERROR
      INTEGER NU, K, NV
      REAL U(1), X(NX), V(1), T, DT, ERRPAR(2)
      REAL EU(1), EV(1)
      LOGICAL ERPUTS, ERROR
C THE ERROR FILTER FOR NLEQS.
C SCRATCH SPACE ALLOCATED - S(A9OSTE) = S(ERROR).
C U(NX-K,NU),V(NV).
C EU(NX-K,NU),EV(NV).
      A9OSTE = ERROR(U, NU, NX-K, K, X, NX, V, NV, T, DT, ERRPAR,
     1   ERPUTS, EU, EV)
      RETURN
      END
