      SUBROUTINE A9OSTH(T0, U0, V0, T, U, V, NU, NV, K, X, NX, DT,
     1   TSTOP, EU, EV, OK, HANDLE)
      INTEGER NX
      EXTERNAL HANDLE
      INTEGER NU, NV, K
      REAL T0, U0(1), V0(1), T, U(1), V(1)
      REAL X(NX), DT, TSTOP, EU(1), EV(1)
      LOGICAL OK
      COMMON /A9OSTM/ THETA, EGIVE, MINIT, MAXIT, KEEJAC
      INTEGER MINIT, MAXIT, KEEJAC
      REAL THETA, EGIVE
      COMMON /A9OSTG/ TJ, DTJ, GETJAC, SEPATE
      REAL TJ, DTJ
      LOGICAL GETJAC, SEPATE
      COMMON /A9OSTF/ FNUM
      INTEGER FNUM
      COMMON /A90STT/ TGOOD
      REAL TGOOD
      COMMON /A90STR/ NJS, NFS, NTSS, NSSS, NNITS, NNDS, NNFS, NRS
      INTEGER NJS, NFS, NTSS, NSSS, NNITS, NNDS
      INTEGER NNFS, NRS
      LOGICAL TEMP
C OUTPUT FILTER FOR POSTS.
C SCRATCH SPACE ALLOCATED - S(A9OSTH) = S(HANDLE).
C (U0,U)(NX-K,NU),(V0,V)(NV).
C EU(NX-K,NU),EV(NV).
      IF (T0 .EQ. T) GOTO 1
         FNUM = 0
         TGOOD = T
         GOTO  2
   1     NRS = NRS+1
   2  TEMP = T0 .EQ. T
      IF (TEMP) TEMP = KEEJAC .EQ. 3
      IF (.NOT. TEMP) GOTO 3
         GETJAC = T0 .NE. TJ
         TJ = T0
   3  NTSS = NTSS+1
      CALL HANDLE(T0, U0, V0, T, U, V, NU, NX-K, NV, K, X, NX, DT,
     1   TSTOP)
      RETURN
      END
