      LOGICAL FUNCTION D90STE(Y, NY, X, T, DT, ERRPAR, DELTA, E,
     1   ERROR, ERROR1)
      INTEGER NY
      EXTERNAL ERROR, ERROR1
      REAL ERRPAR(2), E(NY)
      LOGICAL ERROR
      DOUBLE PRECISION Y(NY), X(1), T, DT, DELTA
      COMMON /D90STK/ NU, NV, K, NX
      INTEGER NU, NV, K, NX
      LOGICAL ERPUTS
C THE ERROR FILTER FOR DESSOM.
C SCRATCH SPACE ALLOCATED - S(D90STE) = S(ERROR).
C X(NX).
      ERPUTS = DELTA .EQ. 1D0
      D90STE = ERROR(Y(NV+1), NU, K, X, NX, Y, NV, T, DT, ERRPAR,
     1   ERPUTS, E(NV+1), E, ERROR1)
      RETURN
      END
