      LOGICAL FUNCTION D9OSTE(U, NU, K, X, NX, V, NV, T, DT,
     1   ERRPAR, ERPUTS, EU, EV, ERROR)
      INTEGER NX
      EXTERNAL ERROR
      INTEGER NU, K, NV
      REAL ERRPAR(2), EU(1), EV(1)
      LOGICAL ERPUTS, ERROR
      DOUBLE PRECISION U(1), X(NX), V(1), T, DT
C THE ERROR FILTER FOR NLEQS.
C SCRATCH SPACE ALLOCATED - S(D9OSTE) = S(ERROR).
C U(NX-K,NU),V(NV).
C EU(NX-K,NU),EV(NV).
      D9OSTE = ERROR(U, NU, NX-K, K, X, NX, V, NV, T, DT, ERRPAR,
     1   ERPUTS, EU, EV)
      RETURN
      END
