      LOGICAL FUNCTION D9OSTN(U, NU, V, NV, T, DT, K, X, NX, AF,
     1   AF1, BC, BC1, D, D1234, ERROR, INMI, SCALE, ERRPAR)
      INTEGER NX
      EXTERNAL AF, AF1, BC, BC1, D, D1234
      EXTERNAL ERROR, INMI, SCALE
      INTEGER NU, NV, K
      REAL ERRPAR(2)
      DOUBLE PRECISION U(1), V(1), T, DT, X(NX)
      COMMON /CSTAK/ DS
      DOUBLE PRECISION DS(500)
      COMMON /D9OSTM/ THETA, EGIVE, MINIT, MAXIT, KEEJAC
      INTEGER MINIT, MAXIT, KEEJAC
      REAL EGIVE
      DOUBLE PRECISION THETA
      COMMON /D9OSTK/ IUTETA, IVTETA, IUT, IVT
      INTEGER IUTETA, IVTETA, IUT, IVT
      INTEGER IDU, IEU, IEV, IDV, ISTKGT, IEU1
      INTEGER IEV1, IEU2, IEV2, IS(1000), IUOLD, IVOLD
      REAL RS(1000)
      LOGICAL D9OSTO, DONE, LS(1000)
      DOUBLE PRECISION WS(500)
      EQUIVALENCE (DS(1), WS(1), RS(1), IS(1), LS(1))
C NONLINEAR EQUATION SOLVER FOR POSTS.
C SCRATCH SPACE ALLOCATED -
C     S(D9OSTN) = IF ( THETA ~= 1 ) { NU*(NX-K)+NV } +
C                 3*(NU*(NX-K)+NV) +
C                 ( NU*(NX-K)+NV ) INTEGER +
C                 MAX ( S(D90STC), S(ERROR) )
C LONG REAL WORDS.
C U(NX-K,NU),V(NV).
C THE PORT LIBRARY STACK AND ITS ALIASES.
      CALL ENTER(1)
      IVOLD = ISTKGT(NU*(NX-K)+NV, 4)
      IUOLD = IVOLD+NV
      IVTETA = ISTKGT(NU*(NX-K)+NV, 4)
      IUTETA = IVTETA+NV
      IVT = ISTKGT(NU*(NX-K)+NV, 4)
      IUT = IVT+NV
      IEV = ISTKGT(NU*(NX-K)+NV, 3)
      IEU = IEV+NV
      IDV = ISTKGT(NU*(NX-K)+NV, 4)
      IDU = IDV+NV
      IEV1 = ISTKGT(NU*(NX-K)+NV, 3)
      IEU1 = IEV1+NV
      IEV2 = ISTKGT(NU*(NX-K)+NV, 3)
      IEU2 = IEV2+NV
      DONE = D9OSTO(U, NU, V, NV, T, DT, K, X, NX, AF, AF1, BC, BC1, D
     1   , D1234, ERROR, INMI, SCALE, ERRPAR, WS(IUTETA), WS(IUT), WS(
     2   IVTETA), WS(IVT), WS(IUOLD), WS(IVOLD), RS(IEU), RS(IEV), RS(
     3   IEU1), RS(IEV1), RS(IEU2), RS(IEV2), WS(IDU), WS(IDV), NX-K,
     4   THETA, MINIT, MAXIT, KEEJAC, EGIVE)
      CALL LEAVE
      D9OSTN = DONE
      RETURN
      END
