      DOUBLE PRECISION FUNCTION DEXPL(X)
      DOUBLE PRECISION X
      DOUBLE PRECISION SMALL, D1MACH, LOGBIG, BIG, LOGALL, DLOG
      DOUBLE PRECISION DEXP
      DATA SMALL/0D0/
      DATA BIG/0D0/
      DATA LOGALL/0D0/
      DATA LOGBIG/0D0/
C DEXPL(X) = EXP(X) EXCEPT WHEN IT WILL -
C   UNDERFLOW - 0 IS RETURNED,
C     OR
C   OVERFLOW - +BIG IS RETURNED, WITH AN ERROR STATE.
      IF (SMALL .NE. 0D0) GOTO 1
         SMALL = D1MACH(1)
         BIG = D1MACH(2)
         LOGALL = DLOG(SMALL*(50D0*D1MACH(4)+1D0))
         LOGBIG = DLOG(BIG*(1D0-50D0*D1MACH(4)))
   1  IF (X .GT. LOGALL) GOTO 2
         DEXPL = 0
         RETURN
   2     IF (X .LT. LOGBIG) GOTO 3
C/6S
C           CALL SETERR(25HDEXPL - EXPONENT OVERFLOW, 25, 1, 2)
C/7S
            CALL SETERR('DEXPL - EXPONENT OVERFLOW', 25, 1, 2)
C/
            DEXPL = BIG
            RETURN
   3  CONTINUE
   4  DEXPL = DEXP(X)
      RETURN
      END
