      SUBROUTINE DLPLMX(XI, NX, V, NV, X, XV)
      INTEGER NV, NX
      DOUBLE PRECISION XI(NX), V(NV), X(NX), XV(NX, NV)
      COMMON /CSTAK/ DS
      DOUBLE PRECISION DS(500)
      INTEGER IXT, ISTKGT, IXXI, IXTV, IXVV, IS(1000)
      INTEGER IXXIV
      REAL RS(1000)
      LOGICAL LS(1000)
      DOUBLE PRECISION WS(500)
      EQUIVALENCE (DS(1), WS(1), RS(1), IS(1), LS(1))
C X(XI,V) IS A PIECEWISE LINEAR MAP IN XI, V == BREAKPOINTS.
      CALL ENTER(1)
C/6S
C     IF (NX .LT. 1) CALL SETERR(18HDLPLMX - NX .LT. 1, 18, 1, 2)
C     IF (NV .LT. 2) CALL SETERR(18HDLPLMX - NV .LT. 2, 18, 2, 2)
C/7S
      IF (NX .LT. 1) CALL SETERR('DLPLMX - NX .LT. 1', 18, 1, 2)
      IF (NV .LT. 2) CALL SETERR('DLPLMX - NV .LT. 2', 18, 2, 2)
C/
      IXXI = ISTKGT(NX, 4)
      IXXIV = ISTKGT(NX*NV, 4)
      IXVV = ISTKGT(NX*NV**2, 4)
      IXT = ISTKGT(NX, 4)
      IXTV = ISTKGT(NX*NV, 4)
      CALL DLPLM(XI, NX, V, NV, X, WS(IXXI), WS(IXXIV), XV, WS(IXVV),
     1   WS(IXT), WS(IXTV))
      CALL LEAVE
      RETURN
      END
