      SUBROUTINE DPOSTD(T, K, X, NX, U, UT, NU, NXMK, V, VT, NV, D
     1   , DU, DUT, DV, DVT)
      INTEGER NXMK, NV, NX
      INTEGER K, NU
      DOUBLE PRECISION T, X(NX), U(NXMK, 1), UT(NXMK, 1), V(NV), VT(NV)
      DOUBLE PRECISION D(NV), DU(NV, NXMK, 1), DUT(NV, NXMK, 1), DV(NV
     1   , NV), DVT(NV, NV)
C SCRATCH SPACE ALLOCATED - NONE.
C (U,UT)(NXMK,NU).
C (DU,DUT)(NV,NXMK,NU).
      RETURN
      END
