      SUBROUTINE DPOSTX
      COMMON /D90STR/ STATS
      INTEGER STATS(8)
      INTEGER I1MACH
      INTEGER TEMP
C TO PRINT THE RUN-TIME STATISTICS FOR POST.
      CALL D9OSTX(STATS, 0)
      TEMP = I1MACH(2)
      WRITE (TEMP,  1) STATS
   1  FORMAT (31H DPOST(J,F,TS,SS,NIT,ND,NF,R) =, 8(I5))
      RETURN
      END
