      SUBROUTINE DPOSTN(NU, NV, NXMK, K, X, NX, T, DT, UOLD, VOLD,
     1   U, UT, V, VT)
      INTEGER NXMK, NX
      INTEGER NU, NV, K
      DOUBLE PRECISION X(NX), T, DT, UOLD(NXMK, 1), VOLD(1), U(NXMK, 1)
      DOUBLE PRECISION UT(NXMK, 1), V(1), VT(1)
C THE DEFAULT NEWTON ITERATION INITIALIZER FOR POSTS.
C UOLD(NXMK,NU),VOLD(NV).
C (U,UT)(NXMK,NU).
C (V,VT)(NV).
      RETURN
      END
