      SUBROUTINE DRCSM(A, M, N, R, C, RC)
      INTEGER M, N
      INTEGER RC(N)
      DOUBLE PRECISION A(M, N), R(M), C(N)
C TO GET THE ROW AND COLUMN SCALE FACTORS FOR A.
C/6S
C     IF (M .LT. 1) CALL SETERR(16HDRCSM - M .LT. 1, 16, 1, 2)
C     IF (N .LT. 1) CALL SETERR(16HDRCSM - N .LT. 1, 16, 2, 2)
C/7S
      IF (M .LT. 1) CALL SETERR('DRCSM - M .LT. 1', 16, 1, 2)
      IF (N .LT. 1) CALL SETERR('DRCSM - N .LT. 1', 16, 2, 2)
C/
C GET THE ROW FACTOR.
      CALL DRCSR(A, M, N, R)
C GET THE COLUMN SCALE FACTOR.
      CALL DRCSC(A, M, N, R, C, RC)
      RETURN
      END
