      SUBROUTINE DRCSBM(A, M, N, R, C, RC)
      INTEGER M, N
      INTEGER RC(M)
      DOUBLE PRECISION A(M, N), R(M), C(M)
C TO GET THE ROW AND COLUMN SCALE FACTORS FOR A.
      CALL ENTER(1)
C/6S
C     IF (M .LT. 1) CALL SETERR(17HDRCSBM - M .LT. 1, 17, 1, 2)
C     IF (N .LT. 1) CALL SETERR(17HDRCSBM - N .LT. 1, 17, 2, 2)
C/7S
      IF (M .LT. 1) CALL SETERR('DRCSBM - M .LT. 1', 17, 1, 2)
      IF (N .LT. 1) CALL SETERR('DRCSBM - N .LT. 1', 17, 2, 2)
C/
C GET THE ROW FACTOR.
      CALL DRCSBR(A, M, N, R)
C GET THE COLUMN SCALE FACTOR.
      CALL DRCSBC(A, M, N, R, C, RC)
      CALL LEAVE
      RETURN
      END
