      SUBROUTINE DRCSA(A, M, N, R, C, RC)
      INTEGER M, N
      INTEGER RC(N)
      DOUBLE PRECISION A(M, N), R(M), C(N)
      INTEGER NERROR, NERR, IROLD
C TO GET THE ROW AND COLUMN SCALE FACTORS FOR A
C AND PERFORM THE SCALING.
C/6S
C     IF (M .LT. 1) CALL SETERR(16HDRCSA - M .LT. 1, 16, 1, 2)
C     IF (N .LT. 1) CALL SETERR(16HDRCSA - N .LT. 1, 16, 2, 2)
C/7S
      IF (M .LT. 1) CALL SETERR('DRCSA - M .LT. 1', 16, 1, 2)
      IF (N .LT. 1) CALL SETERR('DRCSA - N .LT. 1', 16, 2, 2)
C/
C TURN ERROR RECOVERY ON AND SAVE OLD VALUE.
      CALL ENTSRC(IROLD, 1)
C GET ROW AND COLUMN SCALE FACTORS.
      CALL DRCSM(A, M, N, R, C, RC)
C APPLY THE SCALE FACTORS TO A.
      CALL DRCSS(A, M, N, R, C, RC)
      IF (NERROR(NERR) .EQ. 0) GOTO 1
         CALL ERROFF
C/6S
C        CALL SETERR(42HDRCSA - MUST HAVE 1/(S*L) IN MACHINE RANGE, 42
C    1      , 3, 1)
C/7S
         CALL SETERR('DRCSA - MUST HAVE 1/(S*L) IN MACHINE RANGE', 42
     1      , 3, 1)
C/
         RETURN
C RESTORE OLD RECOVERY VALUE.
   1  CALL RETSRC(IROLD)
      RETURN
      END
