      REAL FUNCTION EXPL(X)
      REAL X
      REAL SMALL, R1MACH, LOGBIG, BIG, EXP, LOGALL
      REAL ALOG
      DATA SMALL/0E0/
      DATA BIG/0E0/
      DATA LOGALL/0E0/
      DATA LOGBIG/0E0/
C  EXPL(X) = EXP(X) EXCEPT WHEN IT WILL -
C   UNDERFLOW - 0 IS RETURNED,
C     OR
C   OVERFLOW - +BIG IS RETURNED, WITH AN ERROR STATE.
      IF (SMALL .NE. 0.) GOTO 1
         SMALL = R1MACH(1)
         BIG = R1MACH(2)
         LOGALL = ALOG(SMALL*(50.*R1MACH(4)+1.))
         LOGBIG = ALOG(BIG*(1.-50.*R1MACH(4)))
   1  IF (X .GT. LOGALL) GOTO 2
         EXPL = 0
         RETURN
   2     IF (X .LT. LOGBIG) GOTO 3
C/6S
C           CALL SETERR(25H EXPL - EXPONENT OVERFLOW, 25, 1, 2)
C/7S
            CALL SETERR(' EXPL - EXPONENT OVERFLOW', 25, 1, 2)
C/
            EXPL = BIG
            RETURN
   3  CONTINUE
   4  EXPL = EXP(X)
      RETURN
      END
