      SUBROUTINE LPLMX(XI, NX, V, NV, X, XV)
      INTEGER NV, NX
      REAL XI(NX), V(NV), X(NX), XV(NX, NV)
      COMMON /CSTAK/ DS
      DOUBLE PRECISION DS(500)
      INTEGER IXT, ISTKGT, IXXI, IXTV, IXVV, IS(1000)
      INTEGER IXXIV
      REAL RS(1000), WS(500)
      LOGICAL LS(1000)
      EQUIVALENCE (DS(1), WS(1), RS(1), IS(1), LS(1))
C X(XI,V) IS A PIECEWISE LINEAR MAP IN XI, V == BREAKPOINTS.
      CALL ENTER(1)
C/6S
C     IF (NX .LT. 1) CALL SETERR(18H LPLMX - NX .LT. 1, 18, 1, 2)
C     IF (NV .LT. 2) CALL SETERR(18H LPLMX - NV .LT. 2, 18, 2, 2)
C/7S
      IF (NX .LT. 1) CALL SETERR(' LPLMX - NX .LT. 1', 18, 1, 2)
      IF (NV .LT. 2) CALL SETERR(' LPLMX - NV .LT. 2', 18, 2, 2)
C/
      IXXI = ISTKGT(NX, 3)
      IXXIV = ISTKGT(NX*NV, 3)
      IXVV = ISTKGT(NX*NV**2, 3)
      IXT = ISTKGT(NX, 3)
      IXTV = ISTKGT(NX*NV, 3)
      CALL LPLM(XI, NX, V, NV, X, WS(IXXI), WS(IXXIV), XV, WS(IXVV), WS(
     1   IXT), WS(IXTV))
      CALL LEAVE
      RETURN
      END
