      SUBROUTINE POST1(U, NU, K, X, NX, V, NV, TSTART, TSTOP, DT
     1   , AF, BC, D, ERROR, ERRPAR, ERPUTS, HANDLE)
      EXTERNAL AF, BC, D, ERROR, HANDLE
      INTEGER NU, K, NX, NV
      REAL U(1), X(1), V(1), TSTART, TSTOP, DT
      REAL ERRPAR(2)
      LOGICAL ERPUTS
      INTEGER KMAX, KINIT
      LOGICAL EQUIL, XPOLY
C THE SECOND LEVEL OF  POSTS.
C U(NX-K,NU),X(NX),V(NV).
      KMAX = 10
      XPOLY = .FALSE.
      KINIT = 2
      EQUIL = .TRUE.
      CALL POST2(U, NU, K, X, NX, V, NV, TSTART, TSTOP, DT, AF, BC, D,
     1   EQUIL, KMAX, XPOLY, KINIT, ERROR, ERRPAR, ERPUTS, HANDLE)
      RETURN
      END
