      SUBROUTINE POSTH(T0, U0, V0, T, U, V, NU, NXMK, NV, K, X,
     1   NX, DT, TSTOP)
      INTEGER NXMK, NX
      INTEGER NU, NV, K
      REAL T0, U0(NXMK, 1), V0(1), T, U(NXMK, 1), V(1)
      REAL X(NX), DT, TSTOP
C DEFAULT HANDLE PROCEDURE FOR POSTS.
C SCRATCH SPACE ALLOCATED - NONE.
C REAL (U0,U)(NXMK,NU),(V0,V)(NV).
      RETURN
      END
