      SUBROUTINE POST(U, NU, K, X, NX, V, NV, TSTART, TSTOP, DT,
     1   AF, BC, D, ERRPAR, HANDLE)
      EXTERNAL AF, BC, D, HANDLE
      INTEGER NU, K, NX, NV
      REAL U(1), X(1), V(1), TSTART, TSTOP, DT
      REAL ERRPAR(2)
      EXTERNAL POSTE, POSTN, POSTP
C THE FIRST LEVEL OF  POST.
C U(NX-K,NU),X(NX),V(NV).
      CALL POSTR(U, NU, K, X, NX, V, NV, TSTART, TSTOP, DT, AF, BC, D,
     1   POSTE, ERRPAR, POSTN, POSTP, HANDLE)
      RETURN
      END
