      SUBROUTINE RCSBM(A, M, N, R, C, RC)
      INTEGER M, N
      INTEGER RC(M)
      REAL A(M, N), R(M), C(M)
C TO GET THE ROW AND COLUMN SCALE FACTORS FOR A.
      CALL ENTER(1)
C/6S
C     IF (M .LT. 1) CALL SETERR(17H RCSBM - M .LT. 1, 17, 1, 2)
C     IF (N .LT. 1) CALL SETERR(17H RCSBM - N .LT. 1, 17, 2, 2)
C/7S
      IF (M .LT. 1) CALL SETERR(' RCSBM - M .LT. 1', 17, 1, 2)
      IF (N .LT. 1) CALL SETERR(' RCSBM - N .LT. 1', 17, 2, 2)
C/
C GET THE ROW FACTOR.
      CALL RCSBR(A, M, N, R)
C GET THE COLUMN SCALE FACTOR.
      CALL RCSBC(A, M, N, R, C, RC)
      CALL LEAVE
      RETURN
      END
