         SUBROUTINE  BPFS(N,ML,G,IG,B,IB,NB)
C
C THIS SUBROUTINE SOLVES LX=B WHERE L IS A LOWER TRIANGULAR
C BAND MATRIX
C INPUT PARAMETERS
C N      THE ORDER OF THE SYSTEM
C ML     THE NUMBER OF NONZERO ELEMENTS OF L ON AND BELOW
C        THE DIAGONG,THE ROW DIMENSION OF G
C G     AN IG X N MATRIX CONTAINING THE LOWERTRIANGULAR
C        BAND MATRIX. NOTE THAT G(1+I-J,I)=L(I,J)
C IG    ROW DIMENSION OF G
C B      MATRIX OF RIGHT HAND SIDES
C IB     ROW DIMENSION OF B
C NB     NUMBER OF RIGHT HAND SIDES
C OUTPUT PARAMETERS
C B      THE SOLUTION X
C SCRATCH SPACE GLOCATED - NONE
C ERROR CONDITIONS
C 1     N.LT.1     FATG
C 2     ML.LT.1     FATG
C 3     IG.LT.ML   FATG
C 4     IB.LT.N     FATG
C 5     NB.LT.1     FATG
C
        INTEGER IG,N,ML
        REAL G(IG,N),B(IB,NB)
        REAL X
C CHECK ERROR CONDITIONS
C/6S
C      IF (N.LT.1)CALL SETERR(13H  BPFS-N.LT.1,13,1,2)
C      IF( ML.LT.1)CALL SETERR(14H  BPFS-ML.LT.1,14,2,2)
C      IF (IG.LT.ML)CALL SETERR(15H  BPFS-IG.LT.ML,15,3,2)
C      IF (IB.LT.N) CALL SETERR(14H  BPFS-IB.LT.N,14,4,2)
C      IF (NB.LT.1) CALL SETERR(14H  BPFS-NB.LT.1,14,5,2)
C/7S
       IF (N.LT.1)CALL SETERR('  BPFS-N.LT.1',13,1,2)
       IF( ML.LT.1)CALL SETERR('  BPFS-ML.LT.1',14,2,2)
       IF (IG.LT.ML)CALL SETERR('  BPFS-IG.LT.ML',15,3,2)
       IF (IB.LT.N) CALL SETERR('  BPFS-IB.LT.N',14,4,2)
       IF (NB.LT.1) CALL SETERR('  BPFS-NB.LT.1',14,5,2)
C/
       IF (ML.EQ.1) RETURN
       CALL ENTER(1)
       M1=ML-1
       DO 80 J=1,NB
       DO 60 K=1,N
          X=B(K,J)
 10         IF (K.EQ.N) GO TO 80
            KP1=K+1
            IEND=M1+K
             II=1
            IF (N.LT.IEND)IEND=N
            DO 50 I=KP1,IEND
                 II=II+1
                 B(I,J)=B(I,J)-G(II,K)*X
 50         CONTINUE
 60       CONTINUE
 80       CONTINUE
 100     CALL LEAVE
          RETURN
         END
