          SUBROUTINE CB4ADF(N,ML,M,G,IG,B,IB,NB,MU)
C
C THIS SUBROUTINE DETERMINES THE LU DECOMPOSITION OF A
C BANDED UNSYMMETRIC MATRIX USING GAUSSIAN ELIMINATION
C WITH PARTIAL PIVOTING AND APPLIES THE TRANSFORMATIONS
C FOR L(INVERSE) TO B
C INPUT PARAMETERS
C N      THE ORDER OF THE MATRIX
C ML      MAXIMUM NUMBER OF ELEMENTS ON OR BELOW
C         THE DIAGONAL IN ANY COLUMN OF THE MATRIX
C M       THE MAXIMUM NUMBER OF NONZERO ELEMENTS IN EACH
C         COLUMN
C G       THE MATRIX A STORED AS AN IG X N ARRAY
C         WITH G(ML+J-I,I)=A(I,J).I.E.THE LEFTMOST
C         DIAGONAL OF THE BAND MATRIX IS THE FIRST ROW OF G
C IG      ROW DIMENSION OF IG ,MUST NOT BE LESS THAN M
C B       AN IB X NB MATRIX OF THE RIGHT HAND SIDES
C IB      ROW DIMENSION OF B,MUST BE AT LEAST N
C NB      NUMBER OF RIGHT HAND SIDES
C OUTPUT PARAMETERS
C G       THE UPPER TRIANGULAR BAND FACTOR OF A
C B       THE TRANSFORMED RIGHT HAND SIDE,THE SOLUTION TO
C         LX=B
C MU      THE NUMBER OF NONZERO DIAGONALS IN THE UPPER
C         TRIANGULAR BAND FACTOR
C SCRATCH STORAGE ALLOCATED-NONE
C ERROR STATES
C 1   N.LT.1      FATAL
C 2   ML.LT.1     FATAL
C 3   M.LT.ML     FATAL
C 4   IG.LT.M     FATAL
C 5   IB.LT.N     FATAL
C 6   NB.LT.1     FATAL
C 10+K SINGULAR MATRIX OF RANK K  RECOVERABLE
           INTEGER ML,N,IG,IB,NB
           COMPLEX G(IG,N),B(IB,NB)
           REAL EPS,R1MACH
C
C CHECK FOR INPUT ERRORS
C
C/6S
C      IF (N.LT.1)CALL SETERR(13HCB4ADF-N.LT.1,13,1,2)
C      IF (ML.LT.1)CALL SETERR(14HCB4ADF-ML.LT.1,14,2,2)
C      IF (M.LT.ML) CALL SETERR(14HCB4ADF-ML.LT.M,14,3,2)
C      IF (IG.LT.M) CALL SETERR(14HCB4ADF-IG.LT.M,14,4,2)
C      IF (IB.LT.N) CALL SETERR(14HCB4ADF-IB.LT.N,14,5,2)
C      IF (NB.LT.1)CALL SETERR(14HCB4ADF-NB.LT.1,14,6,2)
C/7S
       IF (N.LT.1)CALL SETERR('CB4ADF-N.LT.1',13,1,2)
       IF (ML.LT.1)CALL SETERR('CB4ADF-ML.LT.1',14,2,2)
       IF (M.LT.ML) CALL SETERR('CB4ADF-ML.LT.M',14,3,2)
       IF (IG.LT.M) CALL SETERR('CB4ADF-IG.LT.M',14,4,2)
       IF (IB.LT.N) CALL SETERR('CB4ADF-IB.LT.N',14,5,2)
       IF (NB.LT.1)CALL SETERR('CB4ADF-NB.LT.1',14,6,2)
C/
        CALL ENTER(1)
         EPS=R1MACH(4)*CBANM(N,ML,M,G,IG)
         CALL CB4ALF(N,ML,M,G,IG,B,IB,NB,MU,EPS)
C/6S
C         IF(NERROR(IERR).NE.0)
C    1      CALL N5ERR(22HCB4ADF-SINGULAR MATRIX,22,IERR,1)
C/7S
          IF(NERROR(IERR).NE.0)
     1      CALL N5ERR('CB4ADF-SINGULAR MATRIX',22,IERR,1)
C/
          CALL LEAVE
          RETURN
          END
