          SUBROUTINE   CBADC(N,ML,M,G,IG,AL,IAL,INT,MU)
C
C THIS SUBROUTINE DETERMINES THE LU DECOMPOSITION OF A
C BANDED UNSYMMETRIC MATRIX USING GAUSSIAN ELIMINATION
C WITH PARTIAL PIVOTING
C INPUT PARAMETERS
C N      THE ORDER OF THE MATRIX
C ML      MAXIMUM NUMBER OF NONZERO ELEMENTS ON OR BELOW
C         THE DIAGONAL IN ANY COLUMN OF THE MATRIX
C M       THE MAXIMUM NUMBER OF NONZERO ELEMENTS IN EACH
C         COLUMN
C G       THE MATRIX A STORED AS AN IG X N ARRAY
C         WITH G(ML+J-I)=A(I,J).I.E. THE LEFTMOST
C         DIAGONAL OF THE BAND MATRIX IS THE FIRST ROW OF G
C IG      ROW DIMENSION OF IG ,MUST NOT BE LESS THAN M
C IAL     ROW DIMENSION OF AL, MUST NOT BE LESS THAN ML
C OUTPUT PARAMETERS
C G       THE UPPER TRIANGULAR BAND FACTOR OF A
C AL      AN IAL X N ARRAY CONTAINING THE LOWER TRIANGULAR
C         BAND FACTOR OF A
C INT     AN INTEGER VECTOR OF LENGTH N RECORDING INTERCHANGES
C          INVOLVED IN GAUSSIAN ELIMINATION
C MU      THE NUMBER OF NONZERO DIAGONALS IN THE UPPER
C         TRIANGULAR BAND FACTOR
C SCRATCH STORAGE ALLOCATED-NONE
C ERROR STATES
C 1   N.LT.1      FATAL
C 2   ML.LT.1     FATAL
C 3   M.LT.ML     FATAL
C 4   IG.LT.M     FATAL
C 5   IAL.LT.ML   FATAL
C 10+K SINGULAR MATRIX OF RANK K   RECOVERABLE
           INTEGER IG,IAL
           INTEGER N,ML,M,INT(N)
           COMPLEX G(IG,N),AL(IAL,N)
           REAL EPS,R1MACH
C
C CHECK FOR INPUT ERRORS
C
C/6S
C      IF (N.LT.1)CALL SETERR(13H CBADC-N.LT.1,13,1,2)
C      IF (ML.LT.1)CALL SETERR(14H CBADC-ML.LT.1,14,2,2)
C      IF (M.LT.ML) CALL SETERR(14H CBADC-ML.LT.M,14,3,2)
C      IF (IG.LT.M) CALL SETERR(14H CBADC-IG,LT.M,14,4,2)
C      IF (IAL.LT.ML)CALL SETERR(16H CBADC-IAL.LT.ML,16,5,2)
C/7S
       IF (N.LT.1)CALL SETERR(' CBADC-N.LT.1',13,1,2)
       IF (ML.LT.1)CALL SETERR(' CBADC-ML.LT.1',14,2,2)
       IF (M.LT.ML) CALL SETERR(' CBADC-ML.LT.M',14,3,2)
       IF (IG.LT.M) CALL SETERR(' CBADC-IG,LT.M',14,4,2)
       IF (IAL.LT.ML)CALL SETERR(' CBADC-IAL.LT.ML',16,5,2)
C/
       CALL ENTER(1)
          EPS=CBANM(N,ML,M,G,IG)*R1MACH(4)
          CALL   CBALU(N,ML,M,G,IG,AL,IAL,INT,MU,EPS)
C/6S
C         IF(NERROR(IERR).NE.0)
C    1      CALL N5ERR(22H CBADC-SINGULAR MATRIX,22,IERR,1)
C/7S
          IF(NERROR(IERR).NE.0)
     1      CALL N5ERR(' CBADC-SINGULAR MATRIX',22,IERR,1)
C/
          CALL LEAVE
          RETURN
          END
