        REAL FUNCTION  CBANM(N,ML,M,G,IG)
        COMPLEX G(IG,1)
        REAL SUM
C THIS SUBROUTINE COMPUTES THE INFINITY NORM OF A BAND MATRIX
C STORED IN BAND FORM
C/6S
C       IF (N.LT.1)CALL SETERR(12HCBANM-N.LT.1,12,1,2)
C       IF (ML.LT.1) CALL SETERR(13HCBANM-ML.LT.1,13,2,2)
C       IF (M.LT.ML)CALL SETERR(13HCBANM-M.LT.ML,13,3,2)
C       IF(IG.LT.M) CALL SETERR(13HCBANM-IG.LT.M,13,4,2)
C/7S
        IF (N.LT.1)CALL SETERR('CBANM-N.LT.1',12,1,2)
        IF (ML.LT.1) CALL SETERR('CBANM-ML.LT.1',13,2,2)
        IF (M.LT.ML)CALL SETERR('CBANM-M.LT.ML',13,3,2)
        IF(IG.LT.M) CALL SETERR('CBANM-IG.LT.M',13,4,2)
C/
        JB=ML+1
        JE=M
        JEND=N-(M-ML)
         CBANM=0.0D0
        DO 10 I=1,N
           SUM=0.0
           JB=MAX0(1,JB-1)
           DO 5 J=JB,JE
              SUM=SUM+CABS(G(J,I))
 5         CONTINUE
           IF(I.GE.JEND)JE=JE-1
           IF(SUM.GT.CBANM) CBANM=SUM
 10      CONTINUE
         RETURN
         END
