         REAL FUNCTION CBPNM(N,ML,G,IG)
C
C  COMPUTE THE MAXIMUM COLUMN SUM (1-NORM) OF A BAND POSITIVE
C  DEFINITE MATRIX
C
C
      INTEGER N,ML,IG
      COMPLEX G(IG,N)
      REAL SUM
C/6S
C        IF (N.LT.1) CALL SETERR(12HCBPNM-N.LT.1,12,1,2)
C        IF (ML.LT.1) CALL SETERR(13HCBPNM-ML.LT.1,13,2,2)
C        IF (IG.LT.ML) CALL SETERR(14HCBPNM-IG.LT.ML,14,3,2)
C/7S
         IF (N.LT.1) CALL SETERR('CBPNM-N.LT.1',12,1,2)
         IF (ML.LT.1) CALL SETERR('CBPNM-ML.LT.1',13,2,2)
         IF (IG.LT.ML) CALL SETERR('CBPNM-IG.LT.ML',14,3,2)
C/
      CBPNM =0.0E0
      NMML = N-ML
C COMPUTE SUM OF COLUMN ELEMENTS STORED AS A COLUMN IN G
      JE = ML
      DO 4 I=1,N
         SUM = 0.0E0
         DO 1 J = 1,JE
 1          SUM = SUM + CABS(G(J,I))
         IF ( NMML.LT.I) JE = JE - 1
C COMPUTE SUM OF COLUMN ELEMENTS STORED ON DIAGONAL IN G
      K = I-1
      L = 2
 2    IF ( (L.GT.ML) .OR. (K.LT.1)  ) GO TO 3
      SUM = SUM + CABS(G(L,K))
      K = K-1
      L = L+1
      GO TO 2
 3    IF (SUM.GT.CBPNM) CBPNM = SUM
 4    CONTINUE
      RETURN
      END
