       SUBROUTINE CGEDC(N,A,IA,INTER)
       INTEGER N,IA,INTER(N)
       COMPLEX A(IA,N)
       REAL EPS
C THIS SUBROUTINE USES GAUSSIAN ELIMINATION WITH PARTIAL
C PIVOTING TO DECOMPOSE A MATRIX A INTO P*A=L*U WHERE
C P IS A PERMUTATION MATRIX,L IS A LOWER UNIT TRIANGULAR
C MATRIX, AND U IS AN UPPER TRIANGULAR MATRIX
C INPUT PARAMETERS
C     N      ORDER OF THE PROBLEM
C     A      AN IA X N ARRAY CONTAINING THE MATRIX TO BE
C            FACTORED
C     IA     ROW DIMENSION OF THE A ARRAY
C OUTPUT PARAMETERS
C     A      CONTAINS THE UPPER TRIANGULAR MATRIX U AND A
C            PERMUTED VERSION OF THE LOWER TRIANGULAR MATRIX I-L
C     INTER  AN INTEGER VECTOR WHOSE ITH COMPONENT RECORDS THE
C            ITH PIVOT ROW
C     EPS    REAL VARIABLE, IF THE MAGNITUDE OF THE PIVOT IS
C            LESS THAN OR EQUAL TO EPS, THE MATRIX IS
C            CONSIDERED SINGULAR
C THE SUBROUTINES CGELU AND CGENMENM ARE CALLED
C ERROR CONDITIONS
C      1      N IS LESS THAN 1   FATAL
C      2      IA.LT.N       FATAL
C      10+K   SINGULAR MATRIX OF RANK K    RECOVERABLE
C
C/6S
C       IF(N.LT.1)CALL SETERR(12HCGEDC-N.LT.1,12,1,2)
C       IF(IA.LT.N)CALL SETERR(13HCGEDC-IA.LT.N,13,2,2)
C/7S
        IF(N.LT.1)CALL SETERR('CGEDC-N.LT.1',12,1,2)
        IF(IA.LT.N)CALL SETERR('CGEDC-IA.LT.N',13,2,2)
C/
         CALL ENTER(1)
        EPS=R1MACH(4)*CGENM(N,A,IA)
        CALL CGELU(N,A,IA,INTER,EPS)
C/6S
C       IF(NERROR(IERR).NE.0)
C    1     CALL N5ERR(21HCGEDC-SINGULAR MATRIX,21,IERR,1)
C/7S
        IF(NERROR(IERR).NE.0)
     1     CALL N5ERR('CGEDC-SINGULAR MATRIX',21,IERR,1)
C/
        CALL LEAVE
        RETURN
        END
