        DOUBLE PRECISION FUNCTION  DBANM(N,ML,M,G,IG)
        DOUBLE PRECISION G(IG,1),SUM
C THIS SUBROUTINE COMPUTES THE INFINITY NORM OF A BAND MATRIX
C STORED IN BAND FORM
C/6S
C       IF (N.LT.1)CALL SETERR(12HDBANM-N.LT.1,12,1,2)
C       IF (ML.LT.1) CALL SETERR(13HDBANM-ML.LT.1,13,2,2)
C       IF (M.LT.ML)CALL SETERR(13HDBANM-M.LT.ML,13,3,2)
C       IF(IG.LT.M) CALL SETERR(13HDBANM-IG.LT.M,13,4,2)
C/7S
        IF (N.LT.1)CALL SETERR('DBANM-N.LT.1',12,1,2)
        IF (ML.LT.1) CALL SETERR('DBANM-ML.LT.1',13,2,2)
        IF (M.LT.ML)CALL SETERR('DBANM-M.LT.ML',13,3,2)
        IF(IG.LT.M) CALL SETERR('DBANM-IG.LT.M',13,4,2)
C/
        JB=ML+1
        JE=M
        JEND=N-(M-ML)
         DBANM=0.0D0
        DO 10 I=1,N
           SUM=0.0
           JB=MAX0(1,JB-1)
           DO 5 J=JB,JE
              SUM=SUM+DABS(G(J,I))
 5         CONTINUE
           IF(I.GE.JEND)JE=JE-1
           IF(SUM.GT.DBANM) DBANM=SUM
 10      CONTINUE
         RETURN
         END
