      SUBROUTINE DC1RSS(M,N,MATU,MATV,MFLAG)
      INTEGER M, N, MFLAG
      DOUBLE PRECISION C, XOVRPT, R, DFLOAT
      LOGICAL MATU, MATV
C     -----------------------------------------------------------------
C
C     SET VALUE FOR C. THE VALUE FOR C DEPENDS ON THE RELATIVE
C     EFFICIENCY OF FLOATING POINT MULTIPLICATIONS, FLOATING POINT
C     ADDITIONS AND TWO-DIMENSIONAL ARRAY INDEXINGS ON THE
C     COMPUTER WHERE THIS SUBROUTINE IS TO BE RUN.  C SHOULD
C     USUALLY BE BETWEEN 2 AND 4.  FOR DETAILS ON CHOOSING C, SEE
C     (2).  THE ALGORITHM IS NOT SENSITIVE TO THE VALUE OF C
C     ACTUALLY USED AS LONG AS C IS BETWEEN 2 AND 4.
C
      C = 4.D0
C
C     DETERMINE CROSS-OVER POINT
C
      IF (MATU .AND. MATV) XOVRPT = (C+7.D0/3.D0)/C
      IF (MATU .AND. .NOT.MATV) XOVRPT = (C+7.D0/3.D0)/C
      IF (.NOT.MATU .AND. MATV) XOVRPT = 5.D0/3.D0
      IF (.NOT.MATU .AND. .NOT.MATV) XOVRPT = 5.D0/3.D0
C
C     DETERMINE WHETHER TO USE GOLUB-REINSCH OR THE MODIFIED
C     ALGORITHM.
C
      R = DFLOAT(M)/DFLOAT(N)
      MFLAG = 0
      IF (R .GE. XOVRPT) MFLAG = 1
C
      RETURN
      END
