        DOUBLE PRECISION FUNCTION DGENM(N,A,IA)
        DOUBLE PRECISION SUM,A(IA,1),DASUM
C THIS SUBROUTINE DETERMINES THE 1 NORM OF AN N X N MATRIX A
C WHOSE ROW DIMENSION IS IA
C/6S
C        IF (N.LT.1) CALL SETERR(12HDGENM-N.LT.1,12,1,2)
C        IF (IA.LT.N) CALL SETERR(13HDGENM-IA.LT.N,13,2,2)
C/7S
         IF (N.LT.1) CALL SETERR('DGENM-N.LT.1',12,1,2)
         IF (IA.LT.N) CALL SETERR('DGENM-IA.LT.N',13,2,2)
C/
        DGENM=0.0
        DO 10 I=1,N
           SUM=DASUM(N,A(1,I),1)
           IF (SUM.GT.DGENM) DGENM=SUM
 10      CONTINUE
         RETURN
         END
