      SUBROUTINE DSVD(M,N,A,NAU,U,MATU,W,V,NV,MATV)
      INTEGER NAU,NV,M,N,MFLAG
      INTEGER ISTKGT,IERR
      INTEGER ID, IRV1, IZ
      DOUBLE PRECISION A(NAU,N),W(N),U(NAU,N),V(NV,N)
      LOGICAL MATU, MATV
      DOUBLE PRECISION DSTAK(500)
      COMMON /CSTAK/DSTAK
C
      CALL ENTER(0)
C/6S
C     IF (M .LT. N) CALL SETERR(12HDSVD- M.LT.N,12,1,2)
C     IF (NAU .LT. M) CALL SETERR (14HDSVD- NAU.LT.M,14,2,2)
C     IF (NV .LT. N) CALL SETERR (13HDSVD- NV.LT.N,13,3,2)
C     IF (M .LT. 1) CALL SETERR (12HDSVD- M.LT.1,12,4,2)
C     IF (N .LT.1) CALL SETERR (12HDSVD- N.LT.1,12,5,2)
C/7S
      IF (M .LT. N) CALL SETERR('DSVD- M.LT.N',12,1,2)
      IF (NAU .LT. M) CALL SETERR ('DSVD- NAU.LT.M',14,2,2)
      IF (NV .LT. N) CALL SETERR ('DSVD- NV.LT.N',13,3,2)
      IF (M .LT. 1) CALL SETERR ('DSVD- M.LT.1',12,4,2)
      IF (N .LT.1) CALL SETERR ('DSVD- N.LT.1',12,5,2)
C/
      IRV1 = ISTKGT(N,4)
      ID = ISTKGT(N,4)
      CALL DC1RSS(M,N,MATU,MATV,MFLAG)
      IF ((.NOT. MATU).OR.(MFLAG.EQ.0))  GO TO 100
      IZ = ISTKGT(N**2,4)
      CALL DG1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,DSTAK(IZ),
     1   A,0,DSTAK(IRV1),DSTAK(ID),MFLAG)
      GOTO 300
 100  CALL DG1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,A,
     1   A,0,DSTAK(IRV1),DSTAK(ID),MFLAG)
 300  IERR = NERROR(NERR)
      IF (IERR.LE.10) GOTO 200
         CALL ERROFF
C/6S
C        CALL SETERR(34HDSVD- NO CONVERGENCE AFTER 30 ITER,
C    1   34,IERR,1)
C/7S
         CALL SETERR('DSVD- NO CONVERGENCE AFTER 30 ITER',
     1   34,IERR,1)
C/
 200  CALL LEAVE
      RETURN
      END
