      SUBROUTINE DSVDLS(M,N,A,NAU,U,MATU,W,V,NV,MATV,B,IRHS)
      INTEGER NAU,NV,M,N,IRHS,MFLAG
      INTEGER IRV1, ICD, IZ, IV
      INTEGER ISTKGT,IERR
C/6S
C     DOUBLE PRECISION A(NAU,N),W(N),U(NAU,N),V(NV,N),B(NAU,1)
C/7S
      DOUBLE PRECISION A(NAU,N),W(N),U(NAU,N),V(NV,N),B(NAU,*)
C/
      LOGICAL MATU, MATV
      DOUBLE PRECISION DSTAK(500)
      COMMON /CSTAK/DSTAK
C
      CALL ENTER(0)
C/6S
C     IF (IRHS .LT. 0) CALL SETERR(17HDSVDLS- IRHS.LT.0,17,1,2)
C     IF (M .LT. N) CALL SETERR(14HDSVDLS- M.LT.N,14,2,2)
C     IF (NAU .LT. M) CALL SETERR (16HDSVDLS- NAU.LT.M,16,3,2)
C     IF (NV .LT. N) CALL SETERR (15HDSVDLS- NV.LT.N,15,4,2)
C     IF (M .LT. 1) CALL SETERR (14HDSVDLS- M.LT.1,14,5,2)
C     IF (N .LT.1) CALL SETERR (14HDSVDLS- N.LT.1,14,6,2)
C/7S
      IF (IRHS .LT. 0) CALL SETERR('DSVDLS- IRHS.LT.0',17,1,2)
      IF (M .LT. N) CALL SETERR('DSVDLS- M.LT.N',14,2,2)
      IF (NAU .LT. M) CALL SETERR ('DSVDLS- NAU.LT.M',16,3,2)
      IF (NV .LT. N) CALL SETERR ('DSVDLS- NV.LT.N',15,4,2)
      IF (M .LT. 1) CALL SETERR ('DSVDLS- M.LT.1',14,5,2)
      IF (N .LT.1) CALL SETERR ('DSVDLS- N.LT.1',14,6,2)
C/
      IRV1 = ISTKGT(N,4)
      ICD = ISTKGT(N,4)
      CALL DC1RSS(M,N,MATU,MATV,MFLAG)
      IF ((IRHS .GT. 0) .AND. (.NOT.MATV)) GO TO 180
      IF ((.NOT. MATU) .OR. (MFLAG .EQ. 0)) GO TO 170
          IZ = ISTKGT(N**2,4)
          CALL DG1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,DSTAK(IZ),B,
     1       IRHS,DSTAK(IRV1),DSTAK(ICD),MFLAG)
      GO TO 190
 170  CALL DG1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,A,B,
     1   IRHS,DSTAK(IRV1),DSTAK(ICD),MFLAG)
      GO TO 190
 180  IV = ISTKGT(N**2,4)
      IF ((.NOT. MATU) .OR. (MFLAG .EQ. 0)) GO TO 185
          IZ = ISTKGT(N**2,4)
          CALL DG1SVD(NAU,N,M,N,A,W,MATU,U,.TRUE.,DSTAK(IV),DSTAK(IZ),B,
     1       IRHS,DSTAK(IRV1),DSTAK(ICD),MFLAG)
      GO TO 190
 185  CALL DG1SVD(NAU,N,M,N,A,W,MATU,U,.TRUE.,DSTAK(IV),A,B,
     1   IRHS,DSTAK(IRV1),DSTAK(ICD),MFLAG)
 190  IERR = NERROR(NERR)
      IF (IERR.LE.10) GOTO 200
         CALL ERROFF
C/6S
C        CALL SETERR(36HDSVDLS- NO CONVERGENCE AFTER 30 ITER,
C    1   35,IERR,1)
C/7S
         CALL SETERR('DSVDLS- NO CONVERGENCE AFTER 30 ITER',
     1   35,IERR,1)
C/
         GO TO 210
 200  IF ((IRHS .GT. 0) .AND. (.NOT. MATV)) GO TO 205
         IF (IRHS .GT. 0) CALL DC2LSQ(DSTAK(ICD),W,B,V,N,M,IRHS,NAU)
         GO TO 210
 205  CALL DC2LSQ(DSTAK(ICD),W,B,DSTAK(IV),N,M,IRHS,NAU)
 210  CALL LEAVE
      RETURN
      END
