      SUBROUTINE DSYCE(N, C, INTER, COND)
      INTEGER N
      INTEGER INTER(N)
      DOUBLE PRECISION C(1), COND
      COMMON /CSTAK/ D
      DOUBLE PRECISION D(500)
      INTEGER IZ, IERR, ISTKGT, NERROR
      DOUBLE PRECISION ANORM, D1MACH, DSYNM
C SYMMETRIC CONDITION ESTIMATION
C INPUT PARMETERS
C N          NUMBER OF ROWS IN A
C C       VECTOR INTO WHICH THE SYMMETRIC MATRIX A IS
C         PACKED BY COLUMNS ACCORDING TO THE FOLLOWING
C         TEMPLATE
C            1
C            2  5
C            3  6  8
C            4  7  9  10
C OUTPUT PARAMETERS
C C          MDM(TRANSPOSE) DECOMPOSITION SUITABLE AS INPUT
C            INTO DSYFBS
C INTER      INTEGER ARRAY OF LENGTH N OF INTERCHANGES PERFORMED
C            DURING DECOMPOSITION
C            SUITABLE OF INPUT INTO SYFBS
C COND       LOWER BOUND ON THE CONDITION NUMBER OF A
C STORAGE ALLOCATED- N DOUBLE PRECISION LOCATIONS
C ERROR CONDITIONS
C 1          N.LT.1
C/6S
C     IF (N .LT. 1) CALL SETERR(12HDSYCE-N.LT.1, 12, 1, 2)
C/7S
      IF (N .LT. 1) CALL SETERR('DSYCE-N.LT.1', 12, 1, 2)
C/
      CALL ENTER(1)
      ANORM=DSYNM(N,C)
      CALL DSYMD(N, C, INTER,0.D0)
      IF (NERROR(IERR) .EQ. 0) GOTO 1
         COND = D1MACH(2)
         CALL LEAVE
         RETURN
   1  IZ = ISTKGT(N, 4)
      CALL DS4YCE(N, C, COND, INTER, ANORM, D(IZ))
      CALL LEAVE
      RETURN
      END
