       SUBROUTINE DSYDC(N,A,INTER)
C THIS SUBROUTINE DOES THE SYMMETRIC DECOMPOSITION
C ALGORITHM OF BUNCH AND KAUFMAN ON A MATRIX
C A STORED AS A 1 DIMENSION ARRAY
C INPUT PARAMETERS
C
C N        ORDER OF THE MATRIX
C A        AN N X(N+1)/2 VECTOR CONTAINING THE COEFFICIENT
C          MATRIX STORED BY COLUMNS IN THE ORDER
C             1
C             2  5
C             3  6  8
C             4  7  9 10
C OUTPUT PARAMETERS
C A       THE DECOMPOSED MATRIX
C INTER     A RECORD OF THE INTERCHANGES PERFORMED
C ERROR SITUATIONS
C 1     N.LT.1    FATAL
C 2     10+K       SINGULAR MATRIX OF RANK K
          DOUBLE PRECISION A(1),DSYNM,EPS
          DOUBLE PRECISION D1MACH
          INTEGER INTER(N)
          CALL ENTER(1)
C/6S
C         IF(N.LT.1) CALL SETERR(12HDSYDC-N.LT.1,12,1,2)
C/7S
          IF(N.LT.1) CALL SETERR('DSYDC-N.LT.1',12,1,2)
C/
C COMPUTE NORM OF THE MATRIX
          EPS=D1MACH(4)*DSYNM(N,A)
          CALL DSYMD(N,A,INTER,EPS)
C/6S
C         IF (NERROR(IER).NE.0)
C    1      CALL N5ERR(21HDSYDC-SINGULAR MATRIX,21,IER,1)
C/7S
          IF (NERROR(IER).NE.0)
     1      CALL N5ERR('DSYDC-SINGULAR MATRIX',21,IER,1)
C/
          CALL LEAVE
          RETURN
          END
