      SUBROUTINE LTSQ(M,N,A,NA,B,IRHS,W)
      INTEGER NA,M,N,IRHS,MFLAG
      INTEGER ISTKGT,IERR
      INTEGER IRV1, ICD, IV
      REAL A(NA,N),B(NA,IRHS),W(N)
      LOGICAL MATU, MATV
      DOUBLE PRECISION DSTAK(500)
      REAL RSTAK(1000)
      COMMON /CSTAK/DSTAK
      EQUIVALENCE(DSTAK(1),RSTAK(1))
C
      CALL ENTER(0)
C/6S
C     IF (IRHS .LT. 0) CALL SETERR(15HLTSQ  IRHS.LT.0,15,1,2)
C     IF (M .LT. N) CALL SETERR(12HLTSQ  M.LT.N,12,2,2)
C     IF (NA .LT. M) CALL SETERR (13HLTSQ  NA.LT.M,13,3,2)
C     IF (M .LT. 1) CALL SETERR (12HLTSQ  M.LT.1,12,4,2)
C     IF (N .LT.1) CALL SETERR (12HLTSQ  N.LT.1,12,5,2)
C/7S
      IF (IRHS .LT. 0) CALL SETERR('LTSQ  IRHS.LT.0',15,1,2)
      IF (M .LT. N) CALL SETERR('LTSQ  M.LT.N',12,2,2)
      IF (NA .LT. M) CALL SETERR ('LTSQ  NA.LT.M',13,3,2)
      IF (M .LT. 1) CALL SETERR ('LTSQ  M.LT.1',12,4,2)
      IF (N .LT.1) CALL SETERR ('LTSQ  N.LT.1',12,5,2)
C/
      IRV1 = ISTKGT(N,3)
      ICD = ISTKGT(N,3)
      IV = ISTKGT(N**2,3)
      MATV = .TRUE.
      MATU = .FALSE.
      CALL C1RSS(M,N,MATU,MATV,MFLAG)
      CALL G1SVD(NA,N,M,N,A,W,MATU,A,MATV,RSTAK(IV),
     1   A,B,IRHS,RSTAK(IRV1),RSTAK(ICD),MFLAG)
      IERR = NERROR(NERR)
      IF (IERR.LE.10) GOTO 200
         CALL ERROFF
C/6S
C        CALL SETERR(34HLTSQ  NO CONVERGENCE AFTER 30 ITER,
C    1      34,IERR,1)
C/7S
         CALL SETERR('LTSQ  NO CONVERGENCE AFTER 30 ITER',
     1      34,IERR,1)
C/
         GO TO 210
C
 200  CALL C2LSQ(RSTAK(ICD),W,B,RSTAK(IV),N,M,IRHS,NA)
 210  CALL LEAVE
      RETURN
      END
