      SUBROUTINE SVD(M,N,A,NAU,U,MATU,W,V,NV,MATV)
      INTEGER NAU,NV,M,N,MFLAG
      INTEGER ISTKGT,IERR
      INTEGER ID, IRV1, IZ
      REAL A(NAU,N),W(N),U(NAU,N),V(NV,N)
      LOGICAL MATU, MATV
      DOUBLE PRECISION DSTAK(500)
      REAL RSTAK(1000)
      COMMON /CSTAK/DSTAK
      EQUIVALENCE(DSTAK(1),RSTAK(1))
C
      CALL ENTER(0)
C/6S
C     IF (M .LT. N) CALL SETERR(11HSVD- M.LT.N,11,1,2)
C     IF (NAU .LT. M) CALL SETERR (13HSVD- NAU.LT.M,13,2,2)
C     IF (NV .LT. N) CALL SETERR (12HSVD- NV.LT.N,12,3,2)
C     IF (M .LT. 1) CALL SETERR (11HSVD- M.LT.1,11,4,2)
C     IF (N .LT.1) CALL SETERR (11HSVD- N.LT.1,11,5,2)
C/7S
      IF (M .LT. N) CALL SETERR('SVD- M.LT.N',11,1,2)
      IF (NAU .LT. M) CALL SETERR ('SVD- NAU.LT.M',13,2,2)
      IF (NV .LT. N) CALL SETERR ('SVD- NV.LT.N',12,3,2)
      IF (M .LT. 1) CALL SETERR ('SVD- M.LT.1',11,4,2)
      IF (N .LT.1) CALL SETERR ('SVD- N.LT.1',11,5,2)
C/
      IRV1 = ISTKGT(N,3)
      ID = ISTKGT(N,3)
      CALL C1RSS(M,N,MATU,MATV,MFLAG)
      IF ((.NOT. MATU).OR.(MFLAG.EQ.0))  GO TO 100
      IZ = ISTKGT(N**2,3)
      CALL G1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,RSTAK(IZ),
     1   A,0,RSTAK(IRV1),RSTAK(ID),MFLAG)
      GOTO 300
 100  CALL G1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,A,
     1   A,0,RSTAK(IRV1),RSTAK(ID),MFLAG)
 300  IERR = NERROR(NERR)
      IF (IERR.LE.10) GOTO 200
         CALL ERROFF
C/6S
C        CALL SETERR(33HSVD- NO CONVERGENCE AFTER 30 ITER,
C    1   33,IERR,1)
C/7S
         CALL SETERR('SVD- NO CONVERGENCE AFTER 30 ITER',
     1   33,IERR,1)
C/
 200  CALL LEAVE
      RETURN
      END
