      SUBROUTINE SVDLS(M,N,A,NAU,U,MATU,W,V,NV,MATV,B,IRHS)
      INTEGER NAU,NV,M,N,IRHS,MFLAG
      INTEGER IRV1, ICD, IZ, IV
      INTEGER ISTKGT,IERR
C/6S
C     REAL A(NAU,N),W(N),U(NAU,N),V(NV,N),B(NAU,1)
C/7S
      REAL A(NAU,N),W(N),U(NAU,N),V(NV,N),B(NAU,*)
C/
      LOGICAL MATU, MATV
      DOUBLE PRECISION DSTAK(500)
      REAL RSTAK(1000)
      COMMON /CSTAK/DSTAK
      EQUIVALENCE(DSTAK(1),RSTAK(1))
C
      CALL ENTER(0)
C/6S
C     IF (IRHS .LT. 0) CALL SETERR(16HSVDLS- IRHS.LT.0,16,1,2)
C     IF (M .LT. N) CALL SETERR(13HSVDLS- M.LT.N,13,2,2)
C     IF (NAU .LT. M) CALL SETERR (15HSVDLS- NAU.LT.M,15,3,2)
C     IF (NV .LT. N) CALL SETERR (14HSVDLS- NV.LT.N,14,4,2)
C     IF (M .LT. 1) CALL SETERR (13HSVDLS- M.LT.1,13,5,2)
C     IF (N .LT.1) CALL SETERR (13HSVDLS- N.LT.1,13,6,2)
C/7S
      IF (IRHS .LT. 0) CALL SETERR('SVDLS- IRHS.LT.0',16,1,2)
      IF (M .LT. N) CALL SETERR('SVDLS- M.LT.N',13,2,2)
      IF (NAU .LT. M) CALL SETERR ('SVDLS- NAU.LT.M',15,3,2)
      IF (NV .LT. N) CALL SETERR ('SVDLS- NV.LT.N',14,4,2)
      IF (M .LT. 1) CALL SETERR ('SVDLS- M.LT.1',13,5,2)
      IF (N .LT.1) CALL SETERR ('SVDLS- N.LT.1',13,6,2)
C/
      IRV1 = ISTKGT(N,3)
      ICD = ISTKGT(N,3)
      CALL C1RSS(M,N,MATU,MATV,MFLAG)
      IF ((IRHS .GT. 0) .AND. (.NOT.MATV)) GO TO 180
      IF ((.NOT. MATU) .OR. (MFLAG .EQ. 0)) GO TO 170
          IZ = ISTKGT(N**2,3)
          CALL G1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,RSTAK(IZ),B,
     1       IRHS,RSTAK(IRV1),RSTAK(ICD),MFLAG)
      GO TO 190
 170  CALL G1SVD(NAU,NV,M,N,A,W,MATU,U,MATV,V,A,B,
     1   IRHS,RSTAK(IRV1),RSTAK(ICD),MFLAG)
      GO TO 190
 180  IV = ISTKGT(N**2,3)
      IF ((.NOT. MATU) .OR. (MFLAG .EQ. 0)) GO TO 185
          IZ = ISTKGT(N**2,3)
          CALL G1SVD(NAU,N,M,N,A,W,MATU,U,.TRUE.,RSTAK(IV),RSTAK(IZ),B,
     1       IRHS,RSTAK(IRV1),RSTAK(ICD),MFLAG)
      GO TO 190
 185  CALL G1SVD(NAU,N,M,N,A,W,MATU,U,.TRUE.,RSTAK(IV),A,B,
     1   IRHS,RSTAK(IRV1),RSTAK(ICD),MFLAG)
 190  IERR = NERROR(NERR)
      IF (IERR.LE.10) GOTO 200
         CALL ERROFF
C/6S
C        CALL SETERR(35HSVDLS- NO CONVERGENCE AFTER 30 ITER,
C    1   35,IERR,1)
C/7S
         CALL SETERR('SVDLS- NO CONVERGENCE AFTER 30 ITER',
     1   35,IERR,1)
C/
         GO TO 210
 200  IF ((IRHS .GT. 0) .AND. (.NOT. MATV)) GO TO 205
         IF (IRHS .GT. 0) CALL C2LSQ(RSTAK(ICD),W,B,V,N,M,IRHS,NAU)
         GO TO 210
 205  CALL C2LSQ(RSTAK(ICD),W,B,RSTAK(IV),N,M,IRHS,NAU)
 210  CALL LEAVE
      RETURN
      END
