      SUBROUTINE B1RM1(NPTS, X, FN, MAXITR, ITOL, M, N, P, Q,
     1   DELK, NEWP, NEWQ, EN, QK, IEXT)
      INTEGER NPTS
      INTEGER MAXITR, ITOL, M, N, IEXT(NPTS)
      REAL X(NPTS), FN(NPTS), P(1), Q(1), DELK, NEWP(1)
      REAL NEWQ(1), EN(NPTS), QK(NPTS)
      INTEGER NITR, NEX, IMAX, IMIN, ILRG, L5RGXR
      INTEGER NERROR, IER, I
      REAL EPS, BND, R1MACH, DELNEW, ABS
      EPS = R1MACH(4)*10.0E0**ITOL
      CALL EXTRMR(NPTS, FN, NEX, IEXT, IMAX, IMIN, ILRG)
      BND = ABS(FN(ILRG))*EPS
      CALL C5EQK(NPTS, X, FN, M, N, P, Q, QK, EN)
      DO  1 I = 1, NPTS
C/6S
C        IF (QK(I) .LE. 0.0E0) CALL SETERR(
C    1      35HBURM1  - DENOMINATOR IS NONPOSITIVE, 35, 6, 2)
C/7S
         IF (QK(I) .LE. 0.0E0) CALL SETERR(
     1      'BURM1  - DENOMINATOR IS NONPOSITIVE', 35, 6, 2)
C/
   1     CONTINUE
      CALL EXTRMR(NPTS, EN, NEX, IEXT, IMAX, IMIN, ILRG)
      DELK = ABS(EN(ILRG))
      DELNEW = DELK
      CALL MOVEFR(M+1, P, NEWP)
      CALL MOVEFR(N+1, Q, NEWQ)
      NITR = 0
         GOTO  3
   2     NITR = NITR+1
   3     IF (NITR .GE. MAXITR) GOTO  6
C   OUTPT3 (X,NPTS,P,Q,DELK,M,N,EN,IEXT,NEX)
         IF (DELK .GT. BND) GOTO 4
C/6S
C           CALL SETERR(38HBURM1  - APPROXIMATION EQUALS FUNCTION, 39, 7
C    1         , 1)
C/7S
            CALL SETERR('BURM1  - APPROXIMATION EQUALS FUNCTION', 39, 7
     1         , 1)
C/
            RETURN
C   TEST FOR OPTIMAL SOLUTION.
   4     IF (L5RGXR(NPTS, EN, NEX, IEXT, ILRG, ITOL) .GE. M+N+2) RETURN
         CALL L5STP(NPTS, X, FN, QK, DELNEW, M, N, NEWP, NEWQ)
         IF (NERROR(IER) .NE. 0) CALL ERROFF
         CALL C5EQK(NPTS, X, FN, M, N, NEWP, NEWQ, QK, EN)
         CALL EXTRMR(NPTS, EN, NEX, IEXT, IMAX, IMIN, ILRG)
         DELNEW = ABS(EN(ILRG))
         IF (DELK .GT. DELNEW) GOTO 5
C/6S
C           CALL SETERR(40HBURM1  - NO IMPROVEMENT IN APPROXIMATION, 40,
C    1         8, 1)
C/7S
            CALL SETERR('BURM1  - NO IMPROVEMENT IN APPROXIMATION', 40,
     1         8, 1)
C/
            RETURN
   5     CALL MOVEFR(M+1, NEWP, P)
         CALL MOVEFR(N+1, NEWQ, Q)
         DELK = DELNEW
         GOTO  2
C/6S
C  6  CALL SETERR(42HBURM1  - REACHED MAXIMUM NO. OF ITERATIONS, 42, 9
C    1   , 1)
C/7S
   6  CALL SETERR('BURM1  - REACHED MAXIMUM NO. OF ITERATIONS', 42, 9
     1   , 1)
C/
      RETURN
      END
