      SUBROUTINE C2SPFT(X,Y,YP,YPP,N,XX,YY,YYP,YYPP)
      DIMENSION X(N),Y(N),YP(N),YPP(N)
C
C USING ALREADY-FIT CUBIC SPLINE TO N DATA PAIRS (X,Y)
C INTERPOLATE AT XX TO GET VALUE AND FIRST TWO DERIVATIVES.
C YP AND YPP, FITTED SPLINE PARAMETERS, ARE FIRST TWO DERIVATIVES
C AT THE DATA POINTS.
C
       N1=N-1
C
C FIND THE CORRECT INTERVAL.  ASSUME X(1) .LE. XX .LE. X(N).
C
       J=INTRVR(N,X,XX)
C
       H=X(J+1)-X(J)
       XP=(X(J+1)-XX)/H
       XM=(XX-X(J))/H
       YY=Y(J)*XP+Y(J+1)*XM -H**2*(YPP(J)*XP*(1.-XP**2)+
     1             YPP(J+1)*XM*(1.-XM**2))/6.0
       YYP=YP(J)+.5*H*(YPP(J)*(1.-XP**2)+YPP(J+1)*XM**2)
       YYPP=YPP(J)*XP+YPP(J+1)*XM
C
       RETURN
       END
