      SUBROUTINE C5DRP(M, N, Q, R, INDEX)
      INTEGER M
      INTEGER N, INDEX
      REAL Q(M, M), R(M, 1)
      INTEGER J, I
      REAL ALFA, BETA
C   IF A IS AN MXN MATRIX DEFINED BY QA = R, WHERE Q IS
C   AN ORTHOGONAL MATRIX AND R IS A RIGHT TRIANGULAR MATRIX,
C   THEN THIS PROCEDURE OBTAINS THE Q(T)R FACTORIZATION
C   OF THE MATRIX DETERMINED BY DELETING A COLUMN OF A.
C   THIS NEW FACTORIZATION IS OBTAINED BY AN EFFICIENT UPDATE
C   PROCESS.
C   INPUT-
C   M      - THE COLUMN DIMENSION OF Q AND R.
C   N      - THE ROW DIMENSION OF R (N .LE. M).
C   Q      - AN MXM ORTHOGONAL MATRIX.
C   R      - AN MXN RIGHT TRIANGULAR MATRIX.
C   INDEX  - THE INDEX OF THE COLUMN TO BE DELETED.
C   OUTPUT-
C   N      - THE NEW ROW DIMENSION OF R.
C   Q      - THE NEW ORTHOGONAL MATRIX.
C   R      - THE NEW RIGHT TRIANGULAR MATRIX.
C/6S
C     IF (M .LE. 0 .OR. N .LE. 0 .OR. M .LT. N) CALL SETERR(
C    1   26HC5DRP  - INVALID DIMENSION, 26, 1, 2)
C     IF (INDEX .LE. 0 .OR. N .LT. INDEX) CALL SETERR(
C    1   22HC5DRP  - INVALID INDEX, 22, 2, 2)
C/7S
      IF (M .LE. 0 .OR. N .LE. 0 .OR. M .LT. N) CALL SETERR(
     1   'C5DRP  - INVALID DIMENSION', 26, 1, 2)
      IF (INDEX .LE. 0 .OR. N .LT. INDEX) CALL SETERR(
     1   'C5DRP  - INVALID INDEX', 22, 2, 2)
C/
      J = INDEX+1
         GOTO  2
   1     J = J+1
   2     IF (J .GT. N) GOTO  3
         CALL MOVEFR(J, R(1, J), R(1, J-1))
         GOTO  1
   3  N = N-1
      I = INDEX
         GOTO  5
   4     I = I+1
   5     IF (I .GT. N) GOTO  6
         CALL SROTG(R(I, I), R(I+1, I), ALFA, BETA)
         CALL SROT(N-I, R(I, I+1), M, R(I+1, I+1), M, ALFA, BETA)
         CALL SROT(M, Q(I, 1), M, Q(I+1, 1), M, ALFA, BETA)
         GOTO  4
   6  RETURN
      END
