      SUBROUTINE CSPFE(X,Y,YP,YPP,N,XX,YY,NN)
      REAL X(N),Y(N),YP(N),YPP(N),XX(NN),YY(NN)
C
C INPUTS
C N DATA PAIRS (X,Y)
C SPLINE DATA YP,YPP AS DONE BY CSPFIT, FOR EXAMPLE
C NN DATA POINTS XX AT WHICH TO INTERPOLATE
C
C OUTPUT
C INTERPOLATED VALUE OF SPLINE AT XX POINTS
C
C/6S
C     IF (N.LT.2) CALL SETERR(
C    *      34H CSPFE - MUST HAVE MORE THAN ONE X,34,1,2)
C/7S
      IF (N.LT.2) CALL SETERR(
     *      ' CSPFE - MUST HAVE MORE THAN ONE X',34,1,2)
C/
C
      N1=N-1
      DO 10 J=1,N1
C/6S
C  10    IF (X(J).GE.X(J+1)) CALL SETERR(
C    *      44H CSPFE - X ARRAY MUST BE IN INCREASING ORDER,44,2,2)
C/7S
   10    IF (X(J).GE.X(J+1)) CALL SETERR(
     *      ' CSPFE - X ARRAY MUST BE IN INCREASING ORDER',44,2,2)
C/
C
C/6S
C     IF (NN.LT.1) CALL SETERR(16H CSPFE - NN.LT.1,16,3,2)
C/7S
      IF (NN.LT.1) CALL SETERR(' CSPFE - NN.LT.1',16,3,2)
C/
      DO 20 J=1,NN
   20    CALL C2SPFT(X,Y,YP,YPP,N,XX(J),YY(J),YYP,YYPP)
C
      RETURN
      END
