      SUBROUTINE CSPFI(X,Y,N,B,YP,YPP)
       DIMENSION X(N),Y(N),B(6),YP(N),YPP(N)
C
C INPUTS
C N DATA PAIRS (X,Y)
C B IS BOUNDARY CONDITION MATRIX
C
C      B(1)*YP(1) + B(2)*YPP(1) = B(3) AT X(1)
C      B(4)*YP(N) + B(5)*YPP(N) = B(6) AT X(N)
C
C WHERE
C YP AND YPP ARE THE DERIVATIVES OF THE FITTED CUBIC SPLINE
C XX IS ARRAY OF VALUES AT WHICH TO INTERPOLATE
C NN IS NUMBER OF XX-VALUES
C
C OUTPUT
C CUBIC SPLINE FIT TO Y(X).
C PARAMETER VECTORS, YP AND YPP AT DATA POINTS, ARE RETURNED.
C
       COMMON/CSTAK/D
       DOUBLE PRECISION D(500)
       REAL R(1000)
       EQUIVALENCE (D(1),R(1))
C
C CHECK FOR ERRORS IN INPUT
C
C/6S
C      IF (N.LT.2)   CALL SETERR(
C    1   33HCSPFI - MUST HAVE MORE THAN ONE X,33,1,2)
C/7S
       IF (N.LT.2)   CALL SETERR(
     1   'CSPFI - MUST HAVE MORE THAN ONE X',33,1,2)
C/
C
       N1=N-1
       DO 10 J=1,N1
C/6S
C  10  IF (X(J).GE.X(J+1))   CALL SETERR(
C    1    43HCSPFI - X ARRAY MUST BE IN INCREASING ORDER,43,2,2)
C/7S
   10  IF (X(J).GE.X(J+1))   CALL SETERR(
     1    'CSPFI - X ARRAY MUST BE IN INCREASING ORDER',43,2,2)
C/
C
C/6S
C      IF (AMAX1(ABS(B(1)),ABS(B(2))).LE.0.0)  CALL SETERR(
C    1    41HCSPFI - B(1) AND B(2) CANNOT BOTH BE ZERO,41,3,2)
C/7S
       IF (AMAX1(ABS(B(1)),ABS(B(2))).LE.0.0)  CALL SETERR(
     1    'CSPFI - B(1) AND B(2) CANNOT BOTH BE ZERO',41,3,2)
C/
C
C/6S
C      IF (AMAX1(ABS(B(4)),ABS(B(5))).LE.0.0)  CALL SETERR(
C    1   41HCSPFI - B(4) AND B(5) CANNOT BOTH BE ZERO,41,4,2)
C/7S
       IF (AMAX1(ABS(B(4)),ABS(B(5))).LE.0.0)  CALL SETERR(
     1   'CSPFI - B(4) AND B(5) CANNOT BOTH BE ZERO',41,4,2)
C/
C
C/6S
C      IF (ISTKQU(3) .LT. 4*N) CALL SETERR(
C    1   46HCSPFI - NOT ENOUGH STACK ROOM, USE PORT ISTKIN,46,5,2)
C/7S
       IF (ISTKQU(3) .LT. 4*N) CALL SETERR(
     1   'CSPFI - NOT ENOUGH STACK ROOM, USE PORT ISTKIN',46,5,2)
C/
C
C SET UP THE STACK AND THEN CALL THE ACTUAL FITTING PROCESS
C
       IH=ISTKGT(4*N,3)
       IU=IH+N
       IV=IU+N
       ID=IV+N
C
C TURN RECOVERY ON AND SAVE OLD RECOVERY SWITCH
C
      CALL ENTSRC (IRSAVE, 1)
C
       CALL C1SPFT(X,Y,N,B,YP,YPP,R(IH),R(IU),R(IV),R(ID))
C
      IF (NERROR(NERR) .EQ. 0)  GOTO 30
C
C ERROR 1 IN C1SPFT.
C TURN OFF ERROR STATE AND RESET IT TO
C GIVE A LOCAL ERROR STATE FOR CSPFI.
C
      CALL ERROFF
C/6S
C     CALL SETERR (37HCSPFI - SINGULAR MATRIX. CHECK INPUTS,37,6,2)
C/7S
      CALL SETERR ('CSPFI - SINGULAR MATRIX. CHECK INPUTS',37,6,2)
C/
C
C
   30  CALL RETSRC (IRSAVE)
      CALL ISTKRL(1)
C
       RETURN
       END
