      SUBROUTINE DC5APP(M, N, Q, R, INDEX, B)
      INTEGER M
      INTEGER N, INDEX
      DOUBLE PRECISION Q(M, M), R(M, 1), B(M)
      INTEGER J, I
      DOUBLE PRECISION ALFA, BETA
C   IF A IS AN MXN MATRIX DEFINED BY QA = R, WHERE Q IS
C   AN ORTHOGONAL MATRIX AND R IS A RIGHT TRIANGULAR MATRIX,
C   THEN THIS PROCEDURE OBTAINS THE Q(T)R FACTORIZATION
C   OF THE MATRIX DETERMINED BY APPENDING A COLUMN TO A.
C   THE COLUMN OF A WHICH IS BEING APPENDED IS DEFINED BY
C   Q(T)B.  THIS NEW FACTORIZATION IS OBTAINED BY AN
C   EFFICIENT UPDATE PROCESS.
C   INPUT-
C   M      - THE COLUMN DIMENSION OF Q AND R.
C   N      - THE ROW DIMENSION OF R (N .LT. M).
C   Q      - AN MXM ORTHOGONAL MATRIX.
C   R      - AN MXN RIGHT TRIANGULAR MATRIX.
C   INDEX  - THE INDEX OF THE COLUMN TO BE ENTERED.
C   B      - THE NEW COLUMN.  IF A IS THE NEW COLUMN  OF
C          - THE MATRIX A, THEN  B = QA.
C   OUTPUT-
C   N      - THE NEW ROW DIMENSION OF R.
C   Q      - THE NEW ORTHOGONAL MATRIX.
C   R      - THE NEW RIGHT TRIANGULAR MATRIX.
C/6S
C     IF (M .LE. 0 .OR. N .LT. 0 .OR. M .LE. N) CALL SETERR(
C    1   26HDC5APP - INVALID DIMENSION, 26, 1, 2)
C     IF (INDEX .LE. 0 .OR. N+1 .LT. INDEX) CALL SETERR(
C    1   22HDC5APP - INVALID INDEX, 22, 2, 2)
C/7S
      IF (M .LE. 0 .OR. N .LT. 0 .OR. M .LE. N) CALL SETERR(
     1   'DC5APP - INVALID DIMENSION', 26, 1, 2)
      IF (INDEX .LE. 0 .OR. N+1 .LT. INDEX) CALL SETERR(
     1   'DC5APP - INVALID INDEX', 22, 2, 2)
C/
      J = N
         GOTO  2
   1     J = J-1
   2     IF (INDEX .GT. J) GOTO  3
         CALL MOVEBD(M, R(1, J), R(1, J+1))
         GOTO  1
   3  N = N+1
      CALL MOVEFD(M, B, R(1, INDEX))
      I = M-1
         GOTO  5
   4     I = I-1
   5     IF (INDEX .GT. I) GOTO  6
         CALL DROTG(R(I, INDEX), R(I+1, INDEX), ALFA, BETA)
         CALL DROT(N-INDEX, R(I, INDEX+1), M, R(I+1, INDEX+1), M, ALFA
     1      , BETA)
         CALL DROT(M, Q(I, 1), M, Q(I+1, 1), M, ALFA, BETA)
         GOTO  4
   6  RETURN
      END
