      SUBROUTINE DCSPIN(X,Y,N,XX,YY,NN)
       DOUBLE PRECISION X(N),Y(N),B(6),XX(NN),YY(NN),YYP,YYPP
       DOUBLE PRECISION DC3SPF
C
C INPUTS
C N DATA PAIRS (X,Y)
C XX IS ARRAY OF VALUES AT WHICH TO INTERPOLATE
C NN IS NUMBER OF XX-VALUES
C
C OUTPUT
C CUBIC SPLINE FIT TO Y(X).
C YY(J) IS INTERPOLATED VALUE AT XX(J),J=1,...,NN.
C
       COMMON/CSTAK/D
       DOUBLE PRECISION D(500)
C
C CHECK FOR ERRORS IN INPUT PARAMETERS
C
C/6S
C      IF (NN .LT. 1) CALL SETERR(
C    1    47HDCSPIN - MUST INTERPOLATE AT ONE POINT AT LEAST,47,1,2)
C/7S
       IF (NN .LT. 1) CALL SETERR(
     1    'DCSPIN - MUST INTERPOLATE AT ONE POINT AT LEAST',47,1,2)
C/
C
C/6S
C      IF (N.LT.4)   CALL SETERR(
C    1   36HDCSPIN - MUST HAVE AT LEAST FOUR X S,36,2,2)
C/7S
       IF (N.LT.4)   CALL SETERR(
     1   'DCSPIN - MUST HAVE AT LEAST FOUR X S',36,2,2)
C/
C
       N1 = N-1
       DO 10 J=1,N1
C/6S
C  10  IF (X(J).GE.X(J+1))   CALL SETERR(
C    1    44HDCSPIN - X ARRAY MUST BE IN INCREASING ORDER,44,3,2)
C/7S
   10  IF (X(J).GE.X(J+1))   CALL SETERR(
     1    'DCSPIN - X ARRAY MUST BE IN INCREASING ORDER',44,3,2)
C/
C
       DO 20 K=1,NN
C/6S
C  20  IF (XX(K) .LT.  X(1) .OR. XX(K) .GT. X(N)) CALL SETERR(
C    1    35HDCSPIN -  POINT NOT INSIDE INTERVAL,35,4,2)
C/7S
   20  IF (XX(K) .LT.  X(1) .OR. XX(K) .GT. X(N)) CALL SETERR(
     1    'DCSPIN -  POINT NOT INSIDE INTERVAL',35,4,2)
C/
C
C BOUNDARY CONDITIONS - APPROXIMATE SECOND DERIVATIVES
C
       B(1)=0.
       B(2)=1.
       B(3)=DC3SPF(X(1),Y(1),X(1))
       B(4)=0.
       B(5)=1.
       B(6)=DC3SPF(X(N-3),Y(N-3),X(N))
C
C SPACE FOR PARAMETERS OF SPLINE
C
C/6S
C      IF (ISTKQU(4) .LT. 2*N) CALL SETERR(
C    1   47HDCSPIN - NOT ENOUGH STACK ROOM, USE PORT ISTKIN,47,5,2)
C/7S
       IF (ISTKQU(4) .LT. 2*N) CALL SETERR(
     1   'DCSPIN - NOT ENOUGH STACK ROOM, USE PORT ISTKIN',47,5,2)
C/
       IYP=ISTKGT(2*N,4)
       IYPP=IYP+N
C
C CHECK IF HAVE ENOUGH SPACE FOR CSPFIT
C
C/6S
C      IF (ISTKQU(4) .LT. 4*N) CALL SETERR(
C    1   47HDCSPIN - NOT ENOUGH STACK ROOM, USE PORT ISTKIN,47,5,2)
C/7S
       IF (ISTKQU(4) .LT. 4*N) CALL SETERR(
     1   'DCSPIN - NOT ENOUGH STACK ROOM, USE PORT ISTKIN',47,5,2)
C/
C
C FIT THE SPLINE
C
       CALL DCSPFI(X,Y,N,B,D(IYP),D(IYPP))
C
C DO THE INTERPOLATION
C
       DO 50 J=1,NN
C
   50  CALL DC2SPF(X,Y,D(IYP),D(IYPP),N,XX(J),YY(J),YYP,YYPP)
C
       CALL ISTKRL(1)
       RETURN
       END
