      SUBROUTINE DCSPFE(X,Y,YP,YPP,N,XX,YY,NN)
      DOUBLE PRECISION X(N),Y(N),YP(N),YPP(N),XX(NN),YY(NN),YYP,YYPP
C
C INPUTS
C N DATA PAIRS (X,Y)
C SPLINE DATA YP,YPP AS DONE BY DCSPFI, FOR EXAMPLE
C NN DATA POINTS XX AT WHICH TO INTERPOLATE
C
C OUTPUT
C INTERPOLATED VALUE OF SPLINE AT XX POINTS
C
C/6S
C     IF (N.LT.2) CALL SETERR(
C    *      34HDCSPFE - MUST HAVE MORE THAN ONE X,34,1,2)
C/7S
      IF (N.LT.2) CALL SETERR(
     *      'DCSPFE - MUST HAVE MORE THAN ONE X',34,1,2)
C/
C
      N1=N-1
      DO 10 J=1,N1
C/6S
C  10    IF (X(J).GE.X(J+1)) CALL SETERR(
C    *      44HDCSPFE - X ARRAY MUST BE IN INCREASING ORDER,44,2,2)
C/7S
   10    IF (X(J).GE.X(J+1)) CALL SETERR(
     *      'DCSPFE - X ARRAY MUST BE IN INCREASING ORDER',44,2,2)
C/
C
C/6S
C     IF (NN.LT.1) CALL SETERR(16HDCSPFE - NN.LT.1,16,3,2)
C/7S
      IF (NN.LT.1) CALL SETERR('DCSPFE - NN.LT.1',16,3,2)
C/
      DO 20 J=1,NN
   20    CALL DC2SPF(X,Y,YP,YPP,N,XX(J),YY(J),YYP,YYPP)
C
      RETURN
      END
