      DOUBLE PRECISION FUNCTION DV5MAX(M, A, INDEX)
      INTEGER M
      INTEGER INDEX
      DOUBLE PRECISION A(M)
      INTEGER I
      DOUBLE PRECISION B
C  THIS LONG REAL FUNCTION RETURNS THE LARGEST COMPONENT
C  OF THE LONG REAL VECTOR A.
C/6S
C     IF (M .LT. 1) CALL SETERR(26HDV5MAX - INVALID DIMENSION, 26, 1, 2)
C/7S
      IF (M .LT. 1) CALL SETERR('DV5MAX - INVALID DIMENSION', 26, 1, 2)
C/
      B = A(1)
      INDEX = 1
      DO  2 I = 1, M
         IF (A(I) .LE. B) GOTO 1
            B = A(I)
            INDEX = I
   1     CONTINUE
   2     CONTINUE
      DV5MAX = B
      RETURN
      END
