       SUBROUTINE DVDSS1 (X,N,U,L,A,F,FPRIME)
C DOUBLE PRECISION SPLINE PACKAGE
C DRIVER FOR 1D
C X--POINT AT WHICH SPLINE IS TO BE EVALUATED
C N--NUMBER OF SAMPLES
C U--UPPER BOUND OF INTERVAL
C L--LOWER BOUND OF INTERVAL
C A--SPLINE COEFFICIENTS
C F--FUNCTION
C FPRIME--DERIVATIVE
       INTEGER N,L1,J
       DOUBLE PRECISION X,A(1),F,FPRIME,U,L,X1,DIST
C ERROR CHECKING
C/6S
C      IF (N.LE.0) CALL SETERR(14HDVDSS1- N.LE.0,13,1,2)
C      IF (U.LE.L) CALL SETERR(14HDVDSS1- U.LE.L,13,2,2)
C/7S
       IF (N.LE.0) CALL SETERR('DVDSS1- N.LE.0',13,1,2)
       IF (U.LE.L) CALL SETERR('DVDSS1- U.LE.L',13,2,2)
C/
C SCALE TO INTERVAL, 0,1, (INCLUDING ENDOINTS)
       X1 = X - L
       DIST = U-L
       X1 = X1 / DIST
       L1 = IDINT(DBLE(FLOAT(N-1))*X1 + 0.5D0)
       J = MAX(0,MIN(N-3,L1-1))
C CALL SPLINE ROUTINE
       CALL DT1UED (X1,L1,1,N-1,A(J+1),F,FPRIME)
       FPRIME = FPRIME/DIST
       RETURN
       END
