      SUBROUTINE L5NKD(LLIST, INDEX)
      INTEGER LLIST(2, 1), INDEX
      INTEGER IBACK, INEXT
      INEXT = LLIST(1, INDEX)
      IBACK = LLIST(2, INDEX)
      LLIST(1, IBACK) = INEXT
      LLIST(2, INEXT) = IBACK
      RETURN
      END
