      SUBROUTINE L5NKI(LLIST, INDEX, IBACK)
      INTEGER LLIST(2, 1), INDEX, IBACK
      INTEGER INEXT
      INEXT = LLIST(1, IBACK)
      LLIST(1, IBACK) = INDEX
      LLIST(2, INDEX) = IBACK
      LLIST(1, INDEX) = INEXT
      LLIST(2, INEXT) = INDEX
      RETURN
      END
