      SUBROUTINE LINEQ (N, A, B, NB, X)
C
C SOLUTION OF A SET OF LINEAR EQUATIONS
C
C  METHOD - QR DECOMPOSITION OF A BY HOUSEHOLDER TRANSFORMATIONS
C           FOLLOWED BY BACK SUBSTITUTION
C
C  INPUT
C
C    N    - THE NUMBER OF EQUATIONS
C    A    - THE MATRIX
C    B    - THE RIGHT-HAND SIDES
C    NB   - THE NUMBER OF RIGHT-HAND SIDES
C
C  OUTPUT
C
C    A - CLOBBERED
C    B - CLOBBERED
C    X - THE SOLUTION VECTORS
C
C  ERROR STATES -
C
C    1 - N.LT.1
C    2 - NB.LT.1
C    3 - A IS SINGULAR (RECOVERABLE)
C
      DIMENSION A(N,N),B(N,NB),X(N,NB)
C
C   SAVE AND TURN ON RECOVERY SWITCH
C
       CALL ENTSRC(IRSAVE, 1)
C
C ... CHECK THE INPUT.
C
C/6S
C     IF (N.LT.1) CALL SETERR(14HLINEQ - N.LT.1,14,1,2)
C/7S
      IF (N.LT.1) CALL SETERR('LINEQ - N.LT.1',14,1,2)
C/
C
C/6S
C     IF (NB.LT.1) CALL SETERR(15HLINEQ - NB.LT.1,15,2,2)
C/7S
      IF (NB.LT.1) CALL SETERR('LINEQ - NB.LT.1',15,2,2)
C/
C
C ... CALL LSTSQ TO GET THE SOLUTION
C
      CALL LSTSQ(N,N,N,N,A,B,NB,X)
C
      IF (NERROR(NERR).EQ.0) GO TO 10
C
C ... SINGULAR MATRIX
C
      CALL ERROFF
C/6S
C     CALL SETERR(21HLINEQ - A IS SINGULAR,21,3,1)
C/7S
      CALL SETERR('LINEQ - A IS SINGULAR',21,3,1)
C/
C
 10   CALL RETSRC(IRSAVE)
      RETURN
      END
