      SUBROUTINE LPPH2(A, M, N, AMAN, B, C, X, MAXITR, CTX)
      INTEGER M, N
      EXTERNAL AMAN
      INTEGER MAXITR
      REAL A(1), B(M), C(N), X(N), CTX
      COMMON /CSTAK/ DSTAK
      DOUBLE PRECISION DSTAK(500)
      INTEGER WPTR, QPTR, LTPTR, PPTR, VPTR, SCLPTR
      INTEGER LSTPTR, ISTAK(1000), ISTKGT
      REAL WS(500)
      EQUIVALENCE (DSTAK(1), ISTAK(1))
      EQUIVALENCE (DSTAK(1), WS(1))
C   LPPH2 IS A REAL PROCEDURE FOR SOLVING
C   PHASE 2 OF A LINEAR PROGRAMMING PROBLEM.
C   SPECIFICALLY, THIS ROUTINE FINDS A VECTOR X WHICH
C   SOLVES THE CANONICAL PROBLEM
C                   MAXIMIZE     C(T)X
C                   SUBJECT TO   AX .GE. B
C
C   THIS ROUTINE STARTS WITH A VECTOR X WHICH IS ALREADY
C   FEASIBLE, THAT IS WHICH SATISFIES THE CONSTRAINTS.
C   THE ALGORITHM IS A GENERALIZATION OF THE STEEPEST EDGE SIMPLEX
C   ALGORITHM.  AN IMPORTANT FEATURE OF THIS PACKAGE WITH
C   RESPECT TO NUMERICAL STABILITY IS THAT THE BASIS MATRIX IS
C   FACTORED INTO THE PRODUCT OF A LEFT TRIANGULAR MATRIX TIMES
C   AN ORTHOGONAL MATRIX.  THIS FACTORIZATION IS UPDATED AT EACH
C   PIVOT BY AN O(N**2) ALGORITHM USING GIVENS ROTATIONS.
C   INPUT-
C   A      - THE CONSTRAINT MATRIX.
C   M      - THE ROW DIMENSION OF A.
C   N      - THE COLUMN DIMENSION OF A.  NOTE THAT N MUST BE
C            LESS THAN OR EQUAL TO M.
C   AMAN   - A PROCEDURE THAT MANIPULATES THE MATRIX A.
C              SINCE ALL REFERENCES TO THE MATRIX A ARE VIA AMAN,
C              THE USER MAY USE ANY DATA STRUCTURE FOR REPRESENTING
C              A THAT EXPLOITS ANY SPARSITY.  IN THE EVENT THAT A
C              IS STORED AS AN M BY N MATRIX, A DEFAULT PROCEDURE
C              LPMAN  MAY BE USED.
C   B      - THE RIGHT HAND SIDE.
C   C      - THE COST FUNCTIONAL.
C   X      - AN INITIAL APPROXIMATION TO THE SOLUTION.
C            THIS INITIAL VECTOR MUST BE FEASIBLE, THAT IS
C            AX .GE. B  MUST BE TRUE.
C   MAXITR - THE MAXIMUM NUMBER OF ALLOWABLE ITERATIONS.
C            EXPERIANCE INDICATES THAT WELL BEHAVED PROBLEMS
C            ARE SOLVED WITH FEWER THAN 3*M ITERATIONS.
C   OUTPUT-
C   X      - THE SOLUTION.
C   CTX    - THE VALUE OF THE COST FUNCTIONAL EVALUATED AT X.
      CALL ENTER(1)
C/6S
C     IF (M .LE. 0 .OR. N .LE. 0) CALL SETERR(
C    1   25HLPPH2 - INVALID DIMENSION, 26, 1, 2)
C     IF (M .LT. N) CALL SETERR(25HLPPH2 - INVALID DIMENSION, 26, 2, 2)
C/7S
      IF (M .LE. 0 .OR. N .LE. 0) CALL SETERR(
     1   'LPPH2 - INVALID DIMENSION', 26, 1, 2)
      IF (M .LT. N) CALL SETERR('LPPH2 - INVALID DIMENSION', 26, 2, 2)
C/
C   ALLOCATE THE WORKING STORAGE.
      WPTR = ISTKGT(M, 3)
      QPTR = ISTKGT(N**2, 3)
      LTPTR = ISTKGT(N**2, 3)
      PPTR = ISTKGT(N, 3)
      VPTR = ISTKGT(M, 3)
      SCLPTR = ISTKGT(M, 3)
      LSTPTR = ISTKGT(2*M+2, 2)
      CALL L9PH2(A, M, N, AMAN, B, C, X, MAXITR, CTX, WS(WPTR), WS(QPTR)
     1   , WS(LTPTR), WS(PPTR), WS(VPTR), WS(SCLPTR), ISTAK(LSTPTR))
      CALL LEAVE
      RETURN
      END
