      SUBROUTINE M5TOP(M, N, B, ILO, IHI, JLO, JHI, X, IOP, Y)
      INTEGER M, N
      INTEGER ILO, IHI, JLO, JHI, IOP
      REAL B(M, N), X(1), Y(1)
      COMMON /CSTAK/ DSTAK
      DOUBLE PRECISION DSTAK(500)
      INTEGER MM, HPTR, ISTAK(1000), ISTKGT
      REAL WS(500)
      EQUIVALENCE (DSTAK(1), ISTAK(1))
      EQUIVALENCE (DSTAK(1), WS(1))
C   THIS PROCEDURE PERFORMS THE FOLLOWING MATRIX VECTOR COMPUTATIONS
C   CASE 1-  Y = CX,
C   CASE 2-  Y = C(T)X,
C   CASE 3-  Y = RX,
C   CASE 4-  Y = R(-1)X.
C   THE MATRIX C IS THE RECTANGULAR SUBMATRIX OF B SPECIFIED
C   BY ILO,IHI,JLO, AND JHI.  THE MATRIX R IS THE RIGHT TRIANGULAR
C   SUBMATRIX OF B SPECIFIED BY THE SAME INDICES.  THE RIGHT TRIANGULAR
C   SUBMATRIX MUST BE SQUARE AND CENTERED.
C   INPUT-
C   M      - THE COLUMN DIMENSION OF THE MATRIX.
C   N      - THE ROW DIMENSION OF THE MATRIX.
C   B      - AN MXN MATRIX
C   ILO    - THE SMALLER RWO INDEX.
C   IHI    - THE LARGER ROW INDEX.
C   JLO    - THE SMALLER COLUMN INDEX.
C   JHI    - THE LARGER COLUMN INDEX.
C   X      - A VECTOR OF LENGTH N FOR CASES 1, 3 AND 4, AND
C            A VECTOR OF LENGTH M FOR CASE 2.
C   IOP    - AN INDEX FOR THE MATRIX VECTOR OPERATION TO BE
C            PERFORMED.
C   OUTPUT-
C   Y      - A VECTOR OF LENGTH M FOR CASES 1, 3 AND 4, AND
C            A VECTOR OF LENGTH N FOR CASE 2.  THE PROGRAM
C            IS ORGANIZED SO THAT X AND Y MAY SHARE THE SAME
C            STORAGE.
      CALL ENTER(0)
C/6S
C     IF (M .LE. 0 .OR. N .LE. 0) CALL SETERR(
C    1   26HM5TOP  - INVALID DIMENSION, 26, 2, 2)
C     IF (IHI .LT. ILO .OR. JHI .LT. JLO) CALL SETERR(
C    1   24HM5TOP  - INVALID INDICES, 24, 3, 2)
C     IF (ILO .LT. 1 .OR. M .LT. IHI .OR. JLO .LT. 1 .OR. N .LT. JHI)
C    1   CALL SETERR(26HM5TOP  - INVALID SUBMATRIX, 26, 4, 2)
C/7S
      IF (M .LE. 0 .OR. N .LE. 0) CALL SETERR(
     1   'M5TOP  - INVALID DIMENSION', 26, 2, 2)
      IF (IHI .LT. ILO .OR. JHI .LT. JLO) CALL SETERR(
     1   'M5TOP  - INVALID INDICES', 24, 3, 2)
      IF (ILO .LT. 1 .OR. M .LT. IHI .OR. JLO .LT. 1 .OR. N .LT. JHI)
     1   CALL SETERR('M5TOP  - INVALID SUBMATRIX', 26, 4, 2)
C/
      GOTO  5
   1     MM = M
         GOTO  6
   2     MM = N
         GOTO  6
C/6S
C  3     IF (ILO .NE. JLO .OR. IHI .NE. JHI) CALL SETERR(
C    1      25HM5TOP  - INVALID TRIANGLE, 25, 5, 2)
C/7S
   3     IF (ILO .NE. JLO .OR. IHI .NE. JHI) CALL SETERR(
     1      'M5TOP  - INVALID TRIANGLE', 25, 5, 2)
C/
         MM = M
         GOTO  6
C/6S
C  4     CALL SETERR(20HM5TOP  - INVALID IOP, 21, 1, 2)
C/7S
   4     CALL SETERR('M5TOP  - INVALID IOP', 21, 1, 2)
C/
         GOTO  6
   5     IF (IOP .EQ. 4) GOTO  3
         IF (IOP .EQ. 3) GOTO  3
         IF (IOP .EQ. 2) GOTO  2
         IF (IOP .EQ. 1) GOTO  1
         GOTO  4
   6  HPTR = ISTKGT(MM, 3)
      CALL M6TOP(M, N, B, ILO, IHI, JLO, JHI, X, IOP, Y, WS(HPTR))
      CALL LEAVE
      RETURN
      END
