      REAL FUNCTION ARSIN(X)
      REAL X
      REAL T, ATAN2, ABS, SQRT
C    THIS FUNCTION SUBPROGRAM COMPUTES ARCSIN(X) MAKING USE OF THE
C    BUILT-IN FUNCTION ATAN2(A1,A2), WHICH COMPUTES THE ARCTAN(A1/A2).
C    THE RANGE OF ARCSIN(X) IS BETWEEN (-PI/2) AND (PI/2).
C    THE FORMULA USED IS  ARCSIN(X) = ARCTAN(X/SQRT(1-X**2)).
C    NOTE THAT ARCSIN(X) LOSES HALF ITS MEANINGFUL DIGITS WHEN X
C    APPROACHES -1 OR +1.
C    ERROR STATES-
C      1 - IF ABS(X) .GT. 1
C    INPUT-
C      X - THE VALUE WHOSE ARCSIN IS DESIRED
C    OUTPUT-
C       ARSIN = ARCSIN(X)
C    CHECK FOR ERROR STATES, AND PRINT OUT ERROR MESSAGE
C/6S
C     IF (ABS(X) .GT. 1.0E0) CALL SETERR(
C    1   41H ARSIN - NO SOLUTION FOR  ABS(X).GT.1.0E0, 41, 1, 2)
C/7S
      IF (ABS(X) .GT. 1.0E0) CALL SETERR(
     1   ' ARSIN - NO SOLUTION FOR  ABS(X).GT.1.0E0', 41, 1, 2)
C/
C    TO COMPUTE ARCSIN(X)
      T = SQRT(1.0E0-X*X)
      ARSIN = ATAN2(X, T)
      RETURN
      END
