      REAL FUNCTION ATANH(X)
      REAL X
      REAL SUM, CT, S, FACT, X2, ABS
      REAL ALOG
C    THIS FUNCTION SUBPROGRAM COMPUTES ARCTANH(X) IN REAL.
C    THE GENERAL FORMULA USED HERE IS -
C      ARCTANH(X) = 0.5 * LN((1+X)/(1-X))
C    EXCEPT FOR THE CASE WHEN X IS SMALL.
C    IN CASE OF SMALL X, THE SERIES EXPANSION
C      ARCTANH(X) = X * (SUM(FROM 0 TO INF) (X**2N)/(2N+1))
C    IS USED IN PLACE OF THE GENERAL FORMULA.
C    INPUT-
C      X - THE VALUE WHOSE ARCTANH IS DESIRED
C    OUTPUT-
C       ATANH = ARCTANH(X)
C    ERROR STATES-
C      1 - ABS(X) .GE. 1
C/6S
C     IF (ABS(X) .GE. 1.0E0) CALL SETERR(
C    1   41H ATANH - NO SOLUTION FOR  ABS(X).GE.1.0E0, 41, 1, 2)
C/7S
      IF (ABS(X) .GE. 1.0E0) CALL SETERR(
     1   ' ATANH - NO SOLUTION FOR  ABS(X).GE.1.0E0', 41, 1, 2)
C/
      IF (ABS(X) .LE. 0.25E0) GOTO 1
         ATANH = 0.5E0*ALOG((X+1.0E0)/(1.0E0-X))
         RETURN
   1  SUM = 1.0E0
      CT = 1.0E0
      X2 = X*X
      FACT = 1.0E0
      GOTO  3
   2     CONTINUE
   3     FACT = FACT*X2
         CT = CT+2.0E0
         S = SUM+FACT/CT
         IF (S .EQ. SUM) GOTO  4
         SUM = S
         GOTO  2
   4  ATANH = X*SUM
      RETURN
      END
