      SUBROUTINE CDEXP(X,EXP)
      DOUBLE PRECISION X(2),EXP(2),R,DEXP,DCOS,DSIN
C
C COMPLEX DOUBLE PRECISION EXPONENTIAL
C
      R = DEXP(X(1))
      EXP(1) = R*DCOS(X(2))
      EXP(2) = R*DSIN(X(2))
C
      RETURN
      END
