      REAL FUNCTION COSH(X)
      REAL X
      REAL T, EXP, ABS
C    THIS FUNCTION SUBPROGRAM COMPUTES COSH(X) IN REAL.
C    SINCE COSH(X) IS A WELL BEHAVED FUNCTION ON THE ENTIRE REAL
C    INTERVAL, THE ONLY FORMULA USED IN THIS COMPUTATION IS-
C        COSH(X) = (EXP(X)+EXP(-X))/2
C    HOWEVER, IN ORDER TO AVOID OVERFLOW IN THE MACHINE WITH THE ABOVE
C    REPRESENTATION, COSH(X) IS REWRITTEN AS-
C        COSH(X)= (EXP(ABS(X/2))*
C  (EXP(ABS(X/2))*(EXP(ABS(X/2))*0.5))+(0.5/EXP(ABS(X/2)))/EXP(ABS(X/2))
C    INPUT-
C      X - VALUE WHOSE COSH IS DESIRED
C    OUTPUT-
C       COSH = COSH(X)
      T = EXP(ABS(X/2.0E0))
      COSH = T*(0.5E0*T)+(0.5E0/T)/T
      RETURN
      END
