      DOUBLE PRECISION FUNCTION DARCOS(X)
      DOUBLE PRECISION X
      DOUBLE PRECISION T, DATAN2, DSQRT
C    THIS FUNCTION SUBPROGRAM COMPUTES ARCCOS(X) MAKING USE OF THE
C    BUILT-IN FUNCTION DATAN2(A1,A2), WHICH COMPUTES THE ARCTAN(A1/A2).
C    THE RANGE OF ARCCOS(X) IS BETWEEN 0 AND PI.
C    THE FORMULA USED IS  ARCCOS(X) = ARCTAN(SQRT(1-X**2)/X)
C    NOTE THAT ARCCOS(X) LOSES HALF ITS MEANINGFUL DIGITS WHEN X
C    APPROACHES -1 OR +1.
C    ERROR STATES-
C      1 - IF ABS(X) .GT. 1
C    INPUT-
C      X - THE VALUE WHOSE ARCCOS IS DESIRED
C    OUTPUT-
C      DARCOS=ARCCOS(X)
C    CHECK FOR ERROR STATES, AND PRINT OUT ERROR MESSAGE
C/6S
C     IF (DABS(X) .GT. 1.0D0) CALL SETERR(
C    1   41HDARCOS - NO SOLUTION FOR DABS(X).GT.1.0D0, 41, 1, 2)
C/7S
      IF (DABS(X) .GT. 1.0D0) CALL SETERR(
     1   'DARCOS - NO SOLUTION FOR DABS(X).GT.1.0D0', 41, 1, 2)
C/
C    TO COMPUTE ARCCOS(X)
      T = DSQRT(1.0D0-X*X)
      DARCOS = DATAN2(T, X)
      RETURN
      END
