      DOUBLE PRECISION FUNCTION DARSIN(X)
      DOUBLE PRECISION X
      DOUBLE PRECISION T, DATAN2, DSQRT
C    THIS FUNCTION SUBPROGRAM COMPUTES ARCSIN(X) MAKING USE OF THE
C    BUILT-IN FUNCTION DATAN2(A1,A2), WHICH COMPUTES THE ARCTAN(A1/A2).
C    THE RANGE OF ARCSIN(X) IS BETWEEN (-PI/2) AND (PI/2).
C    THE FORMULA USED IS  ARCSIN(X) = ARCTAN(X/SQRT(1-X**2)).
C    NOTE THAT ARCSIN(X) LOSES HALF ITS MEANINGFUL DIGITS WHEN X
C    APPROACHES -1 OR +1.
C    ERROR STATES-
C      1 - IF ABS(X) .GT. 1
C    INPUT-
C      X - THE VALUE WHOSE ARCSIN IS DESIRED
C    OUTPUT-
C      DARSIN = ARCSIN(X)
C    CHECK FOR ERROR STATES, AND PRINT OUT ERROR MESSAGE
C/6S
C     IF (DABS(X) .GT. 1.0D0) CALL SETERR(
C    1   41HDARSIN - NO SOLUTION FOR DABS(X).GT.1.0D0, 41, 1, 2)
C/7S
      IF (DABS(X) .GT. 1.0D0) CALL SETERR(
     1   'DARSIN - NO SOLUTION FOR DABS(X).GT.1.0D0', 41, 1, 2)
C/
C    TO COMPUTE ARCSIN(X)
      T = DSQRT(1.0D0-X*X)
      DARSIN = DATAN2(X, T)
      RETURN
      END
