      DOUBLE PRECISION FUNCTION DASINH(X)
      DOUBLE PRECISION X
      DOUBLE PRECISION T, X2, SUM, S, CT, FACT
      DOUBLE PRECISION DSQRT, DLOG
C    THIS FUNCTION SUBPROGRAM COMPUTES ARCSINH(X) IN DOUBLE PRECISION.
C    THE GENERAL FORMULA USED HERE IS -
C      ARCSINH(X) = LN(X + SQRT(X**2 +1))
C    EXCEPT FOR THE CASE WHEN X IS SMALL.
C    TO AVOID OVERFLOW IN THE MACHINE, ARCSINH(X) IS REWRITTEN AS -
C      ARCSINH(X) = SIGN(X) * LN(ABS(X) + ABS(X)*SQRT(1+(1/X)**2))
C    IN CASE OF SMALL X, THE SERIES EXPANSION
C    ARCSINH(X) =
C      X * (SUM(FROM 0 TO INF)(1*3...(2N-1)*X**2N)/(2*4...2N(2N+1)))
C    IS USED IN PLACE OF THE GENERAL FORMULA.
C    INPUT-
C      X - THE VALUE WHOSE ARCSINH IS DESIRED
C    OUTPUT-
C      DASINH = ARCSINH(X)
      IF (X .NE. 0.0D0) GOTO 1
         DASINH = 0.0D0
         RETURN
   1  IF (DABS(X) .LE. 0.25D0) GOTO 2
         T = DABS(X)*DSQRT((1.0D0/X)**2+1.0D0)
         DASINH = DLOG(DABS(X)+T)*(X/DABS(X))
         RETURN
   2  SUM = 1.0D0
      CT = 0.0D0
      FACT = 1.0D0
      X2 = X*X
      GOTO  4
   3     CONTINUE
   4     CT = CT+2.0D0
         FACT = (-(FACT*X2*(CT-1.0D0)))/CT
         S = SUM+FACT/(CT+1.0D0)
         IF (S .EQ. SUM) GOTO  5
         SUM = S
         GOTO  3
   5  DASINH = X*SUM
      RETURN
      END
