      DOUBLE PRECISION FUNCTION DCOSH(X)
      DOUBLE PRECISION X
      DOUBLE PRECISION T, DEXP
C    THIS FUNCTION SUBPROGRAM COMPUTES COSH(X) IN DOUBLE PRECISION.
C    SINCE COSH(X) IS A WELL BEHAVED FUNCTION ON THE ENTIRE REAL
C    INTERVAL, THE ONLY FORMULA USED IN THIS COMPUTATION IS-
C        COSH(X) = (EXP(X)+EXP(-X))/2
C    HOWEVER, IN ORDER TO AVOID OVERFLOW IN THE MACHINE WITH THE ABOVE
C    REPRESENTATION, COSH(X) IS REWRITTEN AS-
C        COSH(X)= (EXP(ABS(X/2))*
C           (EXP(ABS(X/2))*0.5))+(0.5/EXP(ABS(X/2)))/EXP(ABS(X/2)
C    INPUT-
C      X - VALUE WHOSE COSH IS DESIRED
C    OUTPUT-
C      DCOSH = COSH(X)
      T = DEXP(DABS(X/2.0D0))
      DCOSH = T*(0.5D0*T)+(0.5D0/T)/T
      RETURN
      END
