      LOGICAL FUNCTION A3PLNV(T,ADIFF,N,K,X,IX,ILEFT,ID,NID,ILO,IDIM,FX,
     1                        NX,COL,DM,DP)
C
C  TO SET
C
C  FX(IX,J) = F(ID(J))(X)  J=1,...,NID
C
C  WHERE F(X) = SUM(I=1,...,N-K)(A(I)*N(I,K))
C
C  AND 0.LE.ID(1).LT. ... .LT.ID(NID).LT.K.
C
C  (ADIFF)(ILO,IDIM) IS ASSUMED TO COME FROM A CALL TO A3PLND.
C
C  ILEFT IS ASSUMED TO COME FROM A CALL TO INTRV(N,T,X).
C
C  MUST HAVE ILEFT IN (ILO,IDIM+ILO-K).
C
C  A3PLNV=.TRUE. IS RETURNED IF SUCCESSFUL.
C  A3PLNV=.FALSE. IS RETURNED IF THE MESH T IS NOT MONOTONE INCREASING.
C
      REAL T(N),ADIFF(IDIM,NID),X,FX(NX,NID),COL(K),DM(K),
     1                 DP(K)
      INTEGER ID(NID)
C
      LOGICAL A3PLNN
C
      ILMIL=ILEFT-ILO
      JJ01=0
      J=NID
 10      KMID=K-ID(J)
         A3PLNV=A3PLNN(T,N,X,ILEFT,KMID,COL,DM,DP,JJ01)
         IF(.NOT.A3PLNV) GO TO 30
         FX(IX,J)=0.0E0
         IDX=ILMIL
         DO 20 II=1,KMID
            IDX=IDX+1
 20         FX(IX,J)=FX(IX,J)+ADIFF(IDX,J)*COL(II)
         J=J-1
         IF (J.GE.1) GO TO 10
C
 30   RETURN
C
      END
