      SUBROUTINE BSPDB(G,N,M,B)
C
C  TO SOLVE (L*L-TRANSPOSE)*X=B, WHERE L IS
C  THE CHOLESKY FACTOR OF A BANDED, SYMMETRIC, POSITIVE-DEFINITE
C  MATRIX AS DESCRIBED IN BSPDD.
C
C  INPUT
C
C    G - G(I,J)=L(I,I+J-M) STORES THE LOWER TRIANGULAR PORTION OF L
C        FOR I=1,...,N AND J=1,...,M.
C    N - THE ORDER OF THE MATRIX L.
C    M - THE NUMBER OF ENTRIES OF L ON OR BELOW THE DIAGONAL.
C    B - THE RIGHT-HAND SIDE.
C
C  OUTPUT
C
C    B - THE SOLUTION X.
C
C  SCRATCH SPACE ALLOCATED - NONE.
C
C  ERROR STATES
C
C    1 - N.LT.1
C    2 - M.LT.1
C    3 - SINGULAR L.
C
      REAL G(N,M),B(N)
C
C ... CHECK THE INPUT.
C
C/6S
C     IF (N.LT.1) CALL SETERR(15H BSPDB - N.LT.1,15,1,2)
C     IF (M.LT.1) CALL SETERR(15H BSPDB - M.LT.1,15,2,2)
C/7S
      IF (N.LT.1) CALL SETERR(' BSPDB - N.LT.1',15,1,2)
      IF (M.LT.1) CALL SETERR(' BSPDB - M.LT.1',15,2,2)
C/
C
      DO 10 I=1,N
C/6S
C10   IF (G(I,M).LE.0.0E0)
C    1  CALL SETERR(40H BSPDB - SINGULAR CHOLESKY DECOMPOSITION,40,3,2)
C/7S
 10   IF (G(I,M).LE.0.0E0)
     1  CALL SETERR(' BSPDB - SINGULAR CHOLESKY DECOMPOSITION',40,3,2)
C/
C
C ... FORWARD ELIMINATION.
C
      CALL BSPD1(G,N,M,B)
C
C ... BACK-SUBSTITUTION.
C
      CALL BSPD2(G,N,M,B)
C
      RETURN
C
      END
