      SUBROUTINE BSPLI(K,T,N,
     1                  X,NX,ILEFT,
     2                  BIX)
C
C  TO OBTAIN THE INTEGRAL OF ALL NON-ZERO BASIS SPLINES,
C
C           BIX(IX,I) =
C           INTEGRAL ( T(1) TO X(IX) ) B(ILEFT+I-K) (ZETA) DZETA
C
C  FOR IX=1,...,NX, AND I=1,...,K.
C
C  INPUT
C
C    K      - THE ORDER OF THE B-SPLINES TO BE USED.
C             2.LE.K IS ASSUMED.
C    T      - THE B-SPLINE MESH.
C    N      - THE NUMBER OF POINTS IN THE MESH T.
C    X      - POINTS OF EVALUATION FOR THE INTEGRALS OF THE B-SPLINES.
C    NX     - THE NUMBER OF POINTS IN X.
C    ILEFT  - MUST HAVE T(ILEFT).LT.T(ILEFT+1) AND
C             T(ILEFT) .LE. X(IX) .LE. T(ILEFT+1), IX=1,...,NX.
C
C  OUTPUT
C
C    BIX - THE INTEGRALS OF THE BASIS SPLINES.
C
C  SCRATCH SPACE ALLOCATED - 3*K REAL WORDS.
C
C  ERROR STATES -
C
C     1 - K.LT.2.
C     2 - N.LE.K.
C     3 - NX.LT.1.
C     4 - ILEFT.LT.1.
C     5 - ILEFT.GE.N.
C     6 - T(ILEFT)=T(ILEFT+1).
C     7 - X(IX) NOT IN (T(ILEFT),T(ILEFT+1)).
C     8 - T IS NOT MONOTONE INCREASING.
C
      REAL T(N),X(NX),BIX(NX,K)
C
      LOGICAL A3PLNI
C
      COMMON /CSTAK/DS
      DOUBLE PRECISION DS(500)
      REAL WS(1)
      EQUIVALENCE (DS(1),WS(1))
C
C ... CHECK THE INPUT.
C
C/6S
C     IF (K.LT.2) CALL SETERR(15H BSPLI - K.LT.2,15,1,2)
C     IF (N.LE.K) CALL SETERR(15H BSPLI - N.LE.K,15,2,2)
C     IF (NX.LT.1) CALL SETERR(16H BSPLI - NX.LT.1,16,3,2)
C     IF (ILEFT.LT.1) CALL SETERR(19H BSPLI - ILEFT.LT.1,19,4,2)
C     IF (ILEFT.GE.N) CALL SETERR(19H BSPLI - ILEFT.GE.N,19,5,2)
C     IF (T(ILEFT).EQ.T(ILEFT+1)) CALL SETERR
C    1  (28H BSPLI - T(ILEFT)=T(ILEFT+1),28,6,2)
C/7S
      IF (K.LT.2) CALL SETERR(' BSPLI - K.LT.2',15,1,2)
      IF (N.LE.K) CALL SETERR(' BSPLI - N.LE.K',15,2,2)
      IF (NX.LT.1) CALL SETERR(' BSPLI - NX.LT.1',16,3,2)
      IF (ILEFT.LT.1) CALL SETERR(' BSPLI - ILEFT.LT.1',19,4,2)
      IF (ILEFT.GE.N) CALL SETERR(' BSPLI - ILEFT.GE.N',19,5,2)
      IF (T(ILEFT).EQ.T(ILEFT+1)) CALL SETERR
     1  (' BSPLI - T(ILEFT)=T(ILEFT+1)',28,6,2)
C/
C
      DO 10 IX=1,NX
C/6S
C        IF (X(IX).LT.T(ILEFT).OR.X(IX).GT.T(ILEFT+1)) CALL SETERR
C    1      (42H SPLNI - X(IX) NOT IN T(ILEFT),T(ILEFT+1)),42,7,2)
C/7S
         IF (X(IX).LT.T(ILEFT).OR.X(IX).GT.T(ILEFT+1)) CALL SETERR
     1      (' SPLNI - X(IX) NOT IN T(ILEFT),T(ILEFT+1))',42,7,2)
C/
 10      CONTINUE
C
      ICOL=ISTKGT(3*K,3)
      IDM=ICOL+K
      IDP=IDM+K
C
C/6S
C     IF (.NOT.A3PLNI(K,T,N,
C    1                X,NX,ILEFT,
C    2                BIX,
C    3                WS(ICOL),WS(IDM),WS(IDP)))
C    4   CALL SETERR
C    5      (37H BSPLI - T IS NOT MONOTONE INCREASING,37,8,2)
C/7S
      IF (.NOT.A3PLNI(K,T,N,
     1                X,NX,ILEFT,
     2                BIX,
     3                WS(ICOL),WS(IDM),WS(IDP)))
     4   CALL SETERR
     5      (' BSPLI - T IS NOT MONOTONE INCREASING',37,8,2)
C/
C
      CALL ISTKRL(1)
C
      RETURN
C
      END
