      SUBROUTINE DL2SF(X,Y,NXY,K,T,NT,A)
C
C
C TO FIT A B-SPLINE TO DISCRETE DATA.
C
C THE MNEMONIC IS -
C
C   DOUBLE PRECISION DISCRETE L2 B-SPLINE FIT.
C
C METHOD - LET
C
C   E(F) = SUM(I = 1,...,NXY)
C             ( (Y(I) - F) (X(I)) **2 )
C
C   THIS PROGRAM SOLVES THE PROBLEM
C
C         MINIMIZE (OVER ALL B-SPLINES F) E(F).
C
C INPUT
C
C   X      - THE POINTS WHERE THE FITTING IS TO TAKE PLACE.
C            THE ARRAY X MUST BE MONOTONE INCREASING.
C            ANY MULTIPLICITIES IN X WILL BE IGNORED.
C   Y      - Y(I) IS THE VALUE THE THE B-SPLINE
C            IS TO TAKE AT X(I), FOR I = 1,..,NXY.
C   NXY    - THE NUMBER OF POINTS IN X.
C   K      - THE ORDER OF THE B-SPLINE TO BE USED.
C   T      - THE B-SPLINE MESH TO BE USED.
C   NT     - THE NUMBER OF POINTS IN THE MESH T.
C
C OUTPUT
C
C   A      - THE COEFFICIENTS FOR THE B-SPLINE FIT.
C
C SCRATCH SPACE ALLOCATED -
C
C   (NT-K+4)*K + NXY
C
C REAL WORDS +
C
C   1
C
C INTEGER WORDS.
C
C ERROR STATES -
C
C    1 - NXY.LT.1.
C    2 - K.LT.2.
C    3 - NT.LE.K.
C    4 - X IS NOT MONOTONE INCREASING.
C    5 - NOT ENOUGH FITTING POINTS FOR A UNIQUE L2 FIT.
C    6 - X(1).LT.T(1).
C    7 - X(NXY).GT.T(NT).
C    8 - MESH T IS NOT MONOTONE.
C    9 - MULT(T(I)).GT.K.
C   10 - SINGULAR LEAST SQUARES SYSTEM. (RECOVERABLE)
C
      LOGICAL LS(1000)
      INTEGER IS(1000)
      REAL RS(1000)
      REAL WS(500)
      DOUBLE PRECISION DS(500)
      COMMON /CSTAK/DS
      INTEGER NDX,I,IW,ISTKGT,NERROR,NERR
      INTEGER NXY,K,NT
      REAL X(NXY),Y(NXY),T(NT),A(1)
C
      EQUIVALENCE ( DS(1),WS(1),RS(1),IS(1),LS(1) )
C
C
C A(NT-K)
C
C
C
C CHECK THE INPUT FOR ERRORS.
C
      IF( NXY.GE.1 )      GOTO 1000
C/6S
C     CALL SETERR(17H DL2SF - NXY.LT.1,17,1,2)
C/7S
      CALL SETERR(' DL2SF - NXY.LT.1',17,1,2)
C/
 1000 CONTINUE
      IF( K.GE.2 )      GOTO 1002
C/6S
C     CALL SETERR(15H DL2SF - K.LT.2,15,2,2)
C/7S
      CALL SETERR(' DL2SF - K.LT.2',15,2,2)
C/
 1002 CONTINUE
      IF( NT.GT.K )      GOTO 1004
C/6S
C     CALL SETERR(16H DL2SF - NT.LE.K,16,3,2)
C/7S
      CALL SETERR(' DL2SF - NT.LE.K',16,3,2)
C/
 1004 CONTINUE
C
C COUNT THE NUMBER OF DISTINCT X S.
C
      NDX = 1
      I = 2
 1008 CONTINUE
      IF( I.GT.NXY )      GOTO 1007
      IF( X(I).GE.X(I-1) )      GOTO 1009
C/6S
C           CALL SETERR(37H DL2SF - X IS NOT MONOTONE INCREASING,37,4,2)
C/7S
            CALL SETERR(' DL2SF - X IS NOT MONOTONE INCREASING',37,4,2)
C/
 1009 CONTINUE
C
      IF( X(I).EQ.X(I-1) )      GOTO 1011
      NDX = NDX + (1)
 1011 CONTINUE
 1006 CONTINUE
      I = I + (1)
      GOTO 1008
 1007 CONTINUE
      IF( NDX.GE.NT-K )      GOTO 1013
C/6S
C           CALL SETERR(54H DL2SF - NOT ENOUGH FITTING POINTS FOR A UNIQ
C    *UE L2 FIT,54,5,2)
C/7S
            CALL SETERR(' DL2SF - NOT ENOUGH FITTING POINTS FOR A UNIQUE
     * L2 FIT',54,5,2)
C/
 1013 CONTINUE
C
      IF( X(1).GE.T(1) )      GOTO 1015
C/6S
C     CALL SETERR(21H DL2SF - X(1).LT.T(1),21,6,2)
C/7S
      CALL SETERR(' DL2SF - X(1).LT.T(1)',21,6,2)
C/
 1015 CONTINUE
      IF( X(NXY).LE.T(NT) )      GOTO 1017
C/6S
C     CALL SETERR(24H DL2SF - X(NXY).GT.T(NT),24,7,2)
C/7S
      CALL SETERR(' DL2SF - X(NXY).GT.T(NT)',24,7,2)
C/
 1017 CONTINUE
C
C CHECK THE MESH T.
C
      I21021 = NT-1
      DO 1019 I = 1, I21021
      IF( T(I).LE.T(I+1) )      GOTO 1022
C/6S
C     CALL SETERR(31H DL2SF - MESH T IS NOT MONOTONE,31,8,2)
C/7S
      CALL SETERR(' DL2SF - MESH T IS NOT MONOTONE',31,8,2)
C/
 1022 CONTINUE
      IF( I+K.LE.NT )      GOTO 1024
      GOTO 1019
 1024 CONTINUE
      IX1005 = I+K
      IF( T(IX1005).NE.T(I) )      GOTO 1026
C/6S
C     CALL SETERR(24H DL2SF - MULT(T(I)).GT.K,24,9,2)
C/7S
      CALL SETERR(' DL2SF - MULT(T(I)).GT.K',24,9,2)
C/
 1026 CONTINUE
C
 1019 CONTINUE
 1020 CONTINUE
      CALL ENTER(1)
C
      IW = ISTKGT(NXY,3)
C CREATE THE WEIGHTS.
      CALL SETR(NXY,1.0E0,WS(IW))
C
C NOW SOLVE THE LEAST-SQUARES SYSTEM.
C
      CALL DL2SW(X,Y,NXY,WS(IW),K,T,NT,A)
C
      IF( NERROR(NERR).EQ.0 )      GOTO 1028
      CALL ERROFF
C/6S
C           CALL SETERR(38H DL2SF - SINGULAR LEAST SQUARES SYSTEM,38,10,
C    *1)
C/7S
            CALL SETERR(' DL2SF - SINGULAR LEAST SQUARES SYSTEM',38,10,
     *1)
C/
C
 1028 CONTINUE
      CALL LEAVE
C
      RETURN
C
      END
