      SUBROUTINE DMNP1(X,NX,NL,NI,NR,K,T,NT)
C
C
C TO CREATE A B-SPLINE MESH FROM AN ARRAY OF FITTING POINTS.
C
C METHOD - USE AT AT LEAST NL FITTING POINTS X IN THE FIRST MESH
C          INTERVAL, NI FITTING POINTS IN THE INTERIOR INTERVALS,
C          AND AT LEAST NR FITTING POINTS X IN THE LAST
C          MESH INTERVAL.
C
C MNEMONIC - DOUBLE PRECISION MESH GENERATOR
C            USING N POINTS PER INTERVAL, FOR A B-SPLINE, LEVEL 1.
C
C INPUT -
C
C    X  - THE MONOTONE INCREASING ARRAY OF FITTING POINTS.
C         ANY MULTIPLICITIES IN X WILL BE IGNORED.
C    NX - THE NUMBER OF POINTS IN THE ARRAY X.
C    NL - THE NUMBER OF FITTING POINTS TO BE USED IN THE FIRST
C         MESH INTERVAL. MUST HAVE NL .GE. 2.
C         NL = MAX(2*NI,NI*(K+1-NDX)+2*NDX-K)/2 IS A GOOD CHOICE.
C    NI - THE NUMBER OF FITTING POINTS TO BE USED PER INTERIOR
C         MESH INTERVAL. MUST HAVE NI .GE. 2.
C         NI = K IS A GOOD CHOICE, ALTHOUGH NI = 2 IS OK.
C    NR - THE NUMBER OF FITTING POINTS TO BE USED IN THE LAST
C         MESH INTERVAL. MUST HAVE NR .GE. 2.
C         NR = MAX(2*NI,NI*(K+1-NDX)+2*NDX-K)/2 IS A GOOD CHOICE.
C    K  - THE ORDER OF THE B-SPLINE MESH,
C         THE MULTIPLICITY FOR THE FIRST AND LAST MESH POINTS.
C
C OUTPUT -
C
C    T   - THE MESH OF POINTS TAKEN FROM THE ARRAY X.
C    NT  - THE NUMBER OF POINTS IN THE MESH.
C
C          IF ( NDX .GE. NL+NR-1 )
C
C            NT = 2*K + 1 + (NDX-NL-NR+1)/(NI-1)
C
C          OTHERWISE
C
C            NT = 2*K
C
C          WHERE NDX IS THE NUMBER OF DISTINCT POINTS IN THE ARRAY
C
C ERROR STATES -
C
C   1 - NX .LT. 2.
C   2 - NL .LT. 2
C   3 - NI .LT. 2.
C   4 - NR .LT. 2.
C   5 - K .LT. 1.
C   6 - THE ARRAY X IS NOT MONOTONE INCREASING.
C   7 - THE NUMBER OF DISTINCT POINTS IN THE ARRAY X IS ONE.
C
C STORAGE ALLOCATED - NONE.
C
      INTEGER NDX,I
      INTEGER NX,NL,NI,NR,K,NT
      DOUBLE PRECISION X(NX),T(1)
C
C
C
C T(NT).
C
C
C CHECK THE INPUT FOR ERRORS.
C
      IF( NX.GE.2 )      GOTO 1000
C/6S
C     CALL SETERR(15HDMNP1 - NX.LT.2,15,1,2)
C/7S
      CALL SETERR('DMNP1 - NX.LT.2',15,1,2)
C/
 1000 CONTINUE
      IF( NL.GE.2 )      GOTO 1002
C/6S
C     CALL SETERR(15HDMNP1 - NL.LT.2,15,2,2)
C/7S
      CALL SETERR('DMNP1 - NL.LT.2',15,2,2)
C/
 1002 CONTINUE
      IF( NI.GE.2 )      GOTO 1004
C/6S
C     CALL SETERR(15HDMNP1 - NI.LT.2,15,3,2)
C/7S
      CALL SETERR('DMNP1 - NI.LT.2',15,3,2)
C/
 1004 CONTINUE
      IF( NR.GE.2 )      GOTO 1006
C/6S
C     CALL SETERR(15HDMNP1 - NR.LT.2,15,4,2)
C/7S
      CALL SETERR('DMNP1 - NR.LT.2',15,4,2)
C/
 1006 CONTINUE
      IF( K.GE.1 )      GOTO 1008
C/6S
C     CALL SETERR(14HDMNP1 - K.LT.1,14,5,2)
C/7S
      CALL SETERR('DMNP1 - K.LT.1',14,5,2)
C/
 1008 CONTINUE
C
      NDX = 1
C GET THE NUMBER OF DISTINCT POINTS IN X.
      DO 1010 I = 2, NX
      IF( X(I).GE.X(I-1) )      GOTO 1013
C/6S
C     CALL SETERR(36HDMNP1 - X IS NOT MONOTONE INCREASING,36,6,2)
C/7S
      CALL SETERR('DMNP1 - X IS NOT MONOTONE INCREASING',36,6,2)
C/
 1013 CONTINUE
      IF( X(I).LE.X(I-1) )      GOTO 1015
      NDX = NDX+1
 1015 CONTINUE
 1010 CONTINUE
 1011 CONTINUE
      IF( NDX.NE.1 )      GOTO 1017
C/6S
C           CALL SETERR(37HDMNP1 - ONLY ONE POINT IN THE ARRAY X,37,7,2)
C/7S
            CALL SETERR('DMNP1 - ONLY ONE POINT IN THE ARRAY X',37,7,2)
C/
 1017 CONTINUE
C
      CALL DMNP2(X,NX,NL,NI,NR,K,1,K,T,NT)
C
      RETURN
C
      END
