      SUBROUTINE DUMD(A,B,NAB,X)
C
C  TO SET UP THE MESH X(1),...,X(NAB) ON (A,B) WHICH INCLUDES THE
C  POINTS A + (I-1)*((B-A)/(NAB-1)), I=1,...,NAB.
C
C  INPUT -
C
C    A   - LEFT HAND END POINT.
C    B   - RIGHT HAND END POINT.
C    NAB - NUMBER OF POINTS TO BE USED ON (A,B).
C
C  OUTPUT -
C
C    X  - THE MESH X.
C
C  SCRATCH SPACE ALLOCATED - NONE.
C
C  ERROR STATES -
C
C    1 - A=B.
C    2 - NAB.LT.2.
C
      DOUBLE PRECISION A,B,X(NAB)
C
C ... CHECK THE INPUT.
C
C/6S
C     IF (A.EQ.B) CALL SETERR(10HDUMD - A=B,10,1,2)
C     IF (NAB.LT.2) CALL SETERR(15HDUMD - NAB.LT.2,15,2,2)
C/7S
      IF (A.EQ.B) CALL SETERR('DUMD - A=B',10,1,2)
      IF (NAB.LT.2) CALL SETERR('DUMD - NAB.LT.2',15,2,2)
C/
C
      CALL DUMB(A,B,NAB,1,X,NX)
C
      RETURN
C
      END
