      REAL FUNCTION EESFI(K,T,N,A,F,X,NX,EEST)
C
C
C PURPOSE -
C
C   TO FIND THE MAXIMUM ABSOLUTE DIFFERENCE BETWEEN F(Y) AND S(Y),
C   WHERE S(Y) IS THE B-SPLINE GIVEN BY (K,T,N,A), ON EACH INTERVA
C   (X(I),X(I+1)) FOR I = 1,...,NX-1.
C
C METHOD -
C
C   LET MEST = (2*K-1)*PI + 1.
C
C   THE MAXIMUM IS FOUND (ESTIMATED) BY
C   SEARCHING EACH T INTERVAL AT A PATTERN OF MEST POINTS GIVEN BY
C   COS(THETA) WHERE MEST EQUALLY SPACED THETA VALUES ON (-PI,0) A
C   THIS SEARCH GUARANTEES THAT IF F IS A POLYNOMIAL OF DEGREE LES
C   2*K, THE ERROR ESTIMATE WILL BE COMPUTED ACCURATE TO WITHIN A
C   FACTOR OF 2.
C
C MNEMONIC - DOUBLE PRECISION ESTIMATION OF THE ERROR IN A
C            SPLINE FIT TO A FUNCTION, OVER GIVEN INTERVALS.
C
C INPUT -
C
C   K      - THE B-SPLINE ORDER USED.
C   T      - THE B-SPLINE MESH.
C   N      - THE NUMBER OF POINTS IN THE MESH T.
C   A      - THE B-SPLINE COEFFICIENTS.
C   F      - THE NAME OF A USER SUPPLIED SUBROUTINE
C
C                    F(X,NX,FX,WX)
C
C            F MUST DECLARED EXTERNAL IN THE USERS CALLING PROGRAM
C
C            INPUT -
C
C              X    - THE POINTS WHERE F IS TO BE EVALUATED.
C              NX   - THE LENGTH OF THE ARRAY X.
C
C            OUTPUT -
C
C              FX - FX(I) = F( X(I) ), I = 1,...,NX.
C              WX - WX IS A DUMMY ARRAY OF LENGTH NX TO MAKE THE C
C                   CONSISTANT WITH THAT TO F IN DL2SFF.
C   X      - THE INTERVALS ON WHICH THE ERROR IS DESIRED.
C            X MUST BE MONOTONE INCREASING.
C   NX     - THE NUMBER OF POINTS IN X.
C
C OUTPUT -
C
C   EEST - EEST(I) IS THE MAXIMUM ERROR FOUND ON THE I-TH X INTERV
C          FOR I = 1,...,NX-1.
C          IF X(I) = X(I+1) THEN EEST(I) IS MEANINGLESS.
C
C          EEST(NX) = MAX(EEST(1),...,EEST(NX-1))
C
C   PROCEDURE VALUE - EEST(NX).
C
C SCRATCH SPACE ALLOCATED - 4*K + (2*K-1)*PI + 1 REAL WORDS.
C
C ERROR STATES -
C
C   1 - K.LT.2.
C   2 - N.LE.K.
C   3 - NX.LT.2.
C   4 - T NOT MONOTONE INCREASING.
C   5 - (X(1),X(NX)) NOT PART OF (T(1),T(N)).
C   6 - X IS NOT MONOTONE INCREASING.
C
      INTEGER I,MEST
      REAL EESFM
      EXTERNAL F
      INTEGER K,N,NX
      REAL T(N),A(1),X(NX),EEST(NX)
C
C
C
C A(N-K).
C
C
C CHECK THE INPUT.
C
      IF( K.GE.2 )      GOTO 1000
C/6S
C     CALL SETERR(15H EESFI - K.LT.2,15,1,2)
C/7S
      CALL SETERR(' EESFI - K.LT.2',15,1,2)
C/
 1000 CONTINUE
      IF( N.GT.K )      GOTO 1002
C/6S
C     CALL SETERR(15H EESFI - N.LE.K,15,2,2)
C/7S
      CALL SETERR(' EESFI - N.LE.K',15,2,2)
C/
 1002 CONTINUE
      IF( NX.GE.2 )      GOTO 1004
C/6S
C     CALL SETERR(16H EESFI - NX.LT.2,16,3,2)
C/7S
      CALL SETERR(' EESFI - NX.LT.2',16,3,2)
C/
 1004 CONTINUE
C
      I21008 = N-1
      DO 1006 I = 1, I21008
      IF( T(I).LE.T(I+1) )      GOTO 1009
C/6S
C     CALL SETERR(34H EESFI - T NOT MONOTONE INCREASING,34,4,2)
C/7S
      CALL SETERR(' EESFI - T NOT MONOTONE INCREASING',34,4,2)
C/
 1009 CONTINUE
      IF( I+K.LE.N )      GOTO 1011
      GOTO 1006
 1011 CONTINUE
      IX1005 = I+K
      IF( T(IX1005).GT.T(I) )      GOTO 1013
C/6S
C     CALL SETERR(34H EESFI - T NOT MONOTONE INCREASING,34,4,2)
C/7S
      CALL SETERR(' EESFI - T NOT MONOTONE INCREASING',34,4,2)
C/
 1013 CONTINUE
C
 1006 CONTINUE
 1007 CONTINUE
      IF( X(1).GE.T(1).AND.X(NX).LE.T(N) )      GOTO 1015
C/6S
C           CALL SETERR(45H EESFI - (X(1),X(NX)) NOT PART OF (T(1),T(N))
C    *,45,5,2)
C/7S
            CALL SETERR(' EESFI - (X(1),X(NX)) NOT PART OF (T(1),T(N))'
     *,45,5,2)
C/
C
 1015 CONTINUE
      I21019 = NX-1
      DO 1017 I = 1, I21019
      IF( X(I).LE.X(I+1) )      GOTO 1020
C/6S
C           CALL SETERR(37H EESFI - X IS NOT MONOTONE INCREASING,37,6,2)
C/7S
            CALL SETERR(' EESFI - X IS NOT MONOTONE INCREASING',37,6,2)
C/
 1020 CONTINUE
C
 1017 CONTINUE
 1018 CONTINUE
      MEST = FLOAT(2*K-1)*4.0E0*ATAN(1.0E0)+1.0E0
C
      EESFI = EESFM(K,T,N,A,F,X,NX,MEST,EEST)
      RETURN
C
      END
