      SUBROUTINE MNP2(X,NX,NL,NI,NR,ML,MI,MR,T,NT)
C
C
C TO CREATE A B-SPLINE MESH FROM AN ARRAY OF FITTING POINTS.
C
C METHOD - USE AT AT LEAST NL FITTING POINTS X IN THE FIRST MESH
C          INTERVAL, NI FITTING POINTS IN THE INTERIOR INTERVALS,
C          AND AT LEAST NR FITTING POINTS X IN THE LAST
C          MESH INTERVAL.
C
C MNEMONIC - DOUBLE PRECISION MESH GENERATOR
C            USING N POINTS PER INTERVAL, FOR A B-SPLINE, LEVEL 2.
C
C INPUT -
C
C    X  - THE MONOTONE INCREASING ARRAY OF FITTING POINTS.
C         ANY MULTIPLICITIES IN X WILL BE IGNORED.
C    NX - THE NUMBER OF POINTS IN THE ARRAY X.
C    NL - THE NUMBER OF FITTING POINTS TO BE USED IN THE FIRST
C         MESH INTERVAL. MUST HAVE NL .GE. 2.
C         NL = MAX(2*NI,NI*(K+1-NDX)+2*NDX-K)/2 IS A GOOD CHOICE.
C    NI - THE NUMBER OF FITTING POINTS TO BE USED PER INTERIOR
C         MESH INTERVAL. MUST HAVE NI .GE. 2.
C         NI = K IS A GOOD CHOICE, ALTHOUGH NI = 2 IS OK.
C    NR - THE NUMBER OF FITTING POINTS TO BE USED IN THE LAST
C         MESH INTERVAL. MUST HAVE NR .GE. 2.
C         NR = MAX(2*NI,NI*(K+1-NDX)+2*NDX-K)/2 IS A GOOD CHOICE.
C    ML - THE MULTIPLICITY OF THE LEFT-HAND MESH POINT, X(1).
C    MI - THE MULTIPLICITY OF THE INTERIOR MESH POINTS.
C    MR - THE MULTIPLICITY OF THE RIGHT-HAND MESH POINT, X(NX).
C
C OUTPUT -
C
C    T   - THE MESH OF POINTS TAKEN FROM THE ARRAY X.
C    NT  - THE NUMBER OF POINTS IN THE MESH.
C
C          IF ( NDX .GE. NL+NR-1 )
C
C            NT = ML + ( 1 + (NDX-NL-NR+1)/(NI-1) )*MI + MR
C
C          OTHERWISE
C
C            NT = ML + MR
C
C          WHERE NDX IS THE NUMBER OF DISTINCT POINTS IN THE ARRAY
C
C ERROR STATES -
C
C   1 - NX .LT. 2.
C   2 - NL .LT. 2
C   3 - NI .LT. 2.
C   4 - NR .LT. 2.
C   5 - ML .LT. 1.
C   6 - MI .LT. 1
C   7 - MR .LT. 1.
C   8 - THE ARRAY X IS NOT MONOTONE INCREASING.
C   9 - THE NUMBER OF DISTINCT POINTS IN THE ARRAY X IS ONE.
C
C STORAGE ALLOCATED - NONE.
C
      INTEGER NDX,I,NDT,IDXT,NDXI,IX,MULT,NIL,NII,NIR
      INTEGER NX,NL,NI,NR,ML,MI,MR,NT
      REAL X(NX),T(1)
C
C
C
C T(NT).
C
C
C CHECK THE INPUT FOR ERRORS.
C
      IF( NX.GE.2 )      GOTO 1000
C/6S
C     CALL SETERR(15H MNP2 - NX.LT.2,15,1,2)
C/7S
      CALL SETERR(' MNP2 - NX.LT.2',15,1,2)
C/
 1000 CONTINUE
      IF( NL.GE.2 )      GOTO 1002
C/6S
C     CALL SETERR(15H MNP2 - NL.LT.2,15,2,2)
C/7S
      CALL SETERR(' MNP2 - NL.LT.2',15,2,2)
C/
 1002 CONTINUE
      IF( NI.GE.2 )      GOTO 1004
C/6S
C     CALL SETERR(15H MNP2 - NI.LT.2,15,3,2)
C/7S
      CALL SETERR(' MNP2 - NI.LT.2',15,3,2)
C/
 1004 CONTINUE
      IF( NR.GE.2 )      GOTO 1006
C/6S
C     CALL SETERR(15H MNP2 - NR.LT.2,15,4,2)
C/7S
      CALL SETERR(' MNP2 - NR.LT.2',15,4,2)
C/
 1006 CONTINUE
      IF( ML.GE.1 )      GOTO 1008
C/6S
C     CALL SETERR(15H MNP2 - ML.LT.1,15,5,2)
C/7S
      CALL SETERR(' MNP2 - ML.LT.1',15,5,2)
C/
 1008 CONTINUE
      IF( MI.GE.1 )      GOTO 1010
C/6S
C     CALL SETERR(15H MNP2 - MI.LT.1,15,6,2)
C/7S
      CALL SETERR(' MNP2 - MI.LT.1',15,6,2)
C/
 1010 CONTINUE
      IF( MR.GE.1 )      GOTO 1012
C/6S
C     CALL SETERR(15H MNP2 - MR.LT.1,15,7,2)
C/7S
      CALL SETERR(' MNP2 - MR.LT.1',15,7,2)
C/
 1012 CONTINUE
C
      NDX = 1
C GET THE NUMBER OF DISTINCT POINTS IN X.
      DO 1014 I = 2, NX
      IF( X(I).GE.X(I-1) )      GOTO 1017
C/6S
C     CALL SETERR(36H MNP2 - X IS NOT MONOTONE INCREASING,36,8,2)
C/7S
      CALL SETERR(' MNP2 - X IS NOT MONOTONE INCREASING',36,8,2)
C/
 1017 CONTINUE
      IF( X(I).LE.X(I-1) )      GOTO 1019
      NDX = NDX+1
 1019 CONTINUE
 1014 CONTINUE
 1015 CONTINUE
      IF( NDX.NE.1 )      GOTO 1021
C/6S
C           CALL SETERR(37H MNP2 - ONLY ONE POINT IN THE ARRAY X,37,9,2)
C/7S
            CALL SETERR(' MNP2 - ONLY ONE POINT IN THE ARRAY X',37,9,2)
C/
 1021 CONTINUE
C
      IF( NL+NR-1.LE.NDX )      GOTO 1023
C     THE MESH IS (X(1),X(NX)).
      NT = ML+MR
      CALL SETR(ML,X(1),T)
      CALL SETR(MR,X(NX),T(ML+1))
      RETURN
C
C HAVE A FULL MESH.
C
 1023 CONTINUE
      NDT = 3+(NDX-NL-NR+1)/(NI-1)
C NDT = NUMBER OF DISTINCT MESH PTS.
      NIL = (NDX-NL-NR-(NDT-3)*(NI-1)+1)/2
      NIR = NDX-NL-NR+1-(NDT-3)*(NI-1)-NIL
      NIL = NL+NIL
      NIR = NR+NIR
      NT = ML+(NDT-2)*MI+MR
C
      CALL SETR(ML,X(1),T)
      IDXT = ML+1
      NDXI = 0
      NII = NIL-1
      IX = 2
 1027 CONTINUE
      IF( IX.GT.NX )      GOTO 1026
C     MAKE THE MESH.
      IF( X(IX-1).NE.X(IX) )      GOTO 1028
      GOTO 1025
 1028 CONTINUE
      NDXI = NDXI+1
 1029 CONTINUE
      IF( NDXI.GE.NII )      GOTO 1030
      GOTO 1025
 1030 CONTINUE
C
      IF( X(IX).GE.X(NX) )      GOTO 1032
      MULT = MI
      GOTO 1033
 1032 CONTINUE
      MULT = MR
 1033 CONTINUE
      CALL SETR(MULT,X(IX),T(IDXT))
      IDXT = IDXT+MULT
      NDXI = 0
      IF( IDXT.NE.NT-MR+1 )      GOTO 1034
      NII = NIR-1
      GOTO 1035
 1034 CONTINUE
      NII = NI-1
 1035 CONTINUE
C
 1025 CONTINUE
      IX = IX+1
      GOTO 1027
 1026 CONTINUE
      RETURN
C
      END
