      DOUBLE PRECISION FUNCTION DL4ST1(X)
C
C 1-DIM FUNCTION
C
      DOUBLE PRECISION X, F
      DOUBLE PRECISION RS(500)
      INTEGER IS(1000)
      INTEGER P,RLEN
      COMMON/DL6NCB/N,P,IB,IY
      COMMON/CSTAK/R(1000)
      EQUIVALENCE (R(1),IS(1))
      EQUIVALENCE (R(1),RS(1))
C
      IW=ISTKGT(P, 4)
      RLEN= (P*(P+1))/2
      IR=ISTKGT(RLEN, 4)
      IIPVT=ISTKGT(P,2)
C
C EVALUATE FUNCTION
C
      CALL DL4ST2(X,N,P,F,RS(IB),RS(IY),RS(IW),RS(IR),RLEN,IS(IIPVT))
      DL4ST1=F
      CALL ISTKRL(3)
      RETURN
      END
