      DOUBLE PRECISION FUNCTION DMNSX(FUNCT, ITMX, P, PP, S, TOL, X)
C
C *** NELDER-MEAD SIMPLEX METHOD (PATTERN SEARCH) FOR UNCONSTRAINED
C *** MINIMIZATION.
C
      INTEGER ITMX, P, PP
      DOUBLE PRECISION S(PP,1), TOL, X(P)
      EXTERNAL FUNCT
      DOUBLE PRECISION FUNCT
C
C *** PARAMETERS ***
C
C FUNC (INPUT)   EXTERNAL FUNCTION TO COMPUTE F(X)
C ITMX (INPUT)   MAX. NO. OF ITERATIONS ALLOWED
C P    (INPUT)   PROBLEM DIMENSION
C PP   (INPUT)   LEAD DIMENSION OF S, WHICH MUST BE AT LEAST P
C S    (IN/OUT)  ON INPUT, THE INITIAL SIMPLEX.  ON OUTPUT, THE FINAL
C                SIMPLEX
C TOL  (IN/OUT)  ON INPUT, THE CONVERGENCE TOLERANCE (ON THE STANDARD
C                DEVIATION OF THE FUNCTION VALUES AT THE SIMPLEX
C                VERTICES).  ON OUTPUT, TOL IS SET TO THIS STANDARD
C                DEVIATION.
C X    (OUTPUT)  THE BEST X VALUE FOUND, CORRESPONDING TO THE RETURN
C                VALUE FROM DMNSX
C
C
      DOUBLE PRECISION DSTAK(500)
      COMMON /CSTAK/ DSTAK
C
      INTEGER ISTKGT
      DOUBLE PRECISION DM7NSX
      EXTERNAL ISTKGT, ISTKRL, DM7NSX
C
C *** LOCAL VARIABLES ***
C
      INTEGER DX1, IRC, XE1, XR1, Y1
      DOUBLE PRECISION ZERO
      DATA ZERO/0.D+0/
C
C *** BODY ***
C
      IF (TOL .LE. ZERO) GO TO 30
      DX1 = ISTKGT(4*P+1, 4)
      XE1 = DX1 + P
      XR1 = XE1 + P
      Y1 = XR1 + P
      DMNSX = DM7NSX(DSTAK(DX1), FUNCT, IRC, ITMX, P, P+1, PP, S, TOL,
     1               X, DSTAK(XE1), DSTAK(XR1), DSTAK(Y1))
      GO TO (50, 10, 20, 40), IRC
C/6S
C10   CALL SETERR(33HDMNSX -- ITERATION LIMIT EXCEEDED, 33, 1, 1)
C/7S
 10   CALL SETERR('DMNSX -- ITERATION LIMIT EXCEEDED', 33, 1, 1)
C/
      GO TO 50
C/6S
C20   CALL SETERR(27HDMNSX -- INVALID DIMENSIONS, 27, 2, 2)
C30   CALL SETERR(30HDMNSX CALLED WITH TOL .LE. 0.0, 31, 4, 2)
C40   CALL SETERR(
C    1   59HDMNSX -- FUNCTION AT SIMPLEX CENTER EXCEEDS MAX AT VERTICES,
C    2            59, 3, 1)
C/7S
 20   CALL SETERR('DMNSX -- INVALID DIMENSIONS', 27, 2, 2)
 30   CALL SETERR('DMNSX CALLED WITH TOL .LE. 0.0', 31, 4, 2)
 40   CALL SETERR(
     1   'DMNSX -- FUNCTION AT SIMPLEX CENTER EXCEEDS MAX AT VERTICES',
     2            59, 3, 1)
C/
 50   CALL ISTKRL(1)
      RETURN
C *** LAST LINE OF DMNSX FOLLOWS ***
      END
