      SUBROUTINE  DSN2FB(N, P, X,B, CALCR,   MXFCAL, ACC )
C
C ** SIMPLIED VERSION OF DN2FB
C
C INPUT PARAMETERS
C N    NUMBER OF OBSERVATIONS
C P    NUMBER OF UNKNOWNS
C X    APPROXIMATE SOLUTION
C B    FIRST ROW CONTAINS LOWER BOUNDS ON VARIABLES AND SECOND
C      ROW CONSTAINS UPPER BOUNDS
C CALCR SUBROUTINE TO EVALUATE RESIDUAL
C MXFCAL MAXIMUM NUMBER OF PERMITTED FUNCTION EVALUATIONS
C ACC   ACCURACY IN X
C OUTPUT PARAMETERS
C X     SOLUTION
      INTEGER N, P, MXFCAL
      DOUBLE PRECISION X(N), ACC , B(2,P)
      EXTERNAL CALCR,   DC6LCR
C
C
C
C  ***  LOCAL VARIABLES  ***, B(2,P)
C
      INTEGER IV, LIV, LV, V1
      DOUBLE PRECISION UR
      DOUBLE PRECISION DSTAK(500)
      INTEGER ISTAK(1000)
      COMMON /CSTAK/ DSTAK
      EQUIVALENCE (DSTAK(1), ISTAK(1))
C
C  ***  BODY  ***
C
      CALL ENTER(0)
C/6S
C     IF (N.LT.1.OR.P.LT.1)
C    1CALL SETERR(24HDSN2FB- N.LT.1 OR P.LT.1,24,1,2)
C     IF (MXFCAL.LT.1)
C    1CALL SETERR(19HDSN2FB- MXFCAL.LT.1,19,2,2)
C     IF (ACC.LT.0.0D0)
C    1CALL SETERR(18HDSN2FB-ACC .LT.0.0,18,3,2)
C/7S
      IF (N.LT.1.OR.P.LT.1)
     1CALL SETERR('DSN2FB- N.LT.1 OR P.LT.1',24,1,2)
      IF (MXFCAL.LT.1)
     1CALL SETERR('DSN2FB- MXFCAL.LT.1',19,2,2)
      IF (ACC.LT.0.0D0)
     1CALL SETERR('DSN2FB-ACC .LT.0.0',18,3,2)
C/
      LIV = 4*P + 82
      LV = P*(N + 2*P + 21) + 2*N + 105
      IV=ISTKGT(LIV,2)
      V1=ISTKGT(LV, 4)
      CALL DIVSET(1,ISTAK(IV),LIV,LV,DSTAK(V1))
      ISTAK(IV+20)=0
      ISTAK(IV+16)=MXFCAL
      ISTAK(IV+17)=MXFCAL
      ISTAK(IV+56)=0
      DSTAK(V1+32)=ACC
      DSTAK(V1+31)=ACC
      CALL  DN2FB(N, P, X,B,  DC6LCR,  ISTAK(IV), LIV, LV,
     1            DSTAK(V1), IU, UR, CALCR)
      J=ISTAK(IV)
      IF(J.LT.7) GO TO 20
C/6S
C     IF (J.EQ.82)CALL SETERR(26HDSN2FB-INCONSISTENT BOUNDS,26,4,1)
C     IF (J.EQ.7)CALL SETERR(27HDSN2FB-SINGULAR CONVERGENCE,27,5,1)
C     IF(J.EQ.8)CALL SETERR(24HDSN2FB-FALSE CONVERGENCE,24,6,1)
C     IF(J.EQ.9)CALL SETERR(32HDSN2FB-FUNCTION EVALUATION LIMIT,32,7,1)
C     IF (J.EQ.63)
C    1CALL SETERR(43HDSN2FB-F(X) CANNOT BE COMPUTED AT INITIAL X,43,8,1)
C/7S
      IF (J.EQ.82)CALL SETERR('DSN2FB-INCONSISTENT BOUNDS',26,4,1)
      IF (J.EQ.7)CALL SETERR('DSN2FB-SINGULAR CONVERGENCE',27,5,1)
      IF(J.EQ.8)CALL SETERR('DSN2FB-FALSE CONVERGENCE',24,6,1)
      IF(J.EQ.9)CALL SETERR('DSN2FB-FUNCTION EVALUATION LIMIT',32,7,1)
      IF (J.EQ.63)
     1CALL SETERR('DSN2FB-F(X) CANNOT BE COMPUTED AT INITIAL X',43,8,1)
C/
 20   CALL LEAVE
C
      RETURN
C  *** LAST LINE OF  DSN2FB FOLLOWS  ***
      END
