      REAL FUNCTION L4ST1(X)
C
C 1-DIM FUNCTION
C
      REAL RS(1000)
      INTEGER IS(1000)
      INTEGER P,RLEN
      COMMON/L6NCB/N,P,IB,IY
      COMMON/CSTAK/R(1000)
      EQUIVALENCE (R(1),IS(1))
      EQUIVALENCE (R(1),RS(1))
C
      IW=ISTKGT(P, 3)
      RLEN= (P*(P+1))/2
      IR=ISTKGT(RLEN, 3)
      IIPVT=ISTKGT(P,2)
C
C EVALUATE FUNCTION
C
      CALL L4ST2(X,N,P,F,RS(IB),RS(IY),RS(IW),RS(IR),RLEN,IS(IIPVT))
      L4ST1=F
      CALL ISTKRL(3)
      RETURN
      END
