      REAL FUNCTION  MNSX(FUNC, ITMX, P, PP, S, TOL, X)
C
C *** NELDER-MEAD SIMPLEX METHOD (PATTERN SEARCH) FOR UNCONSTRAINED
C *** MINIMIZATION.
C
      INTEGER ITMX, P, PP
      REAL S(PP,1), TOL, X(P)
      REAL FUNC
      EXTERNAL FUNC
C
C *** PARAMETERS ***
C
C FUNC (INPUT)   EXTERNAL FUNCTION TO COMPUTE F(X)
C ITMX (INPUT)   MAX. NO. OF ITERATIONS ALLOWED
C P    (INPUT)   PROBLEM DIMENSION
C PP   (INPUT)   LEAD DIMENSION OF S, WHICH MUST BE AT LEAST P
C S    (IN/OUT)  ON INPUT, THE INITIAL SIMPLEX.  ON OUTPUT, THE FINAL
C                SIMPLEX
C TOL  (IN/OUT)  ON INPUT, THE CONVERGENCE TOLERANCE (ON THE STANDARD
C                DEVIATION OF THE FUNCTION VALUES AT THE SIMPLEX
C                VERTICES).  ON OUTPUT, TOL IS SET TO THIS STANDARD
C                DEVIATION.
C X    (OUTPUT)  THE BEST X VALUE FOUND, CORRESPONDING TO THE RETURN
C                VALUE FROM MNSX
C
C
      REAL RSTAK(1000)
      COMMON /CSTAK/ RSTAK
C
      INTEGER ISTKGT
      REAL M7NSX
      EXTERNAL ISTKGT, ISTKRL, M7NSX
C
C *** LOCAL VARIABLES ***
C
      INTEGER DX1, IRC, XE1, XR1, Y1
      REAL ZERO
      DATA ZERO/0.E+0/
C
C *** BODY ***
C
      IF (TOL .LE. ZERO) GO TO 30
      DX1 = ISTKGT(4*P+1, 3)
      XE1 = DX1 + P
      XR1 = XE1 + P
      Y1 = XR1 + P
       MNSX = M7NSX(RSTAK(DX1), FUNC, IRC, ITMX, P, P+1, PP, S, TOL,
     1               X, RSTAK(XE1), RSTAK(XR1), RSTAK(Y1))
      GO TO (50, 10, 20, 40), IRC
C/6S
C10   CALL SETERR(33H MNSX -- ITERATION LIMIT EXCEEDED, 33, 1, 1)
C/7S
 10   CALL SETERR(' MNSX -- ITERATION LIMIT EXCEEDED', 33, 1, 1)
C/
      GO TO 50
C/6S
C20   CALL SETERR(27H MNSX -- INVALID DIMENSIONS, 27, 2, 2)
C30   CALL SETERR(30H MNSX CALLED WITH TOL .LE. 0.0, 31, 4, 2)
C40   CALL SETERR(
C    1   59H MNSX -- FUNCTION AT SIMPLEX CENTER EXCEEDS MAX AT VERTICES,
C    2            59, 3, 1)
C/7S
 20   CALL SETERR(' MNSX -- INVALID DIMENSIONS', 27, 2, 2)
 30   CALL SETERR(' MNSX CALLED WITH TOL .LE. 0.0', 31, 4, 2)
 40   CALL SETERR(
     1   ' MNSX -- FUNCTION AT SIMPLEX CENTER EXCEEDS MAX AT VERTICES',
     2            59, 3, 1)
C/
 50   CALL ISTKRL(1)
      RETURN
C *** LAST LINE OF  MNSX FOLLOWS ***
      END
