      DOUBLE PRECISION FUNCTION CD1MOD(R,I)
C MODULUS OF A COMPLEX NUMBER AVOIDING OVERFLOW.
      DOUBLE PRECISION R,I,AR,AI,DSQRT
      AR = DABS(R)
      AI = DABS(I)
      IF (AR .GE. AI) GO TO 10
          CD1MOD = AI*DSQRT(1.0D0+(AR/AI)**2)
          RETURN
   10 IF (AR .LE. AI) GO TO 20
          CD1MOD = AR*DSQRT(1.0D0+(AI/AR)**2)
          RETURN
   20 CD1MOD = AR*DSQRT(2.0D0)
      RETURN
      END
