      SUBROUTINE CNVFRD(N,A,B)
C
C     CNVFRD CONVERTS THE N REAL ITEMS IN A
C     TO DOUBLE PRECISION ITEMS PUTTING THE RESULT IN B.
C     A FOWARDS DO LOOP IS USED.
C
      REAL A(1)
      DOUBLE PRECISION B(1)
C
      IF(N .LE. 0) RETURN
C
      DO 10 I = 1, N
 10     B(I) = A(I)
C
      RETURN
C
      END
