      DOUBLE PRECISION FUNCTION DDIM(X, Y)
      DOUBLE PRECISION X, Y
C    THIS FUNCTION SUBPROGRAM COMPUTES THE POSITIVE DIFFERENCE
C    OF TWO NUMBERS IN DOUBLE PRECISION.
      DDIM = X-DMIN1(X, Y)
      RETURN
      END
