      DOUBLE PRECISION FUNCTION DMKFL( E, M )
C
C     DMKFL RETURNS (B**E) * M, WHERE B = I1MACH(10)
C
C     CHANGED JUNE 4, 1976
C
C     INPUT NEED NOT BE NORMALIZED
C
      DOUBLE PRECISION M
      DOUBLE PRECISION S3MACH
      INTEGER E, TE
C
      DOUBLE PRECISION TBASE
      INTEGER BASE, MINEXP, MAXEXP
C
      DATA TBASE / 0.0D0 /
      DATA BASE, MINEXP, MAXEXP / 3*0 /
C
      IF( BASE .NE. 0 ) GO TO 5
        BASE   = I1MACH(10)
        MINEXP = I1MACH(15)
        MAXEXP = I1MACH(16)
        TBASE  = BASE
C
 5    TE = E
      DMKFL = M
C
      IF( DABS(DMKFL) .GE. 1.0D0 ) GO TO 10
C
      IF( TBASE*DABS(M) .GE. 1.0D0 ) GO TO 20
      IF( DABS(M) .EQ. 0.0D0 ) RETURN
C
C     COMES TO HERE IF DABS(M) TOO LARGE OR TOO SMALL.
C
 10   CALL DUMKFL( M, TE, DMKFL )
      TE = E + TE
C
C     NOW M AND TE ARE OK.
C
C/6S
C20   IF( TE .GT. MAXEXP ) CALL SETERR( 16HDMKFL - OVERFLOW, 16, 1, 2 )
C/7S
 20   IF( TE .GT. MAXEXP ) CALL SETERR( 'DMKFL - OVERFLOW', 16, 1, 2 )
C/
C
      IF( TE .LT. MINEXP )  DMKFL = 0.0D0
C
      DMKFL = S3MACH( DMKFL, BASE, TE )
C
      RETURN
      END
