      SUBROUTINE DVDTOB( E10, M10, E, M )
C
C     DVDTOB CONVERTS A BASE 10 REPRESENTATION
C     OF A FLOATING POINT NUMBER INTO A MACHINE BASE
C     REPRESENTATION.
C
      DOUBLE PRECISION M, M10, L10B, BASE, DLOG10
      DOUBLE PRECISION D1MACH
      INTEGER E, E10
C
      DATA L10B / 0.0D0 /
      DATA BASE / 0.0D0 /
C
      IF( BASE .NE. 0.0D0 ) GO TO 1
        L10B = D1MACH(5)
        BASE = I1MACH(10)
C
 1    IF( M10 .NE. 0.0D0 ) GO TO 5
        M = 0.0D0
        E = 0
        RETURN
C
 5    M = DABS(M10)
      E = IDFLR( (DBLE(FLOAT(E10)) + DLOG10(M))/L10B )
      M = ( 10.0D0 ** (DBLE(FLOAT(E10)) - DBLE(FLOAT(E))*L10B) ) * M
C
 10   IF( M .LT. 1.0D0 ) GO TO 20
        M = M / BASE
        E = E + 1
        GO TO 10
C
 20   IF( M10 .LT. 0.0D0 ) M = -M
      RETURN
C
      END
