      REAL FUNCTION ORTHP(N, ALPHA, X, A, B, C)
      INTEGER N
      REAL ALPHA(1), X, A(1), B(1), C(1)
      INTEGER K
      REAL BETAK, BETAK1, BETAK2, Z
C  ORTHP IS A REAL FORTRAN FUNCTION WHICH RETURNS THE
C  VALUE OF A POLYNOMIAL, P(X), OF DEGREE N GIVEN BY AN
C  ORTHOGONAL EXPANSION.  THE ORTHOGONAL POLYNOMIALS OF THIS
C  EXPANSION ARE DEFINED BY THE THREE-TERM RECURRENCE
C  P0 = 1,  P1 = A(1)X + B(1), AND
C  PK+1 = (A(K+1)X + B(K+1))PK + C(K+1)PK-1.
C  N        - THE DEGREE OF P(X).
C  ALPHA    - THE N+1 COEFFICIENTS IN THE EXPANSION OF P(X).
C  X        - THE ARGUMENT AT WHICH P(X) IS TO BE EVALUATED.
C  A,B,C    - THE THREE SETS OF N COEFFICIENTS USED TO
C             DEFINE THE THREE-TERM RECURRENCE.
C  ERROR STATES-
C       1 - INVALID DEGREE.
C       2 - INVALID RECURRENCE.
C/6S
C     IF (N .LT. 0) CALL SETERR(22HORTHP - INVALID DEGREE, 22, 1, 2)
C/7S
      IF (N .LT. 0) CALL SETERR('ORTHP - INVALID DEGREE', 22, 1, 2)
C/
      IF (N .NE. 0) GOTO 1
         ORTHP = ALPHA(1)
         GOTO  5
   1     BETAK2 = ALPHA(N+1)
C/6S
C        IF (A(N) .EQ. 0.0) CALL SETERR(26HORTHP - INVALID RECURRENCE,
C    1      26, 2, 2)
C/7S
         IF (A(N) .EQ. 0.0) CALL SETERR('ORTHP - INVALID RECURRENCE',
     1      26, 2, 2)
C/
         BETAK1 = BETAK2*(A(N)*X+B(N))+ALPHA(N)
         K = N-1
            GOTO  3
   2        K = K-1
   3        IF (K .LT. 1)GOTO  4
C/6S
C           IF (A(K) .EQ. 0.0) CALL SETERR(
C    1         26HORTHP - INVALID RECURRENCE, 26, 2, 2)
C/7S
            IF (A(K) .EQ. 0.0) CALL SETERR(
     1         'ORTHP - INVALID RECURRENCE', 26, 2, 2)
C/
            Z = A(K)*X+B(K)
            BETAK = BETAK1*Z+BETAK2*C(K+1)+ALPHA(K)
            BETAK2 = BETAK1
            BETAK1 = BETAK
            GOTO  2
   4     ORTHP = BETAK1
   5  RETURN
      END
