      SUBROUTINE RANSET(ICSEED,ITSEED)
      INTEGER IBYTE(4)
      DATA IFCN/0/
C
C  TO (RE)INITIALIZE THE UNIFORM RANDOM NUMBER GENERATOR, R1UNIF
C  (TO OTHER THAN THE DEFAULT INITIAL VALUES).
C
C    ICSEED IS THE NEW SEED FOR CONGRUENTIAL GENERATOR.
C    ITSEED IS THE NEW SEED FOR TAUSWORTHE GENERATOR.
C
C  ONE, BUT NOT BOTH, OF THE NEW SEEDS CAN BE ZERO
C
C/6S
C     IF (ICSEED.EQ.0 .AND. ITSEED.EQ.0)
C    1   CALL SETERR(34HRANSET - INPUT SEEDS ARE BOTH ZERO,34,1,2)
C/7S
      IF (ICSEED.EQ.0 .AND. ITSEED.EQ.0)
     1   CALL SETERR('RANSET - INPUT SEEDS ARE BOTH ZERO',34,1,2)
C/
C
C  IFCN = 0 IMPLIES THAT UNI AND IBYTE ARE NOT COMPUTED.
C
      UNI=R1UNIF(ICSEED,ITSEED,IBYTE,IFCN)
      RETURN
      END
