      FUNCTION RNORM(IDUMMY)
C
      INTEGER ISW
      REAL F, TEMP, S, V1, V2
      DATA ISW/0/, F/0.E0/, V2/0.E0/
C
      IF(ISW .NE. 0) GO TO 20
 10   V1 = UNI(0)
      V2 = UNI(0)
C
      V1 = V1 + V1-1.0E0
      V2 = V2 + V2-1.0E0
C
C  IF THE SUM OF THE SQUARES IS NOT LESS THAN 1,
C  TRY AGAIN.
C
      S = V1*V1 + V2*V2
      IF(S .GE. 1.0E0) GO TO 10
C
C  OK - SO GIVE BACK ONE NORMAL DEVIATE AND
C  SAVE THE FACTOR, F FOR THE NEXT REQUEST.
C
      TEMP = ALOG(S)
      F = SQRT((-TEMP-TEMP)/S)
C
C  SET THE SWITCH TO USE THE SAVED STUFF NEXT TIME.
C
      ISW = 1
      RNORM = V1*F
      RETURN
C
C
C  ON THE EVEN TIMES IT COMES HERE TO USE THE SAVED STUFF.
C
 20   ISW = 0
      RNORM = V2*F
      RETURN
      END
