      LOGICAL FUNCTION SMONOI(X, N, INC)
      INTEGER INC
      INTEGER X(INC, 1), N
      INTEGER I
C   SMONOI IS AN LOGICAL FUNCTION WHICH INSPECTS THE INTEGER
C   VECTOR, X, AND RETURNS THE VALUE, TRUE, IF THE ARRAY IS STRICTLY
C   MONOTONE AND THE VALUE, FALSE, OTHERWISE.  THE VALUE, FALSE, IS
C   RETURNED ONLY IF THE ARRAY CONTAINS ELEMENTS WHICH CONTRADICT
C   THE PROPERTY.  IN PARTICULAR, VECTORS OF LENGTH 0 OR 1 RETURN TRUE.
C   X   - THE VECTOR OF POINTS TO BE CHECKED.
C   N   - THE DIMENSION OF THE VECTOR X.
C         N .LT. 0    IS A FATAL ERROR.
C   INC - THE INCREMENT IN THE VECTOR.
C         INC .LT. 1  IS A FATAL ERROR.
C/6S
C     IF (N .LT. 0) CALL SETERR(26HSMONOI - INVALID DIMENSION, 26, 1, 2)
C     IF (INC .LT. 1) CALL SETERR(26HSMONOI - INVALID INCREMENT, 26, 2
C    1   , 2)
C/7S
      IF (N .LT. 0) CALL SETERR('SMONOI - INVALID DIMENSION', 26, 1, 2)
      IF (INC .LT. 1) CALL SETERR('SMONOI - INVALID INCREMENT', 26, 2
     1   , 2)
C/
      SMONOI = .TRUE.
      IF (N .LT. 2) RETURN
C STRICTLY MONOTONE BY DEFAULT.
C CHECK FOR STRICTLY INCREASING.
      DO  1 I = 2, N
         IF (X(1, I-1) .GE. X(1, I)) GOTO  2
   1     CONTINUE
      RETURN
C CHECK FOR STRICLY DECREASING.
   2  DO  3 I = 2, N
         IF (X(1, I-1) .LE. X(1, I)) GOTO  4
   3     CONTINUE
      RETURN
   4  SMONOI = .FALSE.
C NOT STRICTLY MONOTONE.
      RETURN
      END
