      FUNCTION UNI(K)
      INTEGER IBYTE(4)
      DATA ICSEED/0/, ITSEED/0/, IFCN/1/
C
C  UNI IS RETURNED AS A SINGLE REAL RANDOM VARIATE
C  FROM THE UNIFORM DISTRIBUTION 0.0 .LE. UNI .LT. 1.0 .
C
C  IFCN = 1 IMPLIES THAT ICSEED, ITSEED, IBYTE, AND K ARE IGNORED.
C
      UNI=R1UNIF(ICSEED,ITSEED,IBYTE,IFCN)
      RETURN
      END
