      SUBROUTINE WRAPUP
      INTEGER LUSED, I1MACH, NERROR, ISTKST, LMAX, NERR
      INTEGER TEMP
C TO WRAP-UP A RUN BY CHECKING THE STACK AND ERROR STATES.
C/6S
C     IF (NERROR(NERR) .NE. 0) CALL SETERR(
C    1   36HWRAPUP - AN ERROR STATE IS LEFT OVER, 36, 1, 2)
C     IF (ISTKST(1) .GT. 0) CALL SETERR(
C    1   32HWRAPUP - STUFF LEFT ON THE STACK, 32, 2, 2)
C/7S
      IF (NERROR(NERR) .NE. 0) CALL SETERR(
     1   'WRAPUP - AN ERROR STATE IS LEFT OVER', 36, 1, 2)
      IF (ISTKST(1) .GT. 0) CALL SETERR(
     1   'WRAPUP - STUFF LEFT ON THE STACK', 32, 2, 2)
C/
      LUSED = ISTKST(3)
      LMAX = ISTKST(4)
      TEMP = I1MACH(2)
      WRITE (TEMP,  1) LUSED, LMAX
   1  FORMAT (6H USED , I8, 3H / , I8, 22H OF THE STACK ALLOWED.)
      RETURN
      END
