      SUBROUTINE FFTRI(NN,FR,FI)
C
C FFTCI FINDS THE INVERSE FOURIER TRANSFORM BY CALLING
C RLTR AND FFT WITH APPROPRIATE INFORMATION.
C THE RESULT OF THE INVERSE TRANSFORM IS EXPECTED TO BE
C REAL, AND TO CONTAIN AN EVEN NUMBER 2N, OF DATA POINTS.
C THE RESULT OF THE INVERSE TRANSFORM WILL BE PLACED, BY
C FFTRI, IN THE FIRST ARRAY, FR, WHICH MUST THEREFORE
C BE DIMENSIONED TO AT LEAST 2N, ALTHOUGH ONLY N+1 FOURIER
C COEFFICIENTS ARE INPUT IN THE ARRAYS, FR AND FI.
C
C STORAGE IN THE DYNAMIC STORAGE STACK IS REQUIRED FOR
C 220 INTEGER VARIABLES AND 92 REAL VARIABLES.
C
C     INPUT
C
C       NN    -2N, THE NUMBER OF REAL DATA POINTS
C              RESULTING FROM THE REQUESTED INVERSE TRANSFORM
C       FR    -A VECTOR OF LENGTH 2N CONTAINING, IN ITS FIRST N+1
C              LOCATIONS, THE REAL PART OF THE FOURIER COEFFICIENTS
C       FI    -A VECTOR OF LENGTH N+1 CONTAINING THE IMAGINARY
C              PART OF THE FOURIER COEFFICIENTS
C
C     OUTPUT
C
C       FR    -THE 2N REAL DATA RESULTING FROM THE INVERSE TRANSFORM
C
C NUMBER OF FACTORS OF N MUST NOT EXCEED 11.
C MAXIMUM PRIME FACTOR OF N MUST NOT EXCEED 23.
C PRODUCT OF THE SQUARE-FREE FACTORS, IF THERE EXISTS MORE THAN ONE,
C MUST NOT EXCEED 210.
C
C
C     ERROR STATES
C          1.  NN (2N) IS LESS THAN 4
C          2.  NN IS NOT EVEN
C          3.  PRIME FACTOR .GT. 23
C              (RECOVERABLE)
C          4.  SQUARE-FREE FACTOR PRODUCT .GT. 210
C              (RECOVERABLE)
C
C
C COMMON AREA
      COMMON/CSTAK/DSTAK(500)
C
      REAL FR(1),FI(1)
      DOUBLE PRECISION DSTAK
C
C  TEST THE VALIDITY OF THE INPUTS
C
C/6S
C     IF(NN .LT. 4) CALL SETERR(
C    1   26H FFTRI - NN IS LESS THAN 4,26,1,2)
C/7S
      IF(NN .LT. 4) CALL SETERR(
     1   ' FFTRI - NN IS LESS THAN 4',26,1,2)
C/
      J = NN
C/6S
C     IF (J/2*2 .NE. J) CALL SETERR(
C    1   33H FFTRI - NN IS NOT AN EVEN NUMBER,33,2,2)
C/7S
      IF (J/2*2 .NE. J) CALL SETERR(
     1   ' FFTRI - NN IS NOT AN EVEN NUMBER',33,2,2)
C/
C
C ENTER THE RECOVERY MODE (STORING THE PREVIOUS)
C
      CALL ENTER(1)
C
C  CALL THE SUBPROGRAMS, FFT AND RLTR
C
      N = NN/2
      CALL RLTR(FR,FI,N,-1)
      CALL FFT(FR,FI,N,N,N,-1)
C
C
C  CHECK FOR ERRORS FROM FFT
C
      IF (NERROR(NERR) .EQ. 0) GO TO 10
C
      CALL ERROFF
C
C/6S
C     IF (NERR .EQ. 5) CALL SETERR(
C    1   37H FFTRI - PRIME FACTOR GREATER THAN 23,37,3,1)
C/7S
      IF (NERR .EQ. 5) CALL SETERR(
     1   ' FFTRI - PRIME FACTOR GREATER THAN 23',37,3,1)
C/
C
C/6S
C     IF (NERR .EQ. 6) CALL SETERR(
C    1   45H FFTRI - SQUARE-FREE PRODUCT GREATER THAN 210,45,4,1)
C/7S
      IF (NERR .EQ. 6) CALL SETERR(
     1   ' FFTRI - SQUARE-FREE PRODUCT GREATER THAN 210',45,4,1)
C/
C
      GO TO 30
C
 10   CONTINUE
C
C THE TIME DOMAIN RESULTS, RETURNED BY THIS PROCESS, ALTERNATE
C IN THE VECTORS FR AND FI AS FR(1),FI(1),FR(2),FI(2),...FR(N),FI(N).
C THE FOLLOWING FRAGMENT RECOMBINES THEM INTO FR
C
      K = N
      DO 20 KK=1,N
      FR(2*K) = FI(K)
      FR(2*K-1) = FR(K)
 20   K = K-1
 30   CALL LEAVE
C
      RETURN
      END
