      SUBROUTINE C4NST(A, M, N, IA, S, P, V, W, AG, JDEPS,AS, PNRM,
     1   IPTS,IPTG,SIMP,ISIMP,AMAN,EPS,SCALE,X,THETA,T,IHIT,IERC,
     2   IFLAG)
C
C THIS SUBROUTINE LEAVES IN THETA THE DISTANCE ONE
C CAN TRAVEL ALONG THE DIRECTION P BEFORE HITTING
C THE INACTIVE CONSTRAINTS
C
C IF IHIT IS LESS THAN M, THE IHITTH GENERAL CONSTRAINT HAS BEEN
C HIT. IF GREATER THAN M, THEN THE IHITTH-M SIMPLE CONSTRAINT HAS BEEN
C HIT.
C
      INTEGER M, N, S, IA(1), ISIMP(1)
      EXTERNAL AMAN
      INTEGER AG, AS, IPTS(1), IPTG(1)
      REAL A(1), P(1), V(1), W(1), PNRM, EPS
      REAL SCALE(1), X(1)
      INTEGER NMS, AGP1, ASP1, I, K, II
      REAL T(1), TEMP1, THETA, SIMP(1),VV,WW,ET,FLOAT
      LOGICAL UNBNDD
      INTEGER IT1
      UNBNDD = .TRUE.
      IERC=0
      NMS = N-AS
      AGP1 = AG+1
      ASP1 = AS+1
      IF (M .LT. AGP1) GOTO  60
C
C DETERMINE THE DISTANCE TO THE NEAREST GENERAL CONSTRAINT
      IHN=N/2
      DO  50 IJ = AGP1, M
         I = IPTG(IJ)
         IF (AS.GT.IHN)GO TO 10
          CALL AMAN(.TRUE.,A,IA,N,I,P,V(I))
          GO TO 30
 10       CALL AMAN(.FALSE., A, IA, N, I, T, TEMP1)
          V(I) = 0.
          DO  20 II = 1, NMS
             IT1 = AS+II
             K = IPTS(IT1)
             V(I) = V(I)+T(K)*P(K)
 20          CONTINUE
 30       CONTINUE
         IF (V(I) .GE. 0.0E0) GOTO 50
C
C WE WILL HIT THE CONSTRAINT BE GOING IN THE DIRECTION P
C
C  JULY 1983, DAVID GAY DETERMINED BUG TROUBLE, AND
C  PHYL FOX COMMENTED OUT THE FOLLOWING LINE (S. P. VERSION ALSO)
C       IF (W(I).EQ.0.0E0.AND.IFLAG.EQ.1) GO TO 5
            IF (UNBNDD) GOTO 40
               IF (V(I)*THETA .GE. W(I)) GO TO 50
                   THETA=W(I)/V(I)
               IHIT=I
               GOTO  50
 40            UNBNDD = .FALSE.
C
C THIS IS THE FIRST CONSTRAINT ENCOUNTERED THAT EVEN
C IS IN THE RIGHT DIRECTION
C
               THETA = W(I)/V(I)
               IHIT=I
 50      CONTINUE
 60      CONTINUE
      JDEPS1=JDEPS+1
      IF (S .LT. JDEPS1) GOTO  90
C
C DETERMINE THE DISTANCE TO THE NEAREST SIMPLE CONSTRAINT
C
      DO  80 II = JDEPS1, S
       ET = SIGN(1.0E0, FLOAT(ISIMP(II)))
       I1 = IABS(ISIMP(II))
       VV = ET * P(I1)
       IF (VV .GE. 0.0E0) GOTO 80
       WW = ET*(SIMP(II)-X(I1))
       IF (UNBNDD) GOTO 70
       IF (THETA*VV .GE. WW) GO TO 80
           THETA=WW/VV
         IHIT=II+M
         GOTO 80
 70     UNBNDD = .FALSE.
        THETA = WW/VV
        IHIT=II+M
 80      CONTINUE
 90      CONTINUE
      IF (UNBNDD) GOTO 100
         RETURN
 100     IERC=6
 110  RETURN
      END
