      SUBROUTINE  D4CLM(U, AG, AS, E, UMAX, INDX2, FLAG, DVECS,
     1   DVECG, IPTG, IPTS, BOUND,IPHAS,KK,N,ICYCL)
C
C GIVEN THE LAGRANGE MULTIPLIERS, THIS SUBROUTINE DECIDES
C WHICH CONSTRAINT TO DROP.
C CURRENTLY THE DECISION IS MADE TO DROP THE ONE IWTH THE
C LARGEST LAGRANGE MULTIPLIER THAT HAS NOT BEEN
C DROPPED BEFORE A MINIMUM ON THE CURRENT SUBSPACE HAS
C BEEN FOUND
C
      INTEGER AG, AS, E, INDX2, FLAG, DVECG(1)
      INTEGER DVECS(1), IPTG(1), IPTS(1)
      REAL U(1), UMAX, BOUND
      INTEGER I, K, INDEX, EP1
      REAL   V5MAX, R1MACH
      INTEGER AGPAS
       EP1=E+1
      FLAG=1
      UMAX =  V5MAX(AG+AS, U(E+1), INDEX)
      INDX2 = INDEX+E
C     IF (UMAX.LT.R1MACH(4)*100.0E0) RETURN
      IF (UMAX.LT.0.0E0) RETURN
C
C SOMETHING MUST BE DROPPED
      IF (ICYCL.LT.2) GO TO 6
      DO 5 I=1,AG+AS
         IF (U(I+E).LT.0.0) GO TO 5
            INDEX=I
            INDX2=INDEX+E
            GO TO 6
5      CONTINUE
6     CONTINUE
C
      AGPAS=AG+AS
      DO 30 I=1,AGPAS
      FLAG=0
      IF (KK.EQ.N) RETURN
         IF(INDEX.LE.AG)GO TO 10
C SIMPLE CONSTRAINT
         K=INDEX-AG
          IF (DVECS(K).LT.1)RETURN
         GO TO 20
 10      K=IPTG(INDEX)
C LOOKING AT A GENERAL CONSTRAINT
         IF (DVECG(K).LT.1)RETURN
 20      U(INDX2)=-1.0E0
         FLAG=1
         IF( V5MAX(AGPAS,U(E+1),INDEX).LT.0.0E0) RETURN
         INDX2=INDEX+E
 30   CONTINUE
      RETURN
      END
