      SUBROUTINE DLPMAN(INNERP, A, M, N, K, X, SK)
      INTEGER M, N
      INTEGER K
      DOUBLE PRECISION A(M, N), X(N), SK
      LOGICAL INNERP
      INTEGER I
      DOUBLE PRECISION H
C   THIS PROCEDURE HANDLES THE MATRIX A, WHICH IS STORED IN
C   THE CONVENTIONAL FASHION.  IF THE MATRIX IS LARGE AND SPARSE
C   THE USER SHOULD REPLACE THIS ROUTINE WITH A MORE APPROPRIATE
C   ROUTINE.
C   INPUT
C   INNERP - IF TRUE THEN COMPUTE THE INNER PRODUCT OF ROW K WITH X.
C            OTHERWISE RETURN ROW K OF A IN THE VECTOR X.
C   A      - THE MATRIX A.
C   M,N    - THE ROW AND COLUMN DIMENSIONS OF A.
C   K      - THE INDEX OF THE ROW OF A WHICH IS TO BE PROCESSED.
C   X      - IF INNERP IS TRUE, THEN X IS A VECTOR WHOSE INNER
C            PRODUCT WITH ROW K OF A IS TO BE COMPUTED.
C   OUTPUT
C   X      - IF INNERP IS FALSE, THEN X CONTAINS ROW K OF A.
C   SK     - IF INNERP IS TRUE, THEN SK CONTAINS THE INNER
C            PRODUCT OF X AND ROW K OF A.
C/6S
C     IF (M .LE. 0 .OR. N .LE. 0) CALL SETERR(
C    1   24HDLPA - INVALID DIMENSION, 25, 1, 2)
C     IF (K .LT. 1 .OR. M .LT. K) CALL SETERR(20HDLPA - INVALID INDEX,
C    1   21, 2, 2)
C/7S
      IF (M .LE. 0 .OR. N .LE. 0) CALL SETERR(
     1   'DLPA - INVALID DIMENSION', 25, 1, 2)
      IF (K .LT. 1 .OR. M .LT. K) CALL SETERR('DLPA - INVALID INDEX',
     1   21, 2, 2)
C/
      IF (.NOT. INNERP) GOTO 20
         H = 0.D0
         DO  10 I = 1, N
            H = H+X(I)*A(K, I)
 10         CONTINUE
         SK = H
         GOTO  40
 20      DO  30 I = 1, N
            X(I) = A(K, I)
 30         CONTINUE
 40   RETURN
      END
