      SUBROUTINE IQP(N, X, Q, IQ, C, M, A, IA, B, BL, BU,
     1   IPRINT, MAXITR, IEQ)
      INTEGER IA, IQ, N
      INTEGER M, IPRINT, MAXITR
      REAL X(N), Q(IQ, N), C(N), A(IA, N), B(M), BL(N)
      REAL BU(N)
      REAL EPSI
      INTEGER ID, IE, IG, IT, JT
      INTEGER IY, IRES, IAC, I, INJ, IZL
      INTEGER IJSIM, IIRES
      INTEGER IEQ, IWUNIT
      REAL SDOT, R, R1MACH
      INTEGER IISIMP, IEXTRA, ILIM, IND, I1MACH
      INTEGER ICT, IRCT, INDI, INDD,IIND
C
      DOUBLE PRECISION DSTAK(500)
      COMMON /CSTAK/DSTAK
      INTEGER ISTAK(1000)
      REAL RSTAK(1000)
      EQUIVALENCE (DSTAK(1), ISTAK(1))
      EQUIVALENCE (DSTAK(1), RSTAK(1))
C
C THIS SUBROUTINE SOLVES THE INDEFINITE QUADRATIC
C PROGRAMMING PROBLEM OF MINIMIZING
C           T      T
C          X QX/2+C X
C SUCH THAT
C        AX.GE.B
C   AND
C         BL(I).LE.X(I).LE.BU(I).I=1,...,N
C
C PARAMETERS ON INPUT
C   N       ORDER OF PROBLEM
C   X       INITIAL GUESS, NEED NOT SATISFY CONSTRAINTS
C   Q       N X N SYMMETRIC MATRIX,MAY BE INDEFINITE.
C           MUST BE FILLED IN COMPLETELY, STRICTLY
C           LOWER TRIANGLE DESTROYED
C   IQ      LEADING DIMENSION OF Q. MUST BE AT LEAST N
C   C       VECTOR IN LINEAR TERM OF FUNCTION TO BE MINIMIZED
C   IEQ     NUMBER OF LINEAR EQUALITY CONSTRAINTS
C   M       NUMBER OF LINEAR INEQUALITY CONSTRAINTS
C   A       M X N MATRIX OF LINEAR CONSTRAINTS
C   IA      LEADING DIMENSION OF A, MUST BE AT LEAST M
C   B       RIGHT HAND SIDE VECTOR OF CONSTRAINTS
C   BL      LOWER BOUND ON VARIABLES
C   BU      UPPER BOUND ON VARIABLES
C   IPRINT  IF IPRINT IS GREATER THAN 0,THEN THE FUNCTION,GRADIENT,
C           APPROXIMATE SOLUTION WILL BE PRINTED EACH ITERATION.
C           FEASABILITY CONDITIONS FROM FEAS WILL ALSO BE PRINTED.
C  MAXITR   MAXIMUM NUMBER OF ITERATIONS PERMITTED
C
C OUTPUT PARAMETERS
C   X       SOLUTION OF THE PROBLEM
C
C SCRATCH STORAGE (ALLOCATED FROM THE PORT STACK)
C RSTAK     REAL ARRAY OF LENGTH AT LEAST M+(4+N)N LOCATIONS
C           (UNLESS (N.GT.M) WHEN (5+N)N LOCATIONS WILL BE ALLOCATED)
C ISTAK     INTEGER ARRAY OF LENGTH AT LEAST 4N + M LOCATIONS
C       ISTAK(1...N) = INEQUALITY, EQUALITY FOR UPPER AND LOWER BOUNDS
C       ISTAK(N+1...N+M) = EQUALITY, INEQUALITY FOR MATRIX CONSTRAINTS
C       ISTAK(N+M+1...3N+M) = ISIMP FOR FEASA
C       ISTAK(3N+M+1...4N+M) = STORAGE SPACE FOR READING OFF ISIMP
C CHECK FOR ERRORS
C
        CALL ENTER(1)
        IWUNIT = I1MACH(2)
        EPSI = R1MACH(4)
C/6S
C     IF ((N .LT. 1).OR.(M .LT. 0))
C    1  CALL SETERR(20HIQP-N.LT.1 OR M.LT.0,20,1,2)
C     IF (MAXITR .LT. 1) CALL SETERR(15HIQP-MAXITR.LT.1,15,2,2)
C     IF (IQ .LT. N) CALL SETERR(11HIQP-IQ.LT.N,11,3,2)
C     IF (IA .LT. M) CALL SETERR(11HIQP-IA.LT.M,11,4,2)
C     IF ((IEQ .GT. N).OR.(IEQ .GT. M).OR.(IEQ .LT. 0))
C    1  CALL SETERR(36HIQP-IEQ.GT.N OR IEQ.GT.M OR IEQ.LT.0,36,5,2)
C/7S
      IF ((N .LT. 1).OR.(M .LT. 0))
     1  CALL SETERR('IQP-N.LT.1 OR M.LT.0',20,1,2)
      IF (MAXITR .LT. 1) CALL SETERR('IQP-MAXITR.LT.1',15,2,2)
      IF (IQ .LT. N) CALL SETERR('IQP-IQ.LT.N',11,3,2)
      IF (IA .LT. M) CALL SETERR('IQP-IA.LT.M',11,4,2)
      IF ((IEQ .GT. N).OR.(IEQ .GT. M).OR.(IEQ .LT. 0))
     1  CALL SETERR('IQP-IEQ.GT.N OR IEQ.GT.M OR IEQ.LT.0',36,5,2)
C/
C USE FEASA TO GET A FEASIBLE SOLUTION (OR CHECK FEASIBILITY OF CURRENT
C SOLUTION.)
C
C GET SPACE FOR FEASA AND TRANSLATION
      IAC = ISTKGT(M,2)
      IISIMP = ISTKGT(2*N,2)
      INDD = ISTKGT(2*N,3)
      CALL Q6INT(A, M, N, IA, B, X, BL, BU, RSTAK(INDD),
     1   ISTAK(IISIMP),
     2   ISTAK(IAC), IAS, IAG, MAXITR, IPRINT, IEQ, IWUNIT)
C
      CALL ISTKRL(1)
      IF ((NERROR(NERR).NE.6).AND.(NERROR(NERR).NE.8)
     1    .AND.(NERROR(NERR).NE.9))  GO TO 301
      CALL ERROFF
C/6S
C     IF (NERROR(NERR).EQ.6) CALL SETERR (18HIQP-ITER.GT.MAXITR,18,8,1)
C     IF (NERROR(NERR).EQ.8) CALL SETERR (16HIQP-NO FEAS. SOL,16,9,1)
C     IF (NERROR(NERR).EQ.9) CALL SETERR (17HIQP-COND. PROBLEM,17,10,1)
C/7S
      IF (NERROR(NERR).EQ.6) CALL SETERR ('IQP-ITER.GT.MAXITR',18,8,1)
      IF (NERROR(NERR).EQ.8) CALL SETERR ('IQP-NO FEAS. SOL',16,9,1)
      IF (NERROR(NERR).EQ.9) CALL SETERR ('IQP-COND. PROBLEM',17,10,1)
C/
      CALL LEAVE
      RETURN
 301  CONTINUE
      IRCT = 2*M + (3+N) * N
      IF (N.GT.M) IRCT = (4+N) * N + M
      ICT = 2*N
      INDD = ISTKGT(IRCT, 3)
      INDI = ISTKGT(ICT, 2)
      IZL = INDD
      IY = IZL+N*N
      IE = IY+N
      ID = IE+N
      IG = ID+N
      MN=M
      IF(N.GT.M) MN=N
      IRES = IG+MN
      IJSIM = INDI
      INJ = IJSIM
      IEXTRA = IJSIM+N
      JT = IEXTRA-1
      ILIM = IEXTRA+N-1
      DO  1 I = IEXTRA, ILIM
         ISTAK(I) = 0
 1    CONTINUE
C
      IF (IAS.EQ.0) GO TO 19
      DO  2 I = 1, IAS
         IIND = IISIMP + I - 1
         IND = IEXTRA + IABS(ISTAK(IIND)) - 1
         ISTAK(IND) = 1
 2    CONTINUE
 19   CONTINUE
      DO  3 I = 1,N
         IND = IEXTRA + I - 1
         IF(ISTAK(IND).NE.1) GO TO 4
         ISTAK(JT) = I
         JT = JT - 1
         GO TO 3
 4       ISTAK(INJ) = I
         INJ = INJ + 1
 3    CONTINUE
      IT = IAG + IEQ
      JT = N - IAS
      ILIM = 2*N + INDD
      DO 8 I=INDD,ILIM
        RSTAK(I) = 0.
 8    CONTINUE
      IIRES = IRES - 1
      IF (M.LT.1) GO TO 9
      DO 10 I=1,M
        R = SDOT(N,A(I,1),IA,X,1) - B(I)
        IIRES = IIRES + 1
        IF (R.LT.0.) R = 0.
        RSTAK(IIRES) = R
 10   CONTINUE
 9    CONTINUE
C
      CALL Q6IQP(X, N, A, IA, RSTAK(IRES), M, Q, IQ, C, BL, BU, IT
     1   , JT, ISTAK(IJSIM), ISTAK(IAC), RSTAK(ID), RSTAK(IE)
     2   , RSTAK(IY), RSTAK(IZL), RSTAK(IG), IPRINT, MAXITR
     3   , IEQ, IERR, IWUNIT, EPSI, B)
C/6S
C     IF (IERR.EQ.1) CALL SETERR(18HIQP-ITER.GT.MAXITR,17,6,1)
C     IF (IERR.EQ.2) CALL SETERR(22HIQP-UNBOUNDED SOLUTION,21,7,1)
C/7S
      IF (IERR.EQ.1) CALL SETERR('IQP-ITER.GT.MAXITR',17,6,1)
      IF (IERR.EQ.2) CALL SETERR('IQP-UNBOUNDED SOLUTION',21,7,1)
C/
      CALL LEAVE
      RETURN
      END
