        SUBROUTINE Q6INT(A, M, N, IA, B, X, BL, BU, SIMP, ISIMP, IPTG,
     1          IAS, IAG, MAXITR, IPRINT, IE, IWUNIT)
C
C THIS SUBROUTINE PROVIDES AN INTERFACE BETWEEN QP (IN QPPAK.F)
C AND FEASA (IN LPH11T.F)
C
C PARAMETERS ON INPUT
C   N       ORDER OF PROBLEM
C   X       INITIAL GUESS, NEED NOT SATISFY CONSTRAINTS
C   IE      NUMBER OF LINEAR EQUALITY CONSTRAINTS
C   M       NUMBER OF LINEAR EQUALITY AND INEQUALITY CONSTRAINTS
C   A       M X N MATRIX OF LINEAR CONSTRAINTS
C   IA      LEADING DIMENSION OF A, MUST BE AT LEAST M
C   B       RIGHT HAND SIDE VECTOR OF CONSTRAINTS
C   BL      LOWER BOUND ON VARIABLES
C   BU      UPPER BOUND ON VARIABLES
C   SIMP    VECTOR CONTAINING SIMPLE CONSTRAINTS
C   S       NUMBER OF SIMPLE CONSTRAINTS
C   ISIMP   VECTOR TELLING THE ELEMENT OF X THAT THE SIMPLE
C           CONSTRAINT PERTAINS TO.  IF NEGATIVE IT IS AN UPPER
C           BOUND OTHERWISE IT IS A LOWER BOUND.
C   IPRINT  IF IPRINT IS GREATER THAN 0,THEN THE FUNCTION,GRADIENT,
C           APPROXIMATE SOLUTION WILL BE PRINTED EACH ITERATION.
C           FEASABILITY CONDITIONS FROM FEAS WILL ALSO BE PRINTED.
C   MAXITR  MAXIMUM NUMBER OF ITERATIONS PERMITTED
C
C   PARAMETERS ON OUTPUT
C
C   X       FEASIBLE SOLUTION COMPUTED BY FEASA
C
        DOUBLE PRECISION DSTAK(500)
        COMMON/CSTAK/DSTAK
        INTEGER M, N, IA, IFLAG
        REAL A(IA,N), B(M), X(N), BL(N), BU(N)
        INTEGER ICT, ISIMP(1), MAXITR, IE, IPTG(M), SMAX, IAG, IAS
        INTEGER IPRINT, IWUNIT, IND
        REAL SIMP(1)
        EXTERNAL LPRNT, QP1NT
        EXTERNAL LPMAN
C
        IFLAG = 0
C TRANSLATE BL AND BU TO SIMP AND ISIMP
        DO 1 I=1,N
            SIMP(I) = BL(I)
            ISIMP(I) = I
            IND = N + I
            SIMP(IND) = BU(I)
            ISIMP(IND) = -I
 1      CONTINUE
        ICT = 2*N
        SMAX = MAXITR
C
 100    CONTINUE
        IF (IPRINT.LE.0) GOTO 2
            CALL FEASA(A, M, N, LPMAN, IA, B, X, SMAX, ICT, SIMP,
     1          ISIMP, IE, QP1NT, IAG, IAS, IPTG)
            GO TO 31
 2      CALL FEASA(A, M, N, LPMAN, IA, B, X, SMAX, ICT, SIMP, ISIMP,
     1      IE, LPRNT, IAG, IAS, IPTG)
C NO. OF ITERATIONS .GT. MAXITR
 31        IF (NERROR(NERR).NE.6) GO TO 106
           IF (IFLAG.NE.0) GO TO 3
           IFLAG = 1
           SMAX = 3*N
           CALL ERROFF
           GOTO 100
C NO FEASIBLE SOLUTION
 106    IF (NERROR(NERR).EQ.8) GO TO 3
C CONDITIONING PROBLEM
        IF ((NERROR(NERR).NE.9).OR.(IFLAG.NE.0)) GO TO 3
           IFLAG = 1
           CALL ERROFF
           GO TO 100
C
 3      RETURN
        END
